version: 2
registries: # Define access for private registries
  fp-felles:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-felles
    username: x-access-token
    password: ${{ secrets.PAT }}

updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries: # Allow version updates for dependencies in this registry
      - fp-felles
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "no.nav.vedtak.prosesstask:*"
        versions: ["x", "x.x"]
      - dependency-name: "no.nav.foreldrepenger.felles:*"
        versions: ["x", "x.x"]
      - dependency-name: "no.nav.foreldrepenger.kontrakter:*"
        versions: ["x", "x.x"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
