package no.nav.foreldrepenger.tilbakekreving.kontrakter.felles;

public enum BehandlingResultat {
    IKKE_FASTSATT,
    FASTSATT,
    INGEN_TILBAKEBETALING,
    DELVIS_TILBAKEBETALING,
    FULL_TILBAKEBETALING,
    HENLAGT_FEILOPPRETTET,
    HENLAGT_FEILOPPRETTET_MED_BREV,
    HENLAGT_FEILOPPRETTET_UTEN_BREV,
    HENLAGT_KRAVGRUNNLAG_NULLSTILT,
    HENLAGT_TEKNISK_VEDLIKEHOLD
}
