alter database set TIME_ZONE='Europe/Oslo';
alter system set recyclebin=OFF DEFERRED;
alter profile default limit password_life_time unlimited;
alter system set processes=150 scope=spfile;
alter system set session_cached_cursors=100 scope=spfile;
alter system set session_max_open_files=100 scope=spfile;
alter system set sessions=100 scope=spfile;
alter system set license_max_sessions=100 scope=spfile;
alter system set license_sessions_warning=100 scope=spfile;
GRANT CREATE USER, CONNECT, RESOURCE, DBA, ALTER SESSION TO vl_dba WITH ADMIN OPTION;
alter session set NLS_DATE_LANGUAGE='NORWEGIAN';
alter session set NLS_LANGUAGE='NORWEGIAN';
alter session set NLS_SORT='NORWEGIAN';
alter session set NLS_TERRITORY='NORWAY';
alter session set NLS_CURRENCY='kr';
alter session set NLS_ISO_CURRENCY='NORWAY';
alter session set NLS_DATE_FORMAT='DD.MM.RRRR';
alter session set NLS_TIMESTAMP_FORMAT='DD.MM.RRRR HH24.MI.SSXFF';
alter session set NLS_TIMESTAMP_TZ_FORMAT='DD.MM.RRRR HH24.MI.SSXFF TZR';
