name: Generate typescript client
description: Generate typescript client from openapi spec.
inputs:
  openapiVersion:
    description: The openapi version extracted from openapi.json
    required: true
  patchVersion:
    description: 'The <TIMESTAMP>-<SHA> value used as a tag of the version for deployment.'
    required: true
outputs:
  resultDir:
    description: Directory in which the generated typescript client package was written
    value: ${{ steps.set-output.outputs.resultDir }}

runs:
  using: 'composite'
  steps:
    - name: Set resultDir
      id: set-output
      shell: bash
      run: echo "resultDir=web/target/ts-client/k9" >> $GITHUB_OUTPUT
    - name: Typescript generate
      id: typescript-generate
      uses: navikt/openapi-ts-clientmaker@v2
      with:
        openapi-spec-file: web/src/main/resources/openapi-ts-client/k9/k9-tilbake.openapi.json
        package-json-file: web/src/main/resources/openapi-ts-client/k9/package.json
        package-json-version: "${{ env.PACKAGE_JSON_VERSION }}"
        out-dir: "${{ steps.set-output.outputs.resultDir }}"
      env:
        PACKAGE_JSON_VERSION: "${{ inputs.openapiVersion }}.${{ inputs.patchVersion }}"
