apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fptilbake
  namespace: NAMESPACE_VAL
  labels:
    team: teamforeldrepenger
spec:
  image: repo.adeo.no:5443/fptilbake:RELEASE_VERSION
  port: 8080
  team: teamforeldrepenger
  liveness:
    path: /fptilbake/internal/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  readiness:
    path: /fptilbake/internal/isReady
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  replicas:
    min: 1
    max: 3
    cpuThresholdPercentage: 80
  preStopHookPath: /fptilbake/internal/preStop # Optional. A HTTP GET will be issued to this endpoint at least once before the pod is terminated.
  # See https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
  prometheus: # Optional.
    enabled: true # if true the pod will be scraped for metrics by prometheus
    path: /fptilbake/internal/metrics/prometheus # Path to prometheus-metrics
  istio: # Optional.
    enabled: false # Optional. When true, envoy-proxy sidecar will be injected into pod and https urls envvars will be rewritten
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - "ingress_url1"
    - "ingress_url2"
  logformat: accesslog # Optional. The format of the logs from the container if the logs should be handled differently than plain text or json
  logtransform: dns_loglevel # Optional. The transformation of the logs, if they should be handled differently than plain text or json
  webproxy: false # Optional. Expose web proxy configuration to the application using the HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables.
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/defaultDSconfig
        kvPath: oracle.config.kv
      - mountPath: /var/run/secrets/nais.io/defaultDS
        kvPath:  oracle.secret.kv
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: fptilbake.serviceuser.kv
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: app.secret.kv
      - mountPath: /var/run/secrets/nais.io/ldap
        kvPath: ldap.serviceuser.kv
  sidecar: true # refresh token
  env:
    - name: APP_NAME
      value: fptilbake
    - name: APP_VERSION
      value: "RELEASE_VERSION"
    - name: APP_TEAM
      value: teamforeldrepenger
    - name: LOADBALANCER_FQDN
      value: loadbalancer.url
    - name: ABAC_PDP_ENDPOINT_URL
      value: abac_pdp_endpoint.url
    - name: SECURITYTOKENSERVICE_URL
      value: securitytokenservice.url
    - name: FPSAK_PIP_AKTOER_FOR_SAK_URL
      value: fpsak_pip_aktoer_for_sak.url

    # Systembruker konfigurasjoner hentes fra vault.
    # OIDC
    - name: OIDC_OPENAM_JWKSURL
      value: oidc_openam.jwksurl
    - name: OIDC_OPENAM_ISSUERURL
      value: oidc_openam.issuerurl
    - name: OIDC_OPENAM_AGENTNAME
      value: oidc_openam.agentname
    - name: OIDC_OPENAM_HOSTURL
      value: oidc_openam.hosturl

    # LDAP
    - name: LDAP_URL
      value: ldap.url
    - name: LDAP_BASEDN
      value: ldap.basedn
    - name: LDAP_DOMAIN
      value: ldap.domain
    - name: LDAP_USER_BASEDN
      value: ldap_user.basedn
    - name: LDAP_SERVICEUSER_BASEDN
      value: ldap_serviceuser.basedn

    # Database konfigurasjoner hentes fra vault.
    # Køer
    - name: MQGATEWAY02_NAME
      value: mqGateway02.name
    - name: MQGATEWAY02_HOSTNAME
      value: mqGateway02.hostname
    - name: MQGATEWAY02_PORT
      value: mqGateway02.port
    - name: FPSAK_CHANNEL_NAME
      value: fpsak_channel.name
    - name: FPSAK_CHANNEL_QUEUEMANAGER
      value: fpsak_channel.queuemanager
    - name: FPTILBAKE_KRAVGRUNNLAG_QUEUENAME
      value: fptilbake_kravgrunnlag.queuename
    - name: FPTILBAKE_KRAVGRUNNLAG_QUEUEMANAGER
      value: fptilbake_kravgrunnlag.queuemanager

    # Eksterne systemer
    - name: PERSON_V3_URL
      value: person_v3.url
    - name: TILBAKEKREVING_V1_URL
      value: tilbakekreving_service.url
    - name: AKTOER_V2_URL
      value: aktoer_v2.url
    - name: JOURNAL_V3_URL
      value: journal_v3.url
    - name: DOKUMENTPRODUKSJON_V2_URL
      value: dokumentproduksjon_v2.url
    - name: BOOTSTRAP_SERVERS
      value: kafka_brokers.url
    - name: FP_TILKJENTYTELSE_V1_TOPIC_URL
      value: fp_tilkjentytelse_v1_topic.url
    - name: TILBAKEKREVING_BRUKERDIALOG_HENDELSE_V1_TOPIC_URL
      value: tilbakekreving_brukerdialog_hendelse_v1_topic.url
    - name: TILBAKEKREVING_FPLOS_HENDELSE_V1_TOPIC_URL
      value: kafka_fplos.topic
    - name: TILBAKEKREVING_FPLOS_HENDELSE_V1_CLIENT_ID
      value: kafka_fplos_client.id
    - name: TILBAKEKREVING_FPLOS_HENDELSE_V1_REGISTRY_URL
      value: kafka_fplos_schema_registry.url



