alter table HISTORIKKINNSLAG2 set unused (MIGRERT_FRA_ID);
drop table HISTORIKKINNSLAG_DOK_LINK;
drop table HISTORIKKINNSLAG_FELT;
drop table HISTORIKKINNSLAG_DEL;
drop table HISTORIKKINNSLAG;

drop sequence SEQ_HISTORIKKINNSLAG_DOK_LINK;
drop sequence SEQ_HISTORIKKINNSLAG_FELT;
drop sequence SEQ_HISTORIKKINNSLAG_DEL;
drop sequence SEQ_HISTORIKKINNSLAG;
