//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.11.13 at 03:06:23 PM CET
//


package no.nav.foreldrepenger.tilbakekreving.kontrakter.kravgrunnlag.tilbakekrevingsvedtak.vedtak.v1;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import no.nav.tilbakekreving.typer.v1.Periode;


/**
 *  442 - Tilbakekrevingsperiode
 *
 * <p>Java class for Tilbakekrevingsperiode complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Tilbakekrevingsperiode"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="periode" type="{urn:no:nav:tilbakekreving:typer:v1}Periode"/&gt;
 *         &lt;element name="renterBeregnes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="belopRenter" type="{urn:no:nav:tilbakekreving:typer:v1}belop" minOccurs="0"/&gt;
 *         &lt;element name="tilbakekrevingsbelop" type="{urn:no:nav:tilbakekreving:tilbakekrevingsvedtak:vedtak:v1}Tilbakekrevingsbelop" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tilbakekrevingsperiode", propOrder = {
    "periode",
    "renterBeregnes",
    "belopRenter",
    "tilbakekrevingsbelop"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
public class Tilbakekrevingsperiode {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected Periode periode;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected String renterBeregnes;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected BigDecimal belopRenter;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected List<Tilbakekrevingsbelop> tilbakekrevingsbelop;

    /**
     * Gets the value of the periode property.
     *
     * @return
     *     possible object is
     *     {@link Periode }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public Periode getPeriode() {
        return periode;
    }

    /**
     * Sets the value of the periode property.
     *
     * @param value
     *     allowed object is
     *     {@link Periode }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setPeriode(Periode value) {
        this.periode = value;
    }

    /**
     * Gets the value of the renterBeregnes property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public String getRenterBeregnes() {
        return renterBeregnes;
    }

    /**
     * Sets the value of the renterBeregnes property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setRenterBeregnes(String value) {
        this.renterBeregnes = value;
    }

    /**
     * Gets the value of the belopRenter property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public BigDecimal getBelopRenter() {
        return belopRenter;
    }

    /**
     * Sets the value of the belopRenter property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setBelopRenter(BigDecimal value) {
        this.belopRenter = value;
    }

    /**
     * Gets the value of the tilbakekrevingsbelop property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tilbakekrevingsbelop property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTilbakekrevingsbelop().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tilbakekrevingsbelop }
     *
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public List<Tilbakekrevingsbelop> getTilbakekrevingsbelop() {
        if (tilbakekrevingsbelop == null) {
            tilbakekrevingsbelop = new ArrayList<Tilbakekrevingsbelop>();
        }
        return this.tilbakekrevingsbelop;
    }

}
