<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>integrasjontjenester</artifactId>
        <groupId>no.nav.foreldrepenger.tilbakekreving</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>sokos-klient</artifactId>
    <packaging>jar</packaging>
    <name>FPTILBAKE :: Integrasjontjenester - Sokos</name>

    <dependencies>
        <!-- Interne avhengigheter -->
        <dependency>
            <groupId>no.nav.foreldrepenger.tilbakekreving</groupId>
            <artifactId>behandlingslager-domene</artifactId>
        </dependency>

        <dependency>
            <groupId>no.nav.foreldrepenger.felles.integrasjon</groupId>
            <artifactId>felles-integrasjon-rest-klient</artifactId>
        </dependency>
        <dependency>
            <groupId>no.nav.foreldrepenger.felles</groupId>
            <artifactId>felles-feil</artifactId>
        </dependency>
        <dependency>
            <groupId>no.nav.foreldrepenger.felles</groupId>
            <artifactId>felles-mapper</artifactId>
        </dependency>
        <dependency>
            <groupId>no.nav.foreldrepenger.felles</groupId>
            <artifactId>felles-log</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
        </dependency>
    </dependencies>
</project>
