//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.11.13 at 03:06:23 PM CET
//


package no.nav.foreldrepenger.tilbakekreving.kontrakter.kravgrunnlag.retur.v1;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import no.nav.tilbakekreving.typer.v1.Periode;
import no.nav.tilbakekreving.typer.v1.TypeGjelder;


/**
 *  421 - Returnert kravgrunnlag
 *
 * <p>Java class for ReturnertKravgrunnlag complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ReturnertKravgrunnlag"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="kravgrunnlagId" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="kodeStatusKrav" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="gjelderId" type="{urn:no:nav:tilbakekreving:typer:v1}FnrOrgnr"/&gt;
 *         &lt;element name="typeGjelderId" type="{urn:no:nav:tilbakekreving:typer:v1}TypeGjelder"/&gt;
 *         &lt;element name="utbetalesTilId" type="{urn:no:nav:tilbakekreving:typer:v1}FnrOrgnr"/&gt;
 *         &lt;element name="typeUtbetId" type="{urn:no:nav:tilbakekreving:typer:v1}TypeGjelder"/&gt;
 *         &lt;element name="kodeFagomraade" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fagsystemId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="datoVedtakFagsystem" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="enhetBosted" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="enhetAnsvarlig" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="datoKravDannet" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="periode" type="{urn:no:nav:tilbakekreving:typer:v1}Periode"/&gt;
 *         &lt;element name="belopSumFeilutbetalt" type="{urn:no:nav:tilbakekreving:typer:v1}belop"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReturnertKravgrunnlag", propOrder = {
    "kravgrunnlagId",
    "kodeStatusKrav",
    "gjelderId",
    "typeGjelderId",
    "utbetalesTilId",
    "typeUtbetId",
    "kodeFagomraade",
    "fagsystemId",
    "datoVedtakFagsystem",
    "enhetBosted",
    "enhetAnsvarlig",
    "datoKravDannet",
    "periode",
    "belopSumFeilutbetalt"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
public class ReturnertKravgrunnlag {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected BigInteger kravgrunnlagId;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected String kodeStatusKrav;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected String gjelderId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected TypeGjelder typeGjelderId;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected String utbetalesTilId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected TypeGjelder typeUtbetId;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected String kodeFagomraade;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected String fagsystemId;
    @XmlSchemaType(name = "date")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected XMLGregorianCalendar datoVedtakFagsystem;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected String enhetBosted;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected String enhetAnsvarlig;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected XMLGregorianCalendar datoKravDannet;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected Periode periode;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    protected BigDecimal belopSumFeilutbetalt;

    /**
     * Gets the value of the kravgrunnlagId property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public BigInteger getKravgrunnlagId() {
        return kravgrunnlagId;
    }

    /**
     * Sets the value of the kravgrunnlagId property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setKravgrunnlagId(BigInteger value) {
        this.kravgrunnlagId = value;
    }

    /**
     * Gets the value of the kodeStatusKrav property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public String getKodeStatusKrav() {
        return kodeStatusKrav;
    }

    /**
     * Sets the value of the kodeStatusKrav property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setKodeStatusKrav(String value) {
        this.kodeStatusKrav = value;
    }

    /**
     * Gets the value of the gjelderId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public String getGjelderId() {
        return gjelderId;
    }

    /**
     * Sets the value of the gjelderId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setGjelderId(String value) {
        this.gjelderId = value;
    }

    /**
     * Gets the value of the typeGjelderId property.
     *
     * @return
     *     possible object is
     *     {@link TypeGjelder }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public TypeGjelder getTypeGjelderId() {
        return typeGjelderId;
    }

    /**
     * Sets the value of the typeGjelderId property.
     *
     * @param value
     *     allowed object is
     *     {@link TypeGjelder }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setTypeGjelderId(TypeGjelder value) {
        this.typeGjelderId = value;
    }

    /**
     * Gets the value of the utbetalesTilId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public String getUtbetalesTilId() {
        return utbetalesTilId;
    }

    /**
     * Sets the value of the utbetalesTilId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setUtbetalesTilId(String value) {
        this.utbetalesTilId = value;
    }

    /**
     * Gets the value of the typeUtbetId property.
     *
     * @return
     *     possible object is
     *     {@link TypeGjelder }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public TypeGjelder getTypeUtbetId() {
        return typeUtbetId;
    }

    /**
     * Sets the value of the typeUtbetId property.
     *
     * @param value
     *     allowed object is
     *     {@link TypeGjelder }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setTypeUtbetId(TypeGjelder value) {
        this.typeUtbetId = value;
    }

    /**
     * Gets the value of the kodeFagomraade property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public String getKodeFagomraade() {
        return kodeFagomraade;
    }

    /**
     * Sets the value of the kodeFagomraade property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setKodeFagomraade(String value) {
        this.kodeFagomraade = value;
    }

    /**
     * Gets the value of the fagsystemId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public String getFagsystemId() {
        return fagsystemId;
    }

    /**
     * Sets the value of the fagsystemId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setFagsystemId(String value) {
        this.fagsystemId = value;
    }

    /**
     * Gets the value of the datoVedtakFagsystem property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public XMLGregorianCalendar getDatoVedtakFagsystem() {
        return datoVedtakFagsystem;
    }

    /**
     * Sets the value of the datoVedtakFagsystem property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setDatoVedtakFagsystem(XMLGregorianCalendar value) {
        this.datoVedtakFagsystem = value;
    }

    /**
     * Gets the value of the enhetBosted property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public String getEnhetBosted() {
        return enhetBosted;
    }

    /**
     * Sets the value of the enhetBosted property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setEnhetBosted(String value) {
        this.enhetBosted = value;
    }

    /**
     * Gets the value of the enhetAnsvarlig property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public String getEnhetAnsvarlig() {
        return enhetAnsvarlig;
    }

    /**
     * Sets the value of the enhetAnsvarlig property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setEnhetAnsvarlig(String value) {
        this.enhetAnsvarlig = value;
    }

    /**
     * Gets the value of the datoKravDannet property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public XMLGregorianCalendar getDatoKravDannet() {
        return datoKravDannet;
    }

    /**
     * Sets the value of the datoKravDannet property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setDatoKravDannet(XMLGregorianCalendar value) {
        this.datoKravDannet = value;
    }

    /**
     * Gets the value of the periode property.
     *
     * @return
     *     possible object is
     *     {@link Periode }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public Periode getPeriode() {
        return periode;
    }

    /**
     * Sets the value of the periode property.
     *
     * @param value
     *     allowed object is
     *     {@link Periode }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setPeriode(Periode value) {
        this.periode = value;
    }

    /**
     * Gets the value of the belopSumFeilutbetalt property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public BigDecimal getBelopSumFeilutbetalt() {
        return belopSumFeilutbetalt;
    }

    /**
     * Sets the value of the belopSumFeilutbetalt property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2020-11-13T03:06:23+01:00", comments = "JAXB RI v2.3.0")
    public void setBelopSumFeilutbetalt(BigDecimal value) {
        this.belopSumFeilutbetalt = value;
    }

}
