kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: fptilbake
  namespace: {{namespace}}
  labels:
    team: teamforeldrepenger
spec:
  image:  {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /fptilbake/internal/health/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  readiness:
    path: /fptilbake/internal/health/isReady
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  prometheus:
    enabled: true
    path: /fptilbake/internal/metrics/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 80
  leaderElection: false
  istio: # Optional.
    enabled: false
  resources:
    limits:
      cpu: "2000m"
      memory: "1400Mi"
    requests:
      cpu: "200m"
      memory: "1400Mi"
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/defaultDSconfig
        kvPath: {{oracleconfig}}
      - mountPath: /var/run/secrets/nais.io/defaultDS
        kvPath:  {{oraclefptilbakesecret}}
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: {{fptilbakeserviceuser}}
      - mountPath: /var/run/secrets/nais.io/ldap
        kvPath: {{ldapserviceuser}}
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/{{cluster}}/fss/fptilbake/{{namespace}}
  env:
  # miljø-spesifikke variable
  {{#each env}}
   - name: {{@key}}
     value: "{{this}}"
  {{/each}}
   - name: APP_NAME
     value: "fptilbake"
   - name: ABAC_ATTRIBUTT_APPLIKASJON
     value: "no.nav.abac.attributter.foreldrepenger"
   - name: ABAC_ATTRIBUTT_FAGSAK
     value: "no.nav.abac.attributter.foreldrepenger.fagsak"
   - name: ABAC_ATTRIBUTT_VENTEFRIST
     value: "no.nav.abac.attributter.foreldrepenger.fagsak.ventefrist"
   - name: ABAC_ATTRIBUTT_BATCH
     value: "no.nav.abac.attributter.foreldrepenger.batch"
   - name: ABAC_ATTRIBUTT_DRIFT
     value: "no.nav.abac.attributter.foreldrepenger.drift"
   - name: AUDITLOGGER_ENABLED
     value: "true"
   - name: AUDITLOGGER_VENDOR
     value: "fp"
   - name: AUDITLOGGER_PRODUCT
     value: "fptilbake"
   - name: APPDYNAMICS_CONTROLLER_HOST_NAME
     value: "appdynamics.adeo.no"
   - name: APPDYNAMICS_CONTROLLER_PORT
     value: "443"
   - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
     value: "true"
