kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: k9-tilbake
  namespace: {{namespace}}
  labels:
    team: k9saksbehandling
spec:
  image:  {{image}}
  port: 8080 # Required. The port number which is exposed by the container and should receive HTTP traffic.
  team: k9saksbehandling
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness: # HTTP endpoint that signals 200 OK when the application is running.
    path: /k9/tilbake/internal/health/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10     # How often (in seconds) to perform the probe. Default to 10 seconds
    failureThreshold: 27 # when a Pod starts and the probe fails,
    # nais will try failureThreshold times before giving up and restarting the Pod
    # Defaults to 3
  readiness: # HTTP endpoint that signals 200 OK when it is okay to start routing traffic to the application.
    path: /k9/tilbake/internal/health/isReady
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  prometheus: # Optional.
    enabled: true # if true the pod will be scraped for metrics by prometheus
    path: /k9/tilbake/internal/metrics/prometheus # Path to prometheus-metrics
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 80
  leaderElection: false
  istio: # Optional.
    enabled: false
  resources: # Optional. See: http://kubernetes.io/docs/user-guide/compute-resources/
    limits:
      cpu: "2000m"
      memory: "1400Mi"  # app will be killed if exceeding these limits
    requests: # App is guaranteed the requested resources and  will be scheduled on nodes with at least this amount of resources available
      cpu: "200m"
      memory: "1400Mi"
  logformat: accesslog # Optional. The format of the logs from the container if the logs should be handled differently than plain text or json
  logtransform: dns_loglevel # Optional. The transformation of the logs, if they should be handled differently than plain text or json
  webproxy: false # Optional. Expose web proxy configuration to the application using the HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables.
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/defaultDSconfig
        kvPath: {{oracleconfig}}
      - mountPath: /var/run/secrets/nais.io/defaultDS
        kvPath:  {{oraclek9tilbakesecret}}
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: {{k9tilbakeserviceuser}}
      - mountPath: /var/run/secrets/nais.io/ldap
        kvPath: {{ldapserviceuser}}
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/{{cluster}}/fss/k9-tilbake/{{namespace}}
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/{{environment}}
  sidecar: true # refresh token
  env:
  # miljø-spesifikke variable
  {{#each env}}
   - name: {{@key}}
     value: "{{this}}"
  {{/each}}
   - name: APP_NAME
     value: "k9-tilbake"
   - name: ABAC_ATTRIBUTT_APPLIKASJON
     value: "no.nav.abac.attributter.k9"
   - name: ABAC_ATTRIBUTT_FAGSAK
     value: "no.nav.abac.attributter.k9.fagsak"
   - name: ABAC_ATTRIBUTT_VENTEFRIST
     value: "no.nav.abac.attributter.k9.fagsak.ventefrist"
   - name: ABAC_ATTRIBUTT_BATCH
     value: "no.nav.abac.attributter.k9.batch"
   - name: AUDITLOGGER_ENABLED
     value: "true"
   - name: AUDITLOGGER_VENDOR
     value: "k9"
   - name: AUDITLOGGER_PRODUCT
     value: "k9-tilbake"
