apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: tilbakekreving-hendelse-los
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 1440  # 60 dager (24*60)
  acl:
    - team: k9saksbehandling
      application: k9-tilbake
      access: write
    - team: k9saksbehandling
      application: k9-los-api
      access: read
