package no.nav.foreldrepenger.tilbakekreving.web.server.jetty.abac.k9pdp.sifabacpdp.dto.resultat;

public enum IkkeTilgangÅrsak {
    HAR_IKKE_TILGANG_TIL_KODE6_PERSON,
    HAR_IKKE_TILGANG_TIL_KODE7_PERSON,
    HAR_IKKE_TILGANG_TIL_EGEN_ANSATT,
    HAR_IKKE_TILGANG_TIL_APPLIKASJONEN,
    ER_IKKE_VEILEDER_ELLER_SAKSBEHANDLER,
    ER_IKKE_SAKSBEHANDLER,
    ER_IKKE_BESLUTTER,
    ER_IKKE_OVERSTYRER,
    ER_IKKE_DRIFTER,
    ER_IKKE_UNGDSOMSPROGRAMVEILEDER,
    KAN_IKKE_BESLUTTE_EGEN_SAK,
    BEHANDLINGEN_FINNES_IKKE,
    BEHANDLINGEN_ER_LUKKET,
    FEIL_AKSJONSPUNKT_FOR_BESLUTTER,
    FEIL_AKSJONSPUNKT_FOR_SAKSBEHANDLING,
    TEKNISK_FEIL_PERSONER_OPPGITT_FOR_APPLIKASJONRESSURS,
    TEKNISK_FEIL_INGEN_PERSONER_OPPGITT_FOR_FAGSAKRESSURS,
    TEKNISK_FEIL_MANGLER_INFORMASJON_OM_UNGDOMSPROGRAMROLLE,
    TEKNISK_FEIL,
}
