ALTER SESSION SET CONTAINER=FREEPDB1;

DECLARE
    userexists INTEGER;
BEGIN
    SELECT count(*)
    INTO userexists
    FROM SYS.ALL_USERS
    WHERE USERNAME = 'FPTILBAKE';
    IF (userexists = 0)
    THEN
        EXECUTE IMMEDIATE ('CREATE USER FPTILBAKE IDENTIFIED BY fptilbake PROFILE DEFAULT ACCOUNT UNLOCK QUOTA UNLIMITED ON SYSTEM');
    END IF;
END;
/

GRANT
    CREATE SESSION,
    ALTER SESSION,
    CONNECT,
    RESOURCE,
    CREATE MATERIALIZED VIEW,
    CREATE JOB,
    CREATE TABLE,
    CREATE SYNONYM,
    CREATE VIEW,
    CREATE SEQUENCE,
    UNLIMITED TABLESPACE,
    SELECT ANY TABLE
    TO FPTILBAKE;

DECLARE
    userexists INTEGER;
BEGIN
    SELECT count(*)
    INTO userexists
    FROM SYS.ALL_USERS
    WHERE USERNAME = 'FPTILBAKE_UNIT';
    IF (userexists = 0)
    THEN
        EXECUTE IMMEDIATE ('CREATE USER FPTILBAKE_UNIT IDENTIFIED BY fptilbake_unit PROFILE DEFAULT ACCOUNT UNLOCK QUOTA UNLIMITED ON SYSTEM');
    END IF;
END;
/

GRANT
    CREATE SESSION,
    ALTER SESSION,
    CONNECT,
    RESOURCE,
    CREATE MATERIALIZED VIEW,
    CREATE JOB,
    CREATE TABLE,
    CREATE SYNONYM,
    CREATE VIEW,
    CREATE SEQUENCE,
    UNLIMITED TABLESPACE,
    SELECT ANY TABLE
TO FPTILBAKE_UNIT;
