delete from kodeliste_navn_i18n where kl_kodeverk = 'HENDELSE_UNDERTYPE' and kl_kode in ('SVP_IKKE_TAP', 'SVP_FEIL_ARBEIDSFORHOLD', 'SVP_FEIL_ARBEIDSKATEGORI');
delete from kodeliste_relasjon where kodeverk2='HENDELSE_UNDERTYPE' and kode2 in ('SVP_IKKE_TAP', 'SVP_FEIL_ARBEIDSFORHOLD', 'SVP_FEIL_ARBEIDSKATEGORI');
delete from kodeliste where kodeverk='HENDELSE_UNDERTYPE' and kode in ('SVP_IKKE_TAP', 'SVP_FEIL_ARBEIDSFORHOLD', 'SVP_FEIL_ARBEIDSKATEGORI');

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE) VALUES (seq_kodeliste.nextval,'HENDELSE_TYPE','OPPHØR',null,'Opphør');
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN) VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HENDELSE_TYPE','OPPHØR','NB','Opphør');

INSERT INTO KODELISTE_RELASJON (ID,KODEVERK1,KODE1,KODEVERK2,KODE2) VALUES (SEQ_KODELISTE_RELASJON.NEXTVAL,'FAGSAK_YTELSE','SVP','HENDELSE_TYPE','OPPHØR');

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,EKSTRA_DATA) VALUES (seq_kodeliste.nextval,'HENDELSE_UNDERTYPE','MOTTAKER_DØD',null,'Mottaker død', '1');
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN) VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HENDELSE_UNDERTYPE','MOTTAKER_DØD','NB','Mottaker død');
INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,EKSTRA_DATA) VALUES (seq_kodeliste.nextval,'HENDELSE_UNDERTYPE','MOTTAKER_IKKE_GRAVID',null,'Mottaker ikke lenger gravid', '2');
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN) VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HENDELSE_UNDERTYPE','MOTTAKER_IKKE_GRAVID','NB','Mottaker ikke lenger gravid');
INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,EKSTRA_DATA) VALUES (seq_kodeliste.nextval,'HENDELSE_UNDERTYPE','MANGLER_ARBEIDSFORHOLD',null,'Manglende arbeidsforhold', '1');
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN) VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HENDELSE_UNDERTYPE','MANGLER_ARBEIDSFORHOLD','NB','Manglende arbeidsforhold');

INSERT INTO KODELISTE_RELASJON (ID,KODEVERK1,KODE1,KODEVERK2,KODE2) VALUES (SEQ_KODELISTE_RELASJON.NEXTVAL,'HENDELSE_TYPE','OPPHØR','HENDELSE_UNDERTYPE','MOTTAKER_DØD');
INSERT INTO KODELISTE_RELASJON (ID,KODEVERK1,KODE1,KODEVERK2,KODE2) VALUES (SEQ_KODELISTE_RELASJON.NEXTVAL,'HENDELSE_TYPE','OPPHØR','HENDELSE_UNDERTYPE','MOTTAKER_IKKE_GRAVID');
INSERT INTO KODELISTE_RELASJON (ID,KODEVERK1,KODE1,KODEVERK2,KODE2) VALUES (SEQ_KODELISTE_RELASJON.NEXTVAL,'HENDELSE_TYPE','SVP_ARBEIDSFORHOLD_TYPE','HENDELSE_UNDERTYPE','MANGLER_ARBEIDSFORHOLD');
