ALTER TABLE VEDTAKSBREV_OPPSUMMERING ADD TEMP_OPPSUMMERING_FRITEKST CLOB;

UPDATE VEDTAKSBREV_OPPSUMMERING SET TEMP_OPPSUMMERING_FRITEKST=OPPSUMMERING_FRITEKST;

ALTER TABLE VEDTAKSBREV_OPPSUMMERING DROP COLUMN OPPSUMMERING_FRITEKST;

ALTER TABLE VEDTAKSBREV_OPPSUMMERING RENAME COLUMN TEMP_OPPSUMMERING_FRITEKST TO OPPSUMMERING_FRITEKST;

ALTER TABLE VEDTAKSBREV_OPPSUMMERING ADD BREV_TYPE VARCHAR2(100 CHAR);

COMMENT ON COLUMN VEDTAKSBREV_OPPSUMMERING.OPPSUMMERING_FRITEKST IS 'Fritekst fra saksbehandler til oppsummering av vedtaket';
COMMENT ON COLUMN VEDTAKSBREV_OPPSUMMERING.BREV_TYPE IS 'Vedtaksbrev type';

CREATE INDEX IDX_VEDTAKSBREV_OPPSUMMERING_1 ON VEDTAKSBREV_OPPSUMMERING (BREV_TYPE);

UPDATE VEDTAKSBREV_OPPSUMMERING SET BREV_TYPE='ORDINÆR';
