INSERT INTO BEHANDLING_STEG_TYPE (KODE,NAVN,BEHANDLING_STATUS_DEF,BESKRIVELSE)
VALUES ('INOPPSTEG','Innhent opplysninger','UTRED','Innhente opplysninger fra andre systemer.');

INSERT INTO VURDERINGSPUNKT_DEF (KODE,BEHANDLING_STEG,VURDERINGSPUNKT_TYPE,NAVN) VALUES ('INOPPSTEG.INN','INOPPSTEG','INN','Innhent opplysninger - Inngang');

INSERT INTO VURDERINGSPUNKT_DEF (KODE,BEHANDLING_STEG,VURDERINGSPUNKT_TYPE,NAVN) VALUES ('INOPPSTEG.UT','INOPPSTEG','UT','Innhent opplysninger - Utgang');

INSERT INTO AKSJONSPUNKT_DEF (KODE,NAVN,VURDERINGSPUNKT,BESKRIVELSE,TOTRINN_BEHANDLING_DEFAULT,AKSJONSPUNKT_TYPE,TILBAKEHOPP_VED_GJENOPPTAKELSE,LAG_UTEN_HISTORIKK,
SKJERMLENKE_TYPE) values ('5000','Innhent opplysning','INOPPSTEG.INN','Innhent opplysning','N','MANU','N','J', '-');

INSERT INTO BEHANDLING_TYPE_STEG_SEKV (ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR) VALUES
(SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval, 'BT-007', 'INOPPSTEG', 30);
