  DROP TABLE HISTORIKKINNSLAG;

  CREATE TABLE HISTORIKKINNSLAG(
  ID                          NUMBER(19,0) NOT NULL ENABLE,
  TEKST                       VARCHAR2(2000 CHAR),
  BEHANDLING_ID               NUMBER(19,0),
  HISTORIKK_AKTOER_ID         VARCHAR2(100 CHAR) NOT NULL ENABLE,
  HISTORIKKINNSLAG_TYPE       VARCHAR2(100 CHAR) NOT NULL ENABLE,
  OPPRETTET_AV                VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL ENABLE,
  OPPRETTET_TID               TIMESTAMP(3) DEFAULT systimestamp NOT NULL ENABLE,
  ENDRET_AV                   VARCHAR2(20 CHAR),
  ENDRET_TID                 TIMESTAMP (3),
  KL_HISTORIKK_AKTOER        VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('HISTORIKK_AKTOER') VIRTUAL VISIBLE  NOT NULL ENABLE,
  FAGSAK_ID                  NUMBER(19,0) NOT NULL ENABLE,
  BRUKER_KJOENN              VARCHAR2(100 CHAR) NOT NULL ENABLE,
  KL_BRUKER_KJOENN           VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('BRUKER_KJOENN') VIRTUAL VISIBLE  NOT NULL ENABLE,
  KL_HISTORIKKINNSLAG_TYPE   VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('HISTORIKKINNSLAG_TYPE') VIRTUAL VISIBLE  NOT NULL ENABLE
  );

  CREATE SEQUENCE SEQ_HISTORIKKINNSLAG MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

  COMMENT ON TABLE  HISTORIKKINNSLAG  IS 'Historikk over hendelser i saken';
  COMMENT ON COLUMN HISTORIKKINNSLAG.ID IS 'Primary Key';
  COMMENT ON COLUMN HISTORIKKINNSLAG.TEKST IS 'Tekst som beskriver hendelsen (som skal vises i historikkfanen)';
  COMMENT ON COLUMN HISTORIKKINNSLAG.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling';
  COMMENT ON COLUMN HISTORIKKINNSLAG.HISTORIKK_AKTOER_ID IS 'FK:HISTORIKK_AKTOER Fremmednøkkel til';
  COMMENT ON COLUMN HISTORIKKINNSLAG.HISTORIKKINNSLAG_TYPE IS 'Fremmednøkkel til beskrivelse av historikkinnslaget';
  COMMENT ON COLUMN HISTORIKKINNSLAG.KL_HISTORIKK_AKTOER IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
  COMMENT ON COLUMN HISTORIKKINNSLAG.FAGSAK_ID IS 'FK:FAGSAK Fremmednøkkel for kobling til fagsak';
  COMMENT ON COLUMN HISTORIKKINNSLAG.BRUKER_KJOENN IS 'FK:BRUKER_KJOENN Fremmednøkkel til kodeverkstabellen som viser mulige kjønn for bruker og viser til brukerens kjønn';
  COMMENT ON COLUMN HISTORIKKINNSLAG.KL_BRUKER_KJOENN IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
  COMMENT ON COLUMN HISTORIKKINNSLAG.KL_HISTORIKKINNSLAG_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';


  CREATE TABLE HISTORIKKINNSLAG_DEL(
    ID                  NUMBER(19,0) NOT NULL ENABLE,
    HISTORIKKINNSLAG_ID NUMBER(19,0) NOT NULL ENABLE,
    VERSJON             NUMBER(19,0) DEFAULT 0 NOT NULL ENABLE,
    OPPRETTET_AV        VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL ENABLE,
    OPPRETTET_TID       TIMESTAMP (3) DEFAULT systimestamp NOT NULL ENABLE,
    ENDRET_AV           VARCHAR2(20 CHAR),
    ENDRET_TID          TIMESTAMP (3)
    );

  CREATE SEQUENCE SEQ_HISTORIKKINNSLAG_DEL MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

  COMMENT ON TABLE  HISTORIKKINNSLAG_DEL  IS 'Et historikkinnslag kan ha en eller flere deler';
  COMMENT ON COLUMN HISTORIKKINNSLAG_DEL.ID IS 'Primærnøkkel';
  COMMENT ON COLUMN HISTORIKKINNSLAG_DEL.HISTORIKKINNSLAG_ID IS 'FK:HISTORIKKINNSLAG Fremmednøkkel til riktig innslag i historikktabellen';

   CREATE TABLE HISTORIKKINNSLAG_DOK_LINK(
    ID                  NUMBER(19,0) NOT NULL ENABLE,
    LINK_TEKST          VARCHAR2(100 CHAR) NOT NULL ENABLE,
    HISTORIKKINNSLAG_ID NUMBER(19,0) NOT NULL ENABLE,
    JOURNALPOST_ID      VARCHAR2(100 CHAR),
    DOKUMENT_ID         VARCHAR2(100 CHAR),
    OPPRETTET_AV        VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL ENABLE,
    OPPRETTET_TID       TIMESTAMP (3) DEFAULT systimestamp NOT NULL ENABLE,
    ENDRET_AV           VARCHAR2(20 CHAR),
    ENDRET_TID          TIMESTAMP (3)
    );

  CREATE SEQUENCE SEQ_HISTORIKKINNSLAG_DOK_LINK MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

  COMMENT ON TABLE HISTORIKKINNSLAG_DOK_LINK  IS 'Kobling fra historikkinnslag til aktuell dokumentasjon';

  COMMENT ON COLUMN HISTORIKKINNSLAG_DOK_LINK.ID IS 'Primary Key';
  COMMENT ON COLUMN HISTORIKKINNSLAG_DOK_LINK.LINK_TEKST IS 'Tekst som vises for link til dokumentet';
  COMMENT ON COLUMN HISTORIKKINNSLAG_DOK_LINK.HISTORIKKINNSLAG_ID IS 'FK:HISTORIKKINNSLAG Fremmednøkkel til riktig innslag i historikktabellen';
  COMMENT ON COLUMN HISTORIKKINNSLAG_DOK_LINK.JOURNALPOST_ID IS 'Journal post Id';
  COMMENT ON COLUMN HISTORIKKINNSLAG_DOK_LINK.DOKUMENT_ID IS 'Dokumnent Id';

  CREATE TABLE HISTORIKKINNSLAG_FELT(
  ID                          NUMBER(19,0) NOT NULL ENABLE,
  HISTORIKKINNSLAG_DEL_ID     NUMBER(19,0) NOT NULL ENABLE,
  HISTORIKKINNSLAG_FELT_TYPE  VARCHAR2(100 CHAR) NOT NULL ENABLE,
  NAVN                        VARCHAR2(100 CHAR),
  KL_NAVN                     VARCHAR2(100 CHAR),
  NAVN_VERDI                  VARCHAR2(4000 CHAR),
  FRA_VERDI                   VARCHAR2(4000 CHAR),
  TIL_VERDI                   VARCHAR2(4000 CHAR),
  SEKVENS_NR                  NUMBER(5,0),
  VERSJON                     NUMBER(19,0) DEFAULT 0 NOT NULL ENABLE,
  OPPRETTET_AV                VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL ENABLE,
  OPPRETTET_TID               TIMESTAMP (3) DEFAULT systimestamp NOT NULL ENABLE,
  ENDRET_AV                   VARCHAR2(20 CHAR),
  ENDRET_TID                  TIMESTAMP (3),
  FRA_VERDI_KODE              VARCHAR2(100 CHAR),
  TIL_VERDI_KODE              VARCHAR2(100 CHAR),
  KL_FRA_VERDI                VARCHAR2(100 CHAR),
  KL_TIL_VERDI                VARCHAR2(100 CHAR)
  );

  CREATE SEQUENCE SEQ_HISTORIKKINNSLAG_FELT MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

  COMMENT ON TABLE HISTORIKKINNSLAG_FELT IS 'En historikkinnslagdel har typisk mange felt';
  COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.ID IS 'Primærnøkkel';
  COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.HISTORIKKINNSLAG_DEL_ID IS 'FK:HISTORIKKINNSLAG_DEL';
  COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.HISTORIKKINNSLAG_FELT_TYPE IS 'Hva slags type informasjon som er representert';
  COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.NAVN IS 'Navn på felt. Gjelder for endrede verdier og opplysninger';
  COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.KL_NAVN IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
  COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.NAVN_VERDI IS 'Verdi som skal brukes som del av feltets navn';
  COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.FRA_VERDI IS 'Feltets gamle verdi. Kun string';
  COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.TIL_VERDI IS 'Feltets nye verdi. Kun string';
  COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.SEKVENS_NR IS 'Settes dersom historikkinnslagdelen har flere innslag med samme navn';
  COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.FRA_VERDI_KODE IS 'Feltets gamle verdi. Kun kodeverk';
  COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.TIL_VERDI_KODE IS 'Feltets nye verdi. Kun kodeverk';
  COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.KL_FRA_VERDI IS 'FK:KODELISTE Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
  COMMENT ON COLUMN HISTORIKKINNSLAG_FELT.KL_TIL_VERDI IS 'FK:KODELISTE Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';

  --------------------------------------------------------
  --  DDL for Index og Primary Key
  --------------------------------------------------------

  ALTER TABLE HISTORIKKINNSLAG  ADD CONSTRAINT PK_HISTORIKKINNSLAG PRIMARY KEY (ID) ENABLE;

  ALTER TABLE HISTORIKKINNSLAG_DEL  ADD CONSTRAINT PK_HISTORIKKINNSLAG_DEL PRIMARY KEY (ID) ENABLE;

  ALTER TABLE HISTORIKKINNSLAG_DOK_LINK  ADD CONSTRAINT PK_HISTORIKKINNSLAG_DOK_LINK PRIMARY KEY (ID) ENABLE;

  ALTER TABLE HISTORIKKINNSLAG_FELT  ADD CONSTRAINT PK_HISTORIKKINNSLAG_FELT PRIMARY KEY (ID) ENABLE;

  CREATE INDEX IDX_HISTORIKKINNSLAG_1 ON HISTORIKKINNSLAG (BEHANDLING_ID);

  CREATE INDEX IDX_HISTORIKKINNSLAG_2 ON HISTORIKKINNSLAG (BRUKER_KJOENN);

  CREATE INDEX IDX_HISTORIKKINNSLAG_3 ON HISTORIKKINNSLAG (HISTORIKKINNSLAG_TYPE);

  CREATE INDEX IDX_HISTORIKKINNSLAG_4 ON HISTORIKKINNSLAG (FAGSAK_ID);

  CREATE INDEX IDX_HISTORIKKINNSLAG_5 ON HISTORIKKINNSLAG (HISTORIKK_AKTOER_ID);

  CREATE INDEX IDX_HISTORIKKINNSLAG_DEL_1 ON HISTORIKKINNSLAG_DEL (HISTORIKKINNSLAG_ID);

  CREATE INDEX IDX_HISTINNSLAG_DOK_LINK_1 ON HISTORIKKINNSLAG_DOK_LINK (HISTORIKKINNSLAG_ID);

  CREATE INDEX IDX_HISTORIKKINNSLAG_FELT_1 ON HISTORIKKINNSLAG_FELT (HISTORIKKINNSLAG_DEL_ID);

  CREATE INDEX IDX_HISTORIKKINNSLAG_FELT_2 ON HISTORIKKINNSLAG_FELT (NAVN, KL_NAVN);

  CREATE INDEX IDX_HISTORIKKINNSLAG_FELT_3 ON HISTORIKKINNSLAG_FELT (TIL_VERDI_KODE, KL_TIL_VERDI);

  CREATE INDEX IDX_HISTORIKKINNSLAG_FELT_4 ON HISTORIKKINNSLAG_FELT (FRA_VERDI_KODE, KL_FRA_VERDI);

--------------------------------------------------------
--  Ref Constraints
--------------------------------------------------------

ALTER TABLE HISTORIKKINNSLAG ADD CONSTRAINT FK_HISTORIKKINNSLAG_1 FOREIGN KEY (BEHANDLING_ID)
REFERENCES BEHANDLING (ID) ENABLE;

ALTER TABLE HISTORIKKINNSLAG ADD CONSTRAINT FK_HISTORIKKINNSLAG_2 FOREIGN KEY (HISTORIKK_AKTOER_ID, KL_HISTORIKK_AKTOER)
REFERENCES KODELISTE (KODE, KODEVERK) ENABLE;

ALTER TABLE HISTORIKKINNSLAG ADD CONSTRAINT FK_HISTORIKKINNSLAG_3 FOREIGN KEY (FAGSAK_ID) REFERENCES FAGSAK (ID) ENABLE;

ALTER TABLE HISTORIKKINNSLAG ADD CONSTRAINT FK_HISTORIKKINNSLAG_4 FOREIGN KEY (BRUKER_KJOENN, KL_BRUKER_KJOENN)
REFERENCES KODELISTE (KODE, KODEVERK) ENABLE;

ALTER TABLE HISTORIKKINNSLAG ADD CONSTRAINT FK_HISTORIKKINNSLAG_5 FOREIGN KEY (HISTORIKKINNSLAG_TYPE, KL_HISTORIKKINNSLAG_TYPE)
REFERENCES KODELISTE (KODE, KODEVERK) ENABLE;

ALTER TABLE HISTORIKKINNSLAG_DEL ADD CONSTRAINT FK_HISTORIKKINNSLAG_DEL_1 FOREIGN KEY (HISTORIKKINNSLAG_ID)
REFERENCES HISTORIKKINNSLAG (ID) ENABLE;

ALTER TABLE HISTORIKKINNSLAG_DOK_LINK ADD CONSTRAINT FK_HISTORIKKINNSLAG_DOK_LINK_1 FOREIGN KEY (HISTORIKKINNSLAG_ID)
REFERENCES HISTORIKKINNSLAG (ID) ENABLE;

ALTER TABLE HISTORIKKINNSLAG_FELT ADD CONSTRAINT FK_HISTORIKKINNSLAG_FELT_1 FOREIGN KEY (HISTORIKKINNSLAG_DEL_ID)
REFERENCES HISTORIKKINNSLAG_DEL (ID) ENABLE;

ALTER TABLE HISTORIKKINNSLAG_FELT ADD CONSTRAINT FK_HISTORIKKINNSLAG_FELT_2 FOREIGN KEY (NAVN, KL_NAVN)
REFERENCES KODELISTE (KODE, KODEVERK) ENABLE;

ALTER TABLE HISTORIKKINNSLAG_FELT ADD CONSTRAINT FK_HISTORIKKINNSLAG_FELT_3 FOREIGN KEY (FRA_VERDI_KODE, KL_FRA_VERDI)
REFERENCES KODELISTE (KODE, KODEVERK) ENABLE;

ALTER TABLE HISTORIKKINNSLAG_FELT ADD CONSTRAINT FK_HISTORIKKINNSLAG_FELT_4 FOREIGN KEY (TIL_VERDI_KODE, KL_TIL_VERDI)
REFERENCES KODELISTE (KODE, KODEVERK) ENABLE;