--------------------------------------------------------
--  DDL for Table DOKUMENT_ADRESSE
--------------------------------------------------------

  CREATE TABLE DOKUMENT_ADRESSE (
    ID            NUMBER(19, 0),
    VERSJON       NUMBER(19, 0)     DEFAULT 0,
    MOTTAKER_NAVN VARCHAR2(40 CHAR),
    ADRESSELINJE1 VARCHAR2(40 CHAR),
    ADRESSELINJE2 VARCHAR2(40 CHAR),
    ADRESSELINJE3 VARCHAR2(40 CHAR),
    POSTNUMMER    VARCHAR2(20 CHAR),
    POSTSTED      VARCHAR2(40 CHAR),
    LAND          VARCHAR2(40 CHAR),
    OPPRETTET_AV  VARCHAR2(20 CHAR) DEFAULT 'VL',
    OPPRETTET_TID TIMESTAMP(3)      DEFAULT systimestamp,
    ENDRET_AV     VARCHAR2(20 CHAR),
    ENDRET_TID    TIMESTAMP(3)
  );

  CREATE SEQUENCE SEQ_DOKUMENT_ADRESSE MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

  CREATE UNIQUE INDEX PK_ADRESSE ON DOKUMENT_ADRESSE (ID);
  ALTER TABLE DOKUMENT_ADRESSE ADD CONSTRAINT PK_ADRESSE PRIMARY KEY (ID);
  ALTER TABLE DOKUMENT_ADRESSE MODIFY (OPPRETTET_TID NOT NULL ENABLE);
  ALTER TABLE DOKUMENT_ADRESSE MODIFY (OPPRETTET_AV NOT NULL ENABLE);
  ALTER TABLE DOKUMENT_ADRESSE MODIFY (VERSJON NOT NULL ENABLE);
  ALTER TABLE DOKUMENT_ADRESSE MODIFY (ID NOT NULL ENABLE);

  COMMENT ON COLUMN DOKUMENT_ADRESSE.ID IS 'Primary Key';
  COMMENT ON COLUMN DOKUMENT_ADRESSE.MOTTAKER_NAVN IS 'Navn på adressat.';
  COMMENT ON COLUMN DOKUMENT_ADRESSE.ADRESSELINJE1 IS 'Adresse, kan f.eks være c/o, postboksnummer, eller gateadresse';
  COMMENT ON COLUMN DOKUMENT_ADRESSE.ADRESSELINJE2 IS 'Adresse forts.';
  COMMENT ON COLUMN DOKUMENT_ADRESSE.ADRESSELINJE3 IS 'Adresse forts.';
  COMMENT ON COLUMN DOKUMENT_ADRESSE.POSTNUMMER IS 'Postnummer';
  COMMENT ON COLUMN DOKUMENT_ADRESSE.POSTSTED IS 'Poststed';
  COMMENT ON COLUMN DOKUMENT_ADRESSE.LAND IS 'Land';
  COMMENT ON TABLE DOKUMENT_ADRESSE  IS 'Inneholder adressen som et brev skal sendes til.';

--------------------------------------------------------
--  DDL for Table DOKUMENT_MAL_TYPE
--------------------------------------------------------

CREATE TABLE DOKUMENT_MAL_TYPE (
  KODE                        VARCHAR2(7 CHAR)                   NOT NULL,
  NAVN                        VARCHAR2(50 CHAR)                  NOT NULL,
  BESKRIVELSE                 VARCHAR2(4000 CHAR),
  OPPRETTET_AV                VARCHAR2(20 CHAR) DEFAULT 'VL'     NOT NULL,
  OPPRETTET_TID               TIMESTAMP(3) DEFAULT systimestamp  NOT NULL,
  ENDRET_AV                   VARCHAR2(20 CHAR),
  ENDRET_TID                  TIMESTAMP(3),
  GENERISK                    VARCHAR2(1 BYTE) DEFAULT 'J'       NOT NULL,
  DOKUMENT_MAL_RESTRIKSJON    VARCHAR2(100 CHAR) DEFAULT 'INGEN' NOT NULL,
  DOKSYS_KODE                 VARCHAR2(20 CHAR) DEFAULT 'INGEN'  NOT NULL,
  KL_DOKUMENT_MAL_RESTRIKSJON VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('DOKUMENT_MAL_RESTRIKSJON') VIRTUAL VISIBLE NOT NULL,
  CONSTRAINT PK_DOKUMENT_MAL_TYPE PRIMARY KEY (KODE),
  CONSTRAINT FK_DOKUMENT_MAL_TYPE_1 FOREIGN KEY (DOKUMENT_MAL_RESTRIKSJON, KL_DOKUMENT_MAL_RESTRIKSJON) REFERENCES KODELISTE (KODE, KODEVERK)
);

CREATE INDEX IDX_DOKUMENT_MAL_TYPE_1 ON DOKUMENT_MAL_TYPE (DOKUMENT_MAL_RESTRIKSJON);

ALTER TABLE DOKUMENT_MAL_TYPE ADD CONSTRAINT CHK_GENERISK CHECK (GENERISK in ('J', 'N')) ENABLE;

COMMENT ON COLUMN DOKUMENT_MAL_TYPE.KODE IS 'Kodeverk Primary Key';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.NAVN IS 'Lesbart navn på dokumentmaltype';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.GENERISK IS 'Kan dokumentmalen benyttes for informasjonsinnhenting i GUI (Y) eller ikke (N)';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.DOKUMENT_MAL_RESTRIKSJON IS 'Restriksjonskode som begrenser bruken av dokumentmalen, eller INGEN';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.DOKSYS_KODE IS 'Doksys kodeverkskode';
COMMENT ON COLUMN DOKUMENT_MAL_TYPE.KL_DOKUMENT_MAL_RESTRIKSJON IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON TABLE DOKUMENT_MAL_TYPE  IS 'Angir definerte dokumentmaler som brukes ved brevproduksjon';

--------------------------------------------------------
--  DDL for Table DOKUMENT_DATA
--------------------------------------------------------

  CREATE TABLE DOKUMENT_DATA (
    ID                NUMBER(19, 0)                     NOT NULL,
    BEHANDLING_ID     NUMBER(19, 0)                     NOT NULL,
    DOKUMENT_MAL_NAVN VARCHAR2(7 CHAR)                  NOT NULL,
    FORHAANDSVIST_TID TIMESTAMP(3),
    SENDT_TID         TIMESTAMP(3),
    VERSJON           NUMBER(19, 0) DEFAULT 0           NOT NULL,
    OPPRETTET_AV      VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
    OPPRETTET_TID     TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
    ENDRET_AV         VARCHAR2(20 CHAR),
    ENDRET_TID        TIMESTAMP(3),
    BESTILT_TID       TIMESTAMP(3),
    CONSTRAINT PK_DOKUMENT_DATA PRIMARY KEY (ID)
  );

  CREATE SEQUENCE SEQ_DOKUMENT_DATA MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

  CREATE INDEX IDX_DOKUMENT_DATA_6 ON DOKUMENT_DATA (DOKUMENT_MAL_NAVN);
  CREATE INDEX IDX_DOKUMENT_DATA_2 ON DOKUMENT_DATA (BEHANDLING_ID);

  ALTER TABLE DOKUMENT_DATA ADD CONSTRAINT FK_DOKUMENT_DATA_2 FOREIGN KEY (BEHANDLING_ID) REFERENCES BEHANDLING (ID) ENABLE;
  ALTER TABLE DOKUMENT_DATA ADD CONSTRAINT FK_DOKUMENT_DATA_3 FOREIGN KEY (DOKUMENT_MAL_NAVN) REFERENCES DOKUMENT_MAL_TYPE (KODE) ENABLE;

  COMMENT ON COLUMN DOKUMENT_DATA.ID IS 'Primary Key';
  COMMENT ON COLUMN DOKUMENT_DATA.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling';
  COMMENT ON COLUMN DOKUMENT_DATA.DOKUMENT_MAL_NAVN IS 'Navn på mal som brevet er lages fra.';
  COMMENT ON COLUMN DOKUMENT_DATA.FORHAANDSVIST_TID IS 'Tidspunkt for forhåndsvisning.';
  COMMENT ON COLUMN DOKUMENT_DATA.SENDT_TID IS 'Tidspunkt for oversendelse til brevløsningen.';
  COMMENT ON COLUMN DOKUMENT_DATA.BESTILT_TID IS 'Tidspunkt dokumentet ble bestilt';
  COMMENT ON TABLE DOKUMENT_DATA  IS 'Dokumentdata innholder informasjon om et brev som skal bestilles, eller som er bestilt.';

-- Tabell DOKUMENT_FELLES
--------------------------------------------------------
--  DDL for Table DOKUMENT_FELLES
--------------------------------------------------------

  CREATE TABLE DOKUMENT_FELLES (
    ID                       NUMBER(19, 0)                     NOT NULL,
    VERSJON                  NUMBER(19, 0) DEFAULT 0           NOT NULL,
    SPRAK_KODE               VARCHAR2(100 CHAR)                NOT NULL,
    SAKSNUMMER               NUMBER(19, 0)                     NOT NULL,
    SIGN_SAKSBEHANDLER_NAVN  VARCHAR2(80 CHAR),
    AUTOMATISK_BEHANDLET     VARCHAR2(1 CHAR)                  NOT NULL,
    SAKSPART_ID              VARCHAR2(20 CHAR)                 NOT NULL,
    SAKSPART_NAVN            VARCHAR2(80 CHAR)                 NOT NULL,
    SIGN_BESLUTTER_NAVN      VARCHAR2(80 CHAR),
    SIGN_BESLUTTER_GEO_ENHET VARCHAR2(80 CHAR),
    MOTTAKER_ID              VARCHAR2(20 CHAR)                 NOT NULL,
    MOTTAKER_NAVN            VARCHAR2(80 CHAR)                 NOT NULL,
    MOTTAKER_ADRESSE_ID      NUMBER(19, 0)                     NOT NULL,
    NAVN_AVSENDER_ENHET      VARCHAR2(80 CHAR)                 NOT NULL,
    NUMMER_AVSENDER_ENHET    VARCHAR2(80 CHAR),
    KONTAKT_TLF              VARCHAR2(80 CHAR)                 NOT NULL,
    RETUR_ADRESSE_ID         NUMBER(19, 0)                     NOT NULL,
    POST_ADRESSE_ID          NUMBER(19, 0)                     NOT NULL,
    DOKUMENT_DATO            TIMESTAMP(3)                      NOT NULL,
    OPPRETTET_AV             VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
    OPPRETTET_TID            TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
    ENDRET_AV                VARCHAR2(20 CHAR),
    ENDRET_TID               TIMESTAMP(3),
    KL_SPRAAK_KODE           VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('SPRAAK_KODE') VIRTUAL VISIBLE NOT NULL,
    DOKUMENT_DATA_ID         NUMBER(19, 0)                     NOT NULL,
    DOKUMENT_ID              VARCHAR2(20 CHAR),
    JOURNALPOST_ID           VARCHAR2(20 CHAR),
    SAKSPART_PERSON_STATUS   VARCHAR2(20 CHAR) DEFAULT 'ANNET' NOT NULL,
    CONSTRAINT PK_DOKUMENT_FELLES PRIMARY KEY (ID)
  );

  CREATE SEQUENCE SEQ_DOKUMENT_FELLES MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

  CREATE INDEX IDX_DOKUMENT_FELLES_6 ON DOKUMENT_FELLES (MOTTAKER_ADRESSE_ID);
  CREATE INDEX IDX_DOKUMENT_FELLES_7 ON DOKUMENT_FELLES (RETUR_ADRESSE_ID);
  CREATE INDEX IDX_DOKUMENT_FELLES_8 ON DOKUMENT_FELLES (POST_ADRESSE_ID);
  CREATE INDEX IDX_DOKUMENT_FELLES_9 ON DOKUMENT_FELLES (DOKUMENT_DATA_ID);
  CREATE INDEX IDX_DOKUMENT_FELLES_10 ON DOKUMENT_FELLES (SPRAK_KODE);

  ALTER TABLE DOKUMENT_FELLES ADD CONSTRAINT CHK_AUTOMATISK_BEHANDLET CHECK (AUTOMATISK_BEHANDLET in ('J', 'N')) ENABLE;

  ALTER TABLE DOKUMENT_FELLES ADD CONSTRAINT FK_DOKUMENT_FELLES_1 FOREIGN KEY (MOTTAKER_ADRESSE_ID) REFERENCES DOKUMENT_ADRESSE (ID) ENABLE;
  ALTER TABLE DOKUMENT_FELLES ADD CONSTRAINT FK_DOKUMENT_FELLES_2 FOREIGN KEY (RETUR_ADRESSE_ID) REFERENCES DOKUMENT_ADRESSE (ID) ENABLE;
  ALTER TABLE DOKUMENT_FELLES ADD CONSTRAINT FK_DOKUMENT_FELLES_3 FOREIGN KEY (POST_ADRESSE_ID) REFERENCES DOKUMENT_ADRESSE (ID) ENABLE;
  ALTER TABLE DOKUMENT_FELLES ADD CONSTRAINT FK_DOKUMENT_FELLES_4 FOREIGN KEY (DOKUMENT_DATA_ID) REFERENCES DOKUMENT_DATA (ID) ENABLE;
  ALTER TABLE DOKUMENT_FELLES ADD CONSTRAINT FK_DOKUMENT_FELLES_80 FOREIGN KEY (SPRAK_KODE, KL_SPRAAK_KODE) REFERENCES KODELISTE (KODE, KODEVERK) ENABLE;

  COMMENT ON COLUMN DOKUMENT_FELLES.ID IS 'Primary Key';
  COMMENT ON COLUMN DOKUMENT_FELLES.SPRAK_KODE IS 'FK:SPRAAK_KODE Brukers foretrukne språk som skal brukes i kommunikasjon med bruker';
  COMMENT ON COLUMN DOKUMENT_FELLES.SAKSNUMMER IS 'Saksnummer i GSAK';
  COMMENT ON COLUMN DOKUMENT_FELLES.SIGN_SAKSBEHANDLER_NAVN IS 'Signerende saksbehandlers navn';
  COMMENT ON COLUMN DOKUMENT_FELLES.AUTOMATISK_BEHANDLET IS 'Er saken blitt automatisk behandlet?';
  COMMENT ON COLUMN DOKUMENT_FELLES.SAKSPART_ID IS 'Fødselsnummer eller D-nummer til bruker saken gjelder';
  COMMENT ON COLUMN DOKUMENT_FELLES.SAKSPART_NAVN IS 'Navn på bruker saken gjelder';
  COMMENT ON COLUMN DOKUMENT_FELLES.SIGN_BESLUTTER_NAVN IS 'Signerende beslutters navn';
  COMMENT ON COLUMN DOKUMENT_FELLES.SIGN_BESLUTTER_GEO_ENHET IS 'Navn på signerende beslutters geografiske enhet';
  COMMENT ON COLUMN DOKUMENT_FELLES.MOTTAKER_ID IS 'Fødselsnummer eller D-nummer til dokumentmottaker';
  COMMENT ON COLUMN DOKUMENT_FELLES.MOTTAKER_NAVN IS 'Navn på adressat';
  COMMENT ON COLUMN DOKUMENT_FELLES.MOTTAKER_ADRESSE_ID IS 'FK:ADRESSE Fremmednøkkel som skal brukes av brevrutinen for å gjøre oppslag på mottakers adresse';
  COMMENT ON COLUMN DOKUMENT_FELLES.NAVN_AVSENDER_ENHET IS 'Navn på NAV-enhet som har sendt dokumentet';
  COMMENT ON COLUMN DOKUMENT_FELLES.NUMMER_AVSENDER_ENHET IS 'ID til NAV-enhet som har sendt dokumentet';
  COMMENT ON COLUMN DOKUMENT_FELLES.KONTAKT_TLF IS 'Dokumentmottakers kontaktnummer';
  COMMENT ON COLUMN DOKUMENT_FELLES.RETUR_ADRESSE_ID IS 'FK:ADRESSE Fremmednøkkel som skal brukes av brevrutinen for å gjøre oppslag på returadresse';
  COMMENT ON COLUMN DOKUMENT_FELLES.POST_ADRESSE_ID IS 'FK:ADRESSE Fremmednøkkel som skal brukes av brevrutinen for å gjøre oppslag på postadresse';
  COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_DATO IS 'Dato dokumentet er produsert';
  COMMENT ON COLUMN DOKUMENT_FELLES.KL_SPRAAK_KODE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
  COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_DATA_ID IS 'FK:DOKUMENT_DATA Fremmednøkkel til tabellen som Inneholder informasjon om hvilken dokumentmal som er bestillt og når brevet er bestillt';
  COMMENT ON COLUMN DOKUMENT_FELLES.DOKUMENT_ID IS 'Dokumentets Dokument ID i JOARK';
  COMMENT ON COLUMN DOKUMENT_FELLES.JOURNALPOST_ID IS 'Journalpostens ID i JOARK';
  COMMENT ON COLUMN DOKUMENT_FELLES.SAKSPART_PERSON_STATUS IS 'Gjeldende personstatus fra TPS når dokumentet produseres';
  COMMENT ON TABLE DOKUMENT_FELLES  IS 'Generell informasjon tilhørende en brevutsendelse';

--------------------------------------------------------
--  DDL for Table DOKUMENT_TYPE_DATA
--------------------------------------------------------

  CREATE TABLE DOKUMENT_TYPE_DATA (
    ID                 NUMBER(19, 0)                     NOT NULL,
    VERSJON            NUMBER(19, 0) DEFAULT 0           NOT NULL,
    DOKSYS_ID          VARCHAR2(40 CHAR)                 NOT NULL,
    VERDI              VARCHAR2(4000 CHAR)               NOT NULL,
    DOKUMENT_FELLES_ID NUMBER(19, 0)                     NOT NULL,
    OPPRETTET_AV       VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
    OPPRETTET_TID      TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
    ENDRET_AV          VARCHAR2(20 CHAR),
    ENDRET_TID         TIMESTAMP(3),
    STRUKTURERT_VERDI  CLOB,
    CONSTRAINT PK_DOKUMENT_TYPE_DATA PRIMARY KEY (ID)
  );

  CREATE SEQUENCE SEQ_DOKUMENT_TYPE_DATA MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;
  CREATE INDEX IDX_DOKUMENT_TYPE_DATA_6 ON DOKUMENT_TYPE_DATA (DOKUMENT_FELLES_ID);

  ALTER TABLE DOKUMENT_TYPE_DATA ADD CONSTRAINT FK_DOKUMENT_TYPE_DATA_1 FOREIGN KEY (DOKUMENT_FELLES_ID) REFERENCES DOKUMENT_FELLES (ID) ENABLE;

  COMMENT ON COLUMN DOKUMENT_TYPE_DATA.ID IS 'Primary Key';
  COMMENT ON COLUMN DOKUMENT_TYPE_DATA.DOKSYS_ID IS 'MISSING COLUMN COMMENT';
  COMMENT ON COLUMN DOKUMENT_TYPE_DATA.VERDI IS 'Verdi';
  COMMENT ON COLUMN DOKUMENT_TYPE_DATA.DOKUMENT_FELLES_ID IS 'FK:DOKUMENT_FELLES';
  COMMENT ON COLUMN DOKUMENT_TYPE_DATA.STRUKTURERT_VERDI IS 'Strukturert felt brukt i innvilgelsesbrevet og redigerbart brev';
  COMMENT ON TABLE DOKUMENT_TYPE_DATA  IS 'Variabel informasjon (flettefelter) tilhørende en brevutsendelse';
