DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='DOKUMENT_MAL_RESTRIKSJON';
DELETE FROM KODELISTE WHERE KODEVERK='DOKUMENT_MAL_RESTRIKSJON';
DELETE FROM KODEVERK WHERE KODE='DOKUMENT_MAL_RESTRIKSJON';

INSERT INTO KODEVERK (KODE,KODEVERK_EIER,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,SAMMENSATT)
VALUES ('DOKUMENT_MAL_TYPE','VL','N','N','Dokument Mal type','Kodeverk over forskjellige maltype av dokument','VL',to_timestamp(sysdate,'DD.MM.RRRR'),null,null,'N');

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'DOKUMENT_MAL_TYPE','INNHEN',null,
'Innhent dokumentasjon',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'DOKUMENT_MAL_TYPE','INNHEN','NB','Innhent dokumentasjon','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'DOKUMENT_MAL_TYPE','VARS',null,
'Varsel om tilbakekreving dokumentasjon',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'DOKUMENT_MAL_TYPE','VARS','NB','Varsel om tilbakekreving','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'DOKUMENT_MAL_TYPE','KORRIGVARS',null,
'Korrigert Varsel om tilbakekreving dokumentasjon',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'DOKUMENT_MAL_TYPE','KORRIGVARS','NB','Korrigert varsel om tilbakebetaling','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'DOKUMENT_MAL_TYPE','FRITKS',null,
'Fritekstbrev',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'DOKUMENT_MAL_TYPE','FRITKS','NB','Fritekstbrev','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

