
INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE, EKSTRA_DATA)
VALUES (seq_kodeliste.nextval,'HENDELSE_UNDERTYPE','KVO_SAMTIDIG_UTTAK',null,'Samtidig uttak av kvoter', 3);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HENDELSE_UNDERTYPE','KVO_SAMTIDIG_UTTAK','NB','Samtidig uttak');

INSERT INTO KODELISTE_RELASJON (ID,KODEVERK1,KODE1,KODEVERK2,KODE2)
VALUES (SEQ_KODELISTE_RELASJON. NEXTVAL,'HENDELSE_TYPE','UTTAK_KVOTENE_TYPE','HENDELSE_UNDERTYPE','KVO_SAMTIDIG_UTTAK');
