INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (seq_kodeliste.nextval, 'TILBAKEKR_VIDERE_BEH','TILBAKEKR_OPPRETT', 'Gjennomfør tilbakekreving.', to_date('2020-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'TILBAKEKR_VIDERE_BEH','TILBAKEKR_OPPRETT','NB','Feilutbetaling med tilbakekreving','VL',to_date('01.01.2020','DD.MM.RRRR'),null,null);
