CREATE TABLE GR_TBK_GRUNNLAG(
  ID                        NUMBER(19, 0)               NOT NULL ,
  GRUNNLAG_OKONOMI_ID       NUMBER(19, 0)               NOT NULL ,
  BEHANDLING_ID             NUMBER(19, 0)               NOT NULL ,
  AKTIV                     VARCHAR2(1) DEFAULT 'J'     NOT NULL ,
  OPPRETTET_AV  VARCHAR2(200 CHAR) DEFAULT 'VL'         NOT NULL ,
  OPPRETTET_TID TIMESTAMP(3) DEFAULT systimestamp       NOT NULL ,
  ENDRET_AV     VARCHAR2(20 CHAR),
  ENDRET_TID    TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_GR_TBK_GRUNNLAG MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE  GR_TBK_GRUNNLAG IS 'Aggregate tabell for å lagre grunnlag';
COMMENT ON COLUMN GR_TBK_GRUNNLAG.ID IS 'Primary Key';
COMMENT ON COLUMN GR_TBK_GRUNNLAG.GRUNNLAG_OKONOMI_ID IS 'FK:TBK_GRUNNLAG.Angir grunnlag kommer fra okonomi';
COMMENT ON COLUMN GR_TBK_GRUNNLAG.BEHANDLING_ID IS 'FK: BEHANDLING fremmednøkkel for tilknyttet behandling';
COMMENT ON COLUMN GR_TBK_GRUNNLAG.AKTIV IS 'Angir status av grunnlag';

DROP SEQUENCE SEQ_GRUNNLAG_OPPDATERT;

CREATE SEQUENCE SEQ_TBK_GRUNNLAG MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

ALTER TABLE GRUNNLAG_OPPDATERT RENAME TO TBK_GRUNNLAG;

ALTER TABLE TBK_GRUNNLAG DROP CONSTRAINT FK_GRUNNLAG_OPPDATERT_1;

ALTER TABLE TBK_GRUNNLAG RENAME CONSTRAINT PK_GRUNNLAG_OPPDATERT TO PK_TBK_GRUNNLAG;

ALTER TABLE TBK_GRUNNLAG DROP COLUMN BEHANDLING_ID;

ALTER TABLE TBK_GRUNNLAG DROP COLUMN AKTIV;

DROP INDEX IDX_UTBETALING_PERIODE_1;

ALTER TABLE UTBETALING_PERIODE RENAME COLUMN GRUNNLAG_OPPDATERT_ID TO GRUNNLAG_ID;

--------------------------------------------------------
--  DDL for Index og Primary Key
--------------------------------------------------------

ALTER TABLE GR_TBK_GRUNNLAG ADD CONSTRAINT PK_GR_TBK_GRUNNLAG PRIMARY KEY ("ID") ENABLE;

CREATE INDEX IDX_GR_TBK_GRUNNLAG_1 ON GR_TBK_GRUNNLAG ("GRUNNLAG_OKONOMI_ID");

CREATE INDEX IDX_GR_TBK_GRUNNLAG_3 ON GR_TBK_GRUNNLAG ("BEHANDLING_ID");

CREATE INDEX IDX_UTBETALING_PERIODE_1 ON UTBETALING_PERIODE ("GRUNNLAG_ID");

--------------------------------------------------------
--  Ref Constraints for Table GR_TBK_GRUNNLAG
--------------------------------------------------------
ALTER TABLE GR_TBK_GRUNNLAG
ADD CONSTRAINT FK_GR_TBK_GRUNNLAG_1 FOREIGN KEY ("GRUNNLAG_OKONOMI_ID")
REFERENCES TBK_GRUNNLAG ("ID") ENABLE;

ALTER TABLE GR_TBK_GRUNNLAG
ADD CONSTRAINT FK_GR_TBK_GRUNNLAG_3 FOREIGN KEY ("BEHANDLING_ID")
REFERENCES BEHANDLING ("ID") ENABLE;