CREATE TABLE VEDTAK_XML_OS
(
  ID NUMBER(19, 0),
  BEHANDLING_ID NUMBER(19, 0) NOT NULL,
  VEDTAK_XML CLOB NOT NULL,
  KVITTERING_XML CLOB NULL,
  OPPRETTET_AV VARCHAR2(200 CHAR) DEFAULT 'VL',
  OPPRETTET_TID TIMESTAMP(3) DEFAULT SYSTIMESTAMP,
  ENDRET_AV VARCHAR2(200 CHAR),
  ENDRET_TID TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_VEDTAK_XML_OS MINVALUE 1 START WITH 100000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE VEDTAK_XML_OS IS 'Tabell som tar vare på XML sendt til OS for iverksettelse, brukes for feilsøking';
COMMENT ON COLUMN VEDTAK_XML_OS.ID IS 'Primary key';
COMMENT ON COLUMN VEDTAK_XML_OS.BEHANDLING_ID IS 'Behandlingen det gjelder';
COMMENT ON COLUMN VEDTAK_XML_OS.VEDTAK_XML IS 'XML sendt til OS for iverksettelse';
COMMENT ON COLUMN VEDTAK_XML_OS.KVITTERING_XML IS 'Respons fra OS (ikke tatt i bruk enda)';

ALTER TABLE VEDTAK_XML_OS ADD CONSTRAINT PK_VEDTAK_XML_OS PRIMARY KEY (ID) ENABLE;
ALTER TABLE VEDTAK_XML_OS ADD CONSTRAINT FK_VEDTAK_XML_OS_1 FOREIGN KEY (BEHANDLING_ID) REFERENCES BEHANDLING (ID);

create index IDX_VEDTAK_XML_OS_1 on VEDTAK_XML_OS(BEHANDLING_ID);
