ALTER TABLE VEDTAKSBREV_OPPSUMMERING ADD FRITEKST CLOB;
COMMENT ON COLUMN VEDTAKSBREV_OPPSUMMERING.FRITEKST IS 'Fritekst fra saksbehandler til oppsummering av vedtaket';

UPDATE VEDTAKSBREV_OPPSUMMERING SET FRITEKST=OPPSUMMERING_FRITEKST where OPPSUMMERING_FRITEKST is not null;
