INSERT INTO BREV_SPORING(ID, BEHANDLING_ID, JOURNALPOST_ID, DOKUMENT_ID,BREV_TYPE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
SELECT SEQ_BREV_SPORING.NEXTVAL,BEHANDLING_ID, JOURNALPOST_ID, DOKUMENT_ID,'VARSEL', OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID FROM VARSELBREV_SPORING;

INSERT INTO BREV_SPORING(ID, BEHANDLING_ID, JOURNALPOST_ID, DOKUMENT_ID,BREV_TYPE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
SELECT SEQ_BREV_SPORING.NEXTVAL,BEHANDLING_ID, JOURNALPOST_ID, DOKUMENT_ID,'VEDTAK',OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID FROM VEDTAKSBREV_SPORING;
