--------------------------------------------------------
--  DDL for Table LAGRET_VEDTAK
--------------------------------------------------------

CREATE TABLE LAGRET_VEDTAK (
  ID NUMBER(19,0) NOT NULL,
  FAGSAK_ID             NUMBER(19, 0)                     NOT NULL,
  BEHANDLING_ID         NUMBER(19, 0)                     NOT NULL,
  XML_CLOB              CLOB                              NOT NULL,
  LAGRET_VEDTAK_TYPE    VARCHAR2(100 CHAR)                NOT NULL,
  VERSJON               NUMBER(19, 0) DEFAULT 0           NOT NULL,
  OPPRETTET_AV          VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
  OPPRETTET_TID         TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  ENDRET_AV             VARCHAR2(20 CHAR),
  ENDRET_TID            TIMESTAMP(3),
  KL_LAGRET_VEDTAK_TYPE VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('LAGRET_VEDTAK_TYPE') VIRTUAL VISIBLE,
  CONSTRAINT PK_LAGRET_VEDTAK PRIMARY KEY (ID),
  CONSTRAINT FK_LAGRET_VEDTAK_1 FOREIGN KEY (LAGRET_VEDTAK_TYPE, KL_LAGRET_VEDTAK_TYPE) REFERENCES KODELISTE (KODE, KODEVERK)
);

CREATE SEQUENCE SEQ_LAGRET_VEDTAK MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_LAGRET_VEDTAK_1 ON LAGRET_VEDTAK (LAGRET_VEDTAK_TYPE);

COMMENT ON COLUMN LAGRET_VEDTAK.ID IS 'Primary Key';
COMMENT ON COLUMN LAGRET_VEDTAK.FAGSAK_ID IS 'FK:FAGSAK Fremmednøkkel for kobling til fagsak';
COMMENT ON COLUMN LAGRET_VEDTAK.BEHANDLING_ID IS 'FK:BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN LAGRET_VEDTAK.XML_CLOB IS 'Vedtak XML.';
COMMENT ON COLUMN LAGRET_VEDTAK.LAGRET_VEDTAK_TYPE IS 'Fødsel eller adopsjon.';
COMMENT ON COLUMN LAGRET_VEDTAK.KL_LAGRET_VEDTAK_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON TABLE LAGRET_VEDTAK  IS 'Vedtak som er lagret på xml-form i vedtakslageret';
