DROP TABLE FEILUTBETALING_AARSAK_DEF;

--fjerne gamle underÅrsaker
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='UTSETTELSE_ARBEID';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='UTSETTELSE_SYKDOM';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='UTSETTELSE_INNLEGGELSE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='MEDLEMSKAP_VILKAAR';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='ENDRING_UTTAK_KVOTE_TYPE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='STONAD_PERIODE_TYPE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='OPPTJENING';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='MORS_AKTIVITET_TYPE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='OPPHOR';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='UTBETALING_SYSTEM_FEIL';

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='UTSETTELSE_ARBEID';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='UTSETTELSE_SYKDOM';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='UTSETTELSE_INNLEGGELSE';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='MEDLEMSKAP_VILKAAR';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='ENDRING_UTTAK_KVOTE_TYPE';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='STONAD_PERIODE_TYPE';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='OPPTJENING';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='MORS_AKTIVITET_TYPE';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='OPPHOR';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK2='UTBETALING_SYSTEM_FEIL';

DELETE FROM KODELISTE WHERE KODEVERK='UTSETTELSE_ARBEID';
DELETE FROM KODELISTE WHERE KODEVERK='UTSETTELSE_SYKDOM';
DELETE FROM KODELISTE WHERE KODEVERK='UTSETTELSE_INNLEGGELSE';
DELETE FROM KODELISTE WHERE KODEVERK='MEDLEMSKAP_VILKAAR';
DELETE FROM KODELISTE WHERE KODEVERK='ENDRING_UTTAK_KVOTE_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK='STONAD_PERIODE_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK='OPPTJENING';
DELETE FROM KODELISTE WHERE KODEVERK='MORS_AKTIVITET_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK='OPPHOR';
DELETE FROM KODELISTE WHERE KODEVERK='UTBETALING_SYSTEM_FEIL';

DELETE FROM KODEVERK WHERE KODE='UTSETTELSE_ARBEID';
DELETE FROM KODEVERK WHERE KODE='UTSETTELSE_SYKDOM';
DELETE FROM KODEVERK WHERE KODE='UTSETTELSE_INNLEGGELSE';
DELETE FROM KODEVERK WHERE KODE='MEDLEMSKAP_VILKAAR';
DELETE FROM KODEVERK WHERE KODE='ENDRING_UTTAK_KVOTE_TYPE';
DELETE FROM KODEVERK WHERE KODE='STONAD_PERIODE_TYPE';
DELETE FROM KODEVERK WHERE KODE='OPPTJENING';
DELETE FROM KODEVERK WHERE KODE='MORS_AKTIVITET_TYPE';
DELETE FROM KODEVERK WHERE KODE='OPPHOR';
DELETE FROM KODEVERK WHERE KODE='UTBETALING_SYSTEM_FEIL';

--fjerne gamle årsaker
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='UTSETTELSE_AARSAK_TYPE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='MEDLEMSKAP_VILKAARET_TYPE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='UTTAK_KVOTE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='BEREGNINGSGRUNNLAG_TILSTAND';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='STONAD_PERIODE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='OPPTJENING_TYPE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='MORS_AKTIVITET_KRAV';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='OMSORG_TYPE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='FORELDES_UTTAK';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='BARN_ALDER';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='OPPHOR_AARSAK_TYPE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='RETT_TYPE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='UTBETALING_SYSTEM_FEIL_TYPE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='GRADERING_AARSAK_TYPE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='ANNET_AARSAK_TYPE';

DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='UTSETTELSE_AARSAK_TYPE';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='MEDLEMSKAP_VILKAARET_TYPE';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='UTTAK_KVOTE';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='BEREGNINGSGRUNNLAG_TILSTAND';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='STONAD_PERIODE';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='OPPTJENING_TYPE';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='MORS_AKTIVITET_KRAV';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='OMSORG_TYPE';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='FORELDES_UTTAK';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='BARN_ALDER';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='OPPHOR_AARSAK_TYPE';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='RETT_TYPE';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='UTBETALING_SYSTEM_FEIL_TYPE';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='GRADERING_AARSAK_TYPE';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='ANNET_AARSAK_TYPE';

DELETE FROM KODELISTE WHERE KODEVERK='UTSETTELSE_AARSAK_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK='MEDLEMSKAP_VILKAARET_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK='UTTAK_KVOTE';
DELETE FROM KODELISTE WHERE KODEVERK='BEREGNINGSGRUNNLAG_TILSTAND';
DELETE FROM KODELISTE WHERE KODEVERK='STONAD_PERIODE';
DELETE FROM KODELISTE WHERE KODEVERK='OPPTJENING_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK='MORS_AKTIVITET_KRAV';
DELETE FROM KODELISTE WHERE KODEVERK='OMSORG_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK='FORELDES_UTTAK';
DELETE FROM KODELISTE WHERE KODEVERK='BARN_ALDER';
DELETE FROM KODELISTE WHERE KODEVERK='OPPHOR_AARSAK_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK='RETT_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK='UTBETALING_SYSTEM_FEIL_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK='GRADERING_AARSAK_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK='ANNET_AARSAK_TYPE';

DELETE FROM KODEVERK WHERE KODE='UTSETTELSE_AARSAK_TYPE';
DELETE FROM KODEVERK WHERE KODE='MEDLEMSKAP_VILKAARET_TYPE';
DELETE FROM KODEVERK WHERE KODE='UTTAK_KVOTE';
DELETE FROM KODEVERK WHERE KODE='BEREGNINGSGRUNNLAG_TILSTAND';
DELETE FROM KODEVERK WHERE KODE='STONAD_PERIODE';
DELETE FROM KODEVERK WHERE KODE='OPPTJENING_TYPE';
DELETE FROM KODEVERK WHERE KODE='MORS_AKTIVITET_KRAV';
DELETE FROM KODEVERK WHERE KODE='OMSORG_TYPE';
DELETE FROM KODEVERK WHERE KODE='FORELDES_UTTAK';
DELETE FROM KODEVERK WHERE KODE='BARN_ALDER';
DELETE FROM KODEVERK WHERE KODE='OPPHOR_AARSAK_TYPE';
DELETE FROM KODEVERK WHERE KODE='RETT_TYPE';
DELETE FROM KODEVERK WHERE KODE='UTBETALING_SYSTEM_FEIL_TYPE';
DELETE FROM KODEVERK WHERE KODE='GRADERING_AARSAK_TYPE';
DELETE FROM KODEVERK WHERE KODE='ANNET_AARSAK_TYPE';

--ubrukt kodeliste
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='MEDLEMSKAP_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK='MEDLEMSKAP_TYPE';
DELETE FROM KODEVERK WHERE KODE='MEDLEMSKAP_TYPE';

UPDATE KODELISTE_RELASJON SET ID=SEQ_KODELISTE_RELASJON.NEXTVAL WHERE KODEVERK1='REGION';
