Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) values (seq_kodeliste.nextval,'BEHANDLING_RESULTAT_TYPE','FASTSATT',null,'Resultatet er fastsatt, se BEHANDLING_VEDTAK for detaljer',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));
Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) values (seq_kodeliste.nextval,'BEHANDLING_RESULTAT_TYPE','ENDRET',null,'Resultatet er endret i revurderingen, se BEHANDLING_VEDTAK for detaljer',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_RESULTAT_TYPE','FASTSATT','NB','Resultatet er fastsatt','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_RESULTAT_TYPE','ENDRET','NB','Resultatet er endret i revurderingen','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

UPDATE BEHANDLING_RESULTAT SET BEHANDLING_RESULTAT_TYPE ='FASTSATT' WHERE BEHANDLING_RESULTAT_TYPE IN ('INNVILGET', 'AVSLÅTT');

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK = 'BEHANDLING_RESULTAT_TYPE' AND KL_KODE NOT IN ('IKKE_FASTSATT','FASTSATT','HENLAGT_FEILOPPRETTET','HENLAGT_KRAVGRUNNLAG_NULLSTILT','HENLAGT_TEKNISK_VEDLIKEHOLD','ENDRET','INGEN_ENDRING');
DELETE FROM KODELISTE WHERE KODEVERK = 'BEHANDLING_RESULTAT_TYPE' AND KODE NOT IN ('IKKE_FASTSATT','FASTSATT','HENLAGT_FEILOPPRETTET','HENLAGT_KRAVGRUNNLAG_NULLSTILT','HENLAGT_TEKNISK_VEDLIKEHOLD','ENDRET','INGEN_ENDRING');
