DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='FAGSAK_YTELSE' and KODE1='FP' and KODEVERK2='HENDELSE_TYPE' and KODE2='OKONOMI_FEIL';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='FAGSAK_YTELSE' and KODE1='SVP' and KODEVERK2='HENDELSE_TYPE' and KODE2='OKONOMI_FEIL';
