CREATE TABLE DOKUMENT_MAL_TYPE 
   (KODE VARCHAR2(10 CHAR) NOT NULL ENABLE,
	NAVN VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	BESKRIVELSE VARCHAR2(4000 CHAR), 
	OPPRETTET_AV VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL ENABLE, 
	OPPRETTET_TID TIMESTAMP (3) DEFAULT systimestamp NOT NULL ENABLE, 
	ENDRET_AV VARCHAR2(20 CHAR), 
	ENDRET_TID TIMESTAMP (3), 
	GENERISK VARCHAR2(1 BYTE) NOT NULL ENABLE,
	DOKUMENT_MAL_RESTRIKSJON VARCHAR2(100 CHAR) NOT NULL ENABLE,
	DOKSYS_KODE VARCHAR2(20 CHAR) NOT NULL ENABLE,
	KL_DOKUMENT_MAL_RESTRIKSJON VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('DOKUMENT_MAL_RESTRIKSJON') VIRTUAL NOT NULL ENABLE,
	 CONSTRAINT PK_DOKUMENT_MAL_TYPE PRIMARY KEY (KODE),
	 CONSTRAINT CHK_GENERISK CHECK (GENERISK in ('J', 'N')) ENABLE, 
	 CONSTRAINT FK_DOKUMENT_MAL_TYPE_80 FOREIGN KEY (DOKUMENT_MAL_RESTRIKSJON, KL_DOKUMENT_MAL_RESTRIKSJON)
	  REFERENCES KODELISTE (KODE, KODEVERK) ENABLE
   );
   
   COMMENT ON COLUMN DOKUMENT_MAL_TYPE.KODE IS 'Kodeverk Primary Key';
   COMMENT ON COLUMN DOKUMENT_MAL_TYPE.NAVN IS 'Lesbart navn på dokumentmaltype';
   COMMENT ON COLUMN DOKUMENT_MAL_TYPE.BESKRIVELSE IS 'Utdypende beskrivelse av koden';
   COMMENT ON COLUMN DOKUMENT_MAL_TYPE.GENERISK IS 'Kan dokumentmalen benyttes for informasjonsinnhenting i GUI (Y) eller ikke (N)';
   COMMENT ON COLUMN DOKUMENT_MAL_TYPE.DOKUMENT_MAL_RESTRIKSJON IS 'Restriksjonskode som begrenser bruken av dokumentmalen, eller INGEN';
   COMMENT ON COLUMN DOKUMENT_MAL_TYPE.DOKSYS_KODE IS 'Doksys kodeverkskode';
   COMMENT ON COLUMN DOKUMENT_MAL_TYPE.KL_DOKUMENT_MAL_RESTRIKSJON IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
   COMMENT ON TABLE DOKUMENT_MAL_TYPE  IS 'Angir definerte dokumentmaler som brukes ved brevproduksjon';

  CREATE INDEX IDX_DOKUMENT_MAL_TYPE_1 ON DOKUMENT_MAL_TYPE (DOKUMENT_MAL_RESTRIKSJON);

