INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (seq_kodeliste.nextval,'HISTORIKKINNSLAG_TYPE','TILBAKEKREVING_OPPR',null,null,to_date('01.01.2017','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKKINNSLAG_TYPE','TILBAKEKREVING_OPPR','NB','Tilbakekreving opprettet','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

UPDATE KODELISTE_NAVN_I18N SET NAVN='Vedtaksløsningen' WHERE KL_KODEVERK='HISTORIKK_AKTOER' AND KL_KODE='VL';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Søker' WHERE KL_KODEVERK='HISTORIKK_AKTOER' AND KL_KODE='SOKER';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Saksbehandler' WHERE KL_KODEVERK='HISTORIKK_AKTOER' AND KL_KODE='SBH';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Beslutter' WHERE KL_KODEVERK='HISTORIKK_AKTOER' AND KL_KODE='BESL';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Arbeidsgiver' WHERE KL_KODEVERK='HISTORIKK_AKTOER' AND KL_KODE='ARBEIDSGIVER';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Ikke definert' WHERE KL_KODEVERK='HISTORIKK_AKTOER' AND KL_KODE='-';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Saksbehandling starter på nytt' WHERE KL_KODEVERK='HISTORIKK_BEGRUNNELSE_TYPE' AND KL_KODE='SAKSBEH_START_PA_NYTT';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Behandling startet på nytt' WHERE KL_KODEVERK='HISTORIKK_BEGRUNNELSE_TYPE' AND KL_KODE='BEH_STARTET_PA_NYTT';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Ikke definert' WHERE KL_KODEVERK='HISTORIKK_BEGRUNNELSE_TYPE' AND KL_KODE='-';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Behandling på vent' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='BEH_VENT';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Behandling gjenopptatt' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='BEH_GJEN';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Behandling startet' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='BEH_STARTET';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Vedlegg mottatt' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='VEDLEGG_MOTTATT';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Brev sendt' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='BREV_SENT';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Registrer papirsøknad' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='REGISTRER_PAPIRSØK';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Revurdering opprettet' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='REVURD_OPPR';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Varsel om revurdering ikke sendt' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='VRS_REV_IKKE_SNDT';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Mangelfull søknad' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='MANGELFULL_SØKNAD';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Nye registeropplysninger' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='NYE_REGOPPLYSNINGER';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Vurdering før vedtak' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='BEH_AVBRUTT_VUR';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Nye registeropplysninger' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='KLAGE_BEH_NFP';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Klagebehandling NFP' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='NYE_REGOPPLYSNINGER';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Klagebehandling KA' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='KLAGE_BEH_NK';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Vedtak foreslått og sendt til beslutter' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='NYE_REGOPPLYSNINGER';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Vedtak fattet' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='VEDTAK_FATTET';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Overstyrt' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='OVERSTYRT';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Sak retur' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='SAK_RETUR';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Behandling er henlagt' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='AVBRUTT_BEH';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Fakta endret' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='FAKTA_ENDRET';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Bytt enhet' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='BYTT_ENHET';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Ny info fra TPS' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='NY_INFO_FRA_TPS';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Ikke definert' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='-';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Klage mottatt' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='KLAGEBEH_STARTET';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Uendret utfall' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='UENDRET_UTFALL';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Brev bestilt' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='BREV_BESTILT';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Innsynsbehandling opprettet' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='INNSYN_OPPR';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Gjenoppta behandling' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='BEH_MAN_GJEN';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Behandlet opptjeningsperiode' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='OPPTJENING';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Behandling startet på nytt' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='BEH_STARTET_PÅ_NYTT';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Behandlingen oppdatert med nye opplysninger' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='BEH_OPPDATERT_NYE_OPPL';