-- VilkårResultat
DELETE FROM KODELISTE WHERE KODEVERK='TBK_OPPFYLT_VALG';
DELETE FROM KODEVERK WHERE KODE='TBK_OPPFYLT_VALG';

INSERT INTO KODEVERK (KODE,KODEVERK_EIER,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,SAMMENSATT)
VALUES ('VILKAAR_RESULTAT','VL','N','N','Vilkaar resultat','Kodeverk over vilkaar resultat for hver periode','VL',to_timestamp(sysdate,'DD.MM.RRRR'),null,null,'N');

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'VILKAAR_RESULTAT','FORSTO_BURDE_FORSTÅTT',null,
'Mottaker forsto eller burder forstått at utbetalingen skyldtes en feil',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'VILKAAR_RESULTAT','FEIL_OPPLYSNINGER_FRA_BRUKER',null,
'Mottaker har gitt feil opplysninger ved forsett eller uaktsomhet',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'VILKAAR_RESULTAT','MANGELFULLE_OPPLYSNINGER_FRA_BRUKER',null,
'Mottaker har gitt mangelfulle opplysninger ved forsett eller uaktsomhet',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'VILKAAR_RESULTAT','GOD_TRO',null,
'Mottaker har mottat beløpet i god tro',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));


-- Aktsomhet
INSERT INTO KODEVERK (KODE,KODEVERK_EIER,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,SAMMENSATT)
VALUES ('AKTSOMHET','VL','N','N','Aktsomhet','Kodeverk over for forskjellige aktsomheter','VL',to_timestamp(sysdate,'DD.MM.RRRR'),null,null,'N');

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'AKTSOMHET','FORSETT',null,
'Forsett',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'AKTSOMHET','GROVT_UAKTSOM',null,
'Grovt uaktsom',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'AKTSOMHET','SIMPEL_UAKTSOM',null,
'Simpel uaktsom',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

--SærligGrunn
INSERT INTO KODEVERK (KODE,KODEVERK_EIER,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,SAMMENSATT)
VALUES ('SAERLIG_GRUNN','VL','N','N','Saerlig grunner','Kodeverk over for forskjellige saerlig grunner','VL',to_timestamp(sysdate,'DD.MM.RRRR'),null,null,'N');

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'SAERLIG_GRUNN','GRAD_AV_UAKTSOMHET',null,
'Graden av uaktsomhet hos den kravet retter seg mot',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'SAERLIG_GRUNN','HELT_ELLER_DELVIS_NAVS_FEIL',null,
'Om feilen helt eller delvis kan tilskrives NAV',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'SAERLIG_GRUNN','STOERRELSE_BELOEP',null,
'Størrelsen på feilutbetalt beløp',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'SAERLIG_GRUNN','TID_FRA_UTBETALING',null,
'Hvor lang tid siden utbetalingen fant sted',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'SAERLIG_GRUNN','ANNET',null,
'Annet',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

--NavOppfulgt
INSERT INTO KODEVERK (KODE,KODEVERK_EIER,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,SAMMENSATT)
VALUES ('NAV_OPPFULGT','VL','N','N','Nav oppfulgt','Kodeverk over for forskjellige nav oppfulgt','VL',to_timestamp(sysdate,'DD.MM.RRRR'),null,null,'N');

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'NAV_OPPFULGT','NAV_KAN_IKKE_LASTES',null,
'NAV kan ikke lastes for feilutbetalingen',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'NAV_OPPFULGT','HAR_IKKE_FULGT_OPP',null,
'Har ikke fulgt opp melding om endring',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'NAV_OPPFULGT','HAR_BENYTTET_FEIL',null,
'Har benyttet feil rettsanvendelse',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'NAV_OPPFULGT','HAR_IKKE_SJEKKET',null,
'Har ikke sjekket med andre ytelser',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'NAV_OPPFULGT','BEREGNINGS_FEIL',null,
'Beregningsfeil',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'NAV_OPPFULGT','HAR_UTFOERT_FEIL',null,
'Har utført feil trekk/feil i økonomi',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'NAV_OPPFULGT','HAR_SENDT_TIL_FEIL_MOTTAKER',null,
'Har sendt utbetaling til feil mottaker',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));