CREATE TABLE OKO_XML_MOTATT_ARKIV
(
  ID NUMBER(19, 0)                                NOT NULL ,
  MELDING CLOB                                    NOT NULL,
  OPPRETTET_AV VARCHAR2(200 CHAR) DEFAULT 'VL'    NOT NULL,
  OPPRETTET_TID TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
  ENDRET_AV VARCHAR2(200 CHAR),
  ENDRET_TID TIMESTAMP(3),
  CONSTRAINT PK_OKO_XML_MOTATT_ARKIV PRIMARY KEY (ID)
);

COMMENT ON TABLE OKO_XML_MOTATT_ARKIV IS 'Tabell for å arkivere gamle kravgrunnlag som ikke finnes i Økonomi.';
COMMENT ON COLUMN OKO_XML_MOTATT_ARKIV.ID IS 'Primary key';
COMMENT ON COLUMN OKO_XML_MOTATT_ARKIV.MELDING IS 'Gammel kravgrunnlag XML';
