CREATE INDEX IDX_OKO_XML_MOTTATT_4 ON OKO_XML_MOTTATT (OPPRETTET_TID);

CREATE INDEX IDX_OKO_XML_MOTTATT_5 ON OKO_XML_MOTTATT (TILKOBLET);

CREATE INDEX IDX_OKO_XML_MOTTATT_6 ON OKO_XML_MOTTATT (MELDING) INDEXTYPE IS CTXSYS.CONTEXT;
