INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'NAV_OPPFULGT','-',null,
'Ikke definert',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KONFIG_VERDI_KODE (KODE, NAVN, KONFIG_GRUPPE, KONFIG_TYPE, BESKRIVELSE) VALUES ('rettsgebyr', '4 Retts gebyr', 'INGEN', 'INTEGER',
'Rettsgebyr');

INSERT INTO KONFIG_VERDI (ID,KONFIG_KODE,KONFIG_GRUPPE,KONFIG_VERDI,GYLDIG_FOM,GYLDIG_TOM) VALUES (SEQ_KONFIG_VERDI.NEXTVAL,'rettsgebyr','INGEN','1000',
to_date('01.01.2016','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO AKSJONSPUNKT_DEF (KODE, NAVN, VURDERINGSPUNKT, BESKRIVELSE, VILKAR_TYPE, TOTRINN_BEHANDLING_DEFAULT, AKSJONSPUNKT_TYPE, FRIST_PERIODE, TILBAKEHOPP_VED_GJENOPPTAKELSE, LAG_UTEN_HISTORIKK, SKJERMLENKE_TYPE )
VALUES ('5004', 'Foreslå vedtak', 'FORVEDSTEG.UT', 'Foreslå vedtak', '-', 'N', 'MANU', null, 'N', 'N', '-');