CREATE SEQUENCE SEQ_FAGSAK MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

ALTER TABLE EKSTERN_BEHANDLING ADD EKSTERN_UUID RAW(16);

COMMENT ON COLUMN EKSTERN_BEHANDLING.EKSTERN_UUID IS 'Unik UUID for ekstern-behandling';

CREATE INDEX IDX_EKSTERN_BEHANDLING_3 ON EKSTERN_BEHANDLING (EKSTERN_UUID);
