alter table BREV_SPORING add VERSJON NUMBER(19,0) DEFAULT 0 NOT NULL;
alter table EKSTERN_BEHANDLING add VERSJON NUMBER(19,0) DEFAULT 0 NOT NULL;
alter table GR_FAKTA_FEILUTBETALING add VERSJON NUMBER(19,0) DEFAULT 0 NOT NULL;
alter table GR_KRAV_GRUNNLAG add VERSJON NUMBER(19,0) DEFAULT 0 NOT NULL;
alter table GR_KRAV_VEDTAK_STATUS add VERSJON NUMBER(19,0) DEFAULT 0 NOT NULL;
alter table GR_VERGE add VERSJON NUMBER(19,0) DEFAULT 0 NOT NULL;
alter table GR_VILKAAR add VERSJON NUMBER(19,0) DEFAULT 0 NOT NULL;
alter table GR_VURDERT_FORELDELSE add VERSJON NUMBER(19,0) DEFAULT 0 NOT NULL;
alter table MOTTAKER_VARSEL_RESPONS add VERSJON NUMBER(19,0) DEFAULT 0 NOT NULL;
alter table OKO_XML_MOTTATT add VERSJON NUMBER(19,0) DEFAULT 0 NOT NULL;
alter table OKO_XML_SENDT add VERSJON NUMBER(19,0) DEFAULT 0 NOT NULL;
alter table VARSEL add VERSJON NUMBER(19,0) DEFAULT 0 NOT NULL;
alter table VEDTAKSBREV_OPPSUMMERING add VERSJON NUMBER(19,0) DEFAULT 0 NOT NULL;
alter table VEDTAKSBREV_PERIODE add VERSJON NUMBER(19,0) DEFAULT 0 NOT NULL;

