Insert into BEHANDLING_STEG_TYPE (KODE,NAVN,BEHANDLING_STATUS_DEF,BESKRIVELSE)
values ('VTILBSTEG','Vurder tilbakekreving','UTRED','Vurdere om og hva som skal tilbakekreves');

insert into BEHANDLING_TYPE_STEG_SEKV (ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval, 'BT-007', 'VTILBSTEG', 90);

Insert into VURDERINGSPUNKT_DEF (KODE,BEHANDLING_STEG,VURDERINGSPUNKT_TYPE,NAVN)
values ('VTILBSTEG.INN','VTILBSTEG','INN','Vurder tilbakekreving - Inngang');

Insert into VURDERINGSPUNKT_DEF (KODE,BEHANDLING_STEG,VURDERINGSPUNKT_TYPE,NAVN)
values ('VTILBSTEG.UT','VTILBSTEG','UT','Vurder tilbakekreving - Utgang');

Insert into AKSJONSPUNKT_DEF (KODE,NAVN,VURDERINGSPUNKT,BESKRIVELSE,TOTRINN_BEHANDLING_DEFAULT,AKSJONSPUNKT_TYPE,TILBAKEHOPP_VED_GJENOPPTAKELSE,LAG_UTEN_HISTORIKK, SKJERMLENKE_TYPE)
values ('5002','Vurder tilbakekreving','VTILBSTEG.UT','Vurder tilbakekreving.','J','MANU','N','N', '-');

