ALTER TABLE FAGSAK ADD YTELSE_TYPE VARCHAR2(100 CHAR) DEFAULT 'FP' NOT NULL;

ALTER TABLE FAGSAK ADD KL_YTELSE_TYPE VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('FAGSAK_YTELSE') VIRTUAL VISIBLE;

ALTER TABLE FAGSAK ADD CONSTRAINT FK_FAGSAK_3 FOREIGN KEY ("YTELSE_TYPE","KL_YTELSE_TYPE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

CREATE INDEX IDX_FAGSAK_3 ON FAGSAK (YTELSE_TYPE);

COMMENT ON COLUMN FAGSAK.YTELSE_TYPE IS 'Fremmednøkkel til kodeverkstabellen som inneholder oversikt over ytelser';
COMMENT ON COLUMN FAGSAK.KL_YTELSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
