ALTER TABLE VILKAAR_AKTSOMHET RENAME COLUMN BELOEP_TILBAKEKREVES TO MANUELT_SATT_BELOEP;

COMMENT ON COLUMN VILKAAR_AKTSOMHET.MANUELT_SATT_BELOEP IS 'Feilutbetalt beløp som skal tilbakekreves som bestemt ved saksbehandler';