--AKSJONSPUNKT_DEF
UPDATE AKSJONSPUNKT_DEF SET TOTRINN_BEHANDLING_DEFAULT='J' WHERE KODE IN (7003,5002,5003);
UPDATE AKSJONSPUNKT_DEF SET VURDERINGSPUNKT='FVEDSTEG.INN' WHERE KODE=5005;

--KODELISTE
INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE, GYLDIG_FOM)  VALUES (SEQ_KODELISTE.NEXTVAL, 'HISTORIKKINNSLAG_TYPE', 'SAK_GODKJENT', 'Sak godkjent', to_date('2000-01-01', 'YYYY-MM-DD'));

-- KODELISTE_NAVN_I18N
INSERT INTO KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN) VALUES  (SEQ_KODELISTE_NAVN_I18N.NEXTVAL, 'HISTORIKKINNSLAG_TYPE', 'SAK_GODKJENT','NB', 'Sak godkjent');

UPDATE KODELISTE_NAVN_I18N SET NAVN='Feil fakta' WHERE KL_KODEVERK='VURDER_AARSAK' AND KL_KODE='FEIL_FAKTA';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Feil lovanvendelse' WHERE KL_KODEVERK='VURDER_AARSAK' AND KL_KODE='FEIL_LOV';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Feil regelforståelse' WHERE KL_KODEVERK='VURDER_AARSAK' AND KL_KODE='FEIL_REGEL';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Annet' WHERE KL_KODEVERK='VURDER_AARSAK' AND KL_KODE='ANNET';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Ikke definert' WHERE KL_KODEVERK='VURDER_AARSAK' AND KL_KODE='-';