INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'SKJERMLENKE_TYPE','FAKTA_OM_FEILUTBETALING',null,'Fakta om feilutbetaling',to_date('01.01.2000','DD.MM.RRRR'),
to_date('31.12.9999','DD.MM.RRRR'),'VL',to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'SKJERMLENKE_TYPE','FAKTA_OM_FEILUTBETALING','NB','Fakta om feilutbetaling','VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);


INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKKINNSLAG_TYPE','FAKTA_OM_FEILUTBETALING',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKKINNSLAG_TYPE','FAKTA_OM_FEILUTBETALING','NB','Fakta om feilutbetaling','VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','HENDELSE_AARSAK',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','HENDELSE_AARSAK','NB','Hendelse','VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','HENDELSE_UNDER_AARSAK',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','HENDELSE_UNDER_AARSAK','NB','Hendelse Under Årsak','VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKK_OPPLYSNING_TYPE','PERIODE_FOM',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKK_OPPLYSNING_TYPE','PERIODE_FOM','NB',null,'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKK_OPPLYSNING_TYPE','PERIODE_TOM',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKK_OPPLYSNING_TYPE','PERIODE_TOM','NB',null,'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);
