ALTER TABLE AKSJONSPUNKT SET UNUSED (REAKTIVERING_STATUS, REVURDERING, MANUELT_OPPRETTET);
DROP TABLE AKSJONSPUNKT_UTELUKKENDE;
DROP TABLE AKSJONSPUNKT_DEF;
DROP TABLE VURDERINGSPUNKT_DEF;
DROP TABLE BEHANDLING_TYPE_STEG_SEKV;
DROP TABLE BEHANDLING_STEG_TYPE;
