ALTER TABLE VILKAAR_AKTSOMHET ADD SARLIG_GRUNNER_TIL_REDUKSJON varchar2(1 char);

comment on column VILKAAR_AKTSOMHET.SARLIG_GRUNNER_TIL_REDUKSJON is 'Angir om særlig grunner gi reduksjon av beløpet';

ALTER TABLE VILKAAR_AKTSOMHET ADD CONSTRAINT CHK_GRUNNER_TIL_REDUSKSJON check (SARLIG_GRUNNER_TIL_REDUKSJON is null or SARLIG_GRUNNER_TIL_REDUKSJON in ('J', 'N'));

ALTER TABLE VILKAAR_AKTSOMHET ADD TILBAKEKREV_SMAABELOEP varchar2(1 char);

comment on column VILKAAR_AKTSOMHET.TILBAKEKREV_SMAABELOEP is 'Angir om skal tilbakekreves når totalbeløpet er under 4 rettsgebyr';

ALTER TABLE VILKAAR_AKTSOMHET ADD CONSTRAINT CHK_TILBAKEKREV_SMAABELOEP check (TILBAKEKREV_SMAABELOEP is null or TILBAKEKREV_SMAABELOEP in ('J', 'N'));

ALTER TABLE VILKAAR_SAERLIG_GRUNN ADD BEGRUNNELSE varchar2(4000 char);

comment on column VILKAAR_SAERLIG_GRUNN.BEGRUNNELSE is 'Beskrivelse av særlig grunn hvis grunn er annet';

ALTER TABLE VILKAAR_AKTSOMHET MODIFY BEGRUNNELSE varchar2(4000 char);

ALTER TABLE VILKAAR_GOD_TRO MODIFY BEGRUNNELSE varchar2(4000 char);

ALTER TABLE VILKAAR_PERIODE MODIFY BEGRUNNELSE varchar2(4000 char);