INSERT INTO AKSJONSPUNKT_DEF (KODE, NAVN, VURDERINGSPUNKT, BESKRIVELSE, VILKAR_TYPE, TOTRINN_BEHANDLING_DEFAULT, AKSJONSPUNKT_TYPE, FRIST_PERIODE, TILBAKEHOPP_VED_GJENOPPTAKELSE, LAG_UTEN_HISTORIKK, SKJERMLENKE_TYPE )
VALUES ('5005', 'Fatte vedtak', 'FVEDSTEG.UT', 'Fatte vedtak', '-', 'N', 'MANU', null, 'N', 'N', '-');

--historikkinnslag
UPDATE KODELISTE_NAVN_I18N SET NAVN='Vedtak' where KL_KODEVERK='SKJERMLENKE_TYPE' and KL_KODE='VEDTAK';