DROP TABLE DAGLIG_UTBETALING;
DROP SEQUENCE SEQ_DAGLIG_UTBETALING;

DROP TABLE UTBETALING_PERIODE;
DROP SEQUENCE SEQ_UTBETALING_PERIODE;

DROP TABLE GR_TBK_GRUNNLAG;
DROP SEQUENCE SEQ_GR_TBK_GRUNNLAG;

DROP TABLE TBK_GRUNNLAG;
DROP SEQUENCE SEQ_TBK_GRUNNLAG;



