ALTER TABLE VEDTAK_XML_OS RENAME COLUMN VEDTAK_XML TO MELDING;

ALTER TABLE VEDTAK_XML_OS RENAME COLUMN KVITTERING_XML TO KVITTERING;

ALTER TABLE VEDTAK_XML_OS RENAME CONSTRAINT PK_VEDTAK_XML_OS TO PK_OKO_XML_SENDT;

ALTER TABLE VEDTAK_XML_OS RENAME CONSTRAINT FK_VEDTAK_XML_OS_1 TO FK_OKO_XML_SENDT_1;

ALTER INDEX IDX_VEDTAK_XML_OS_1 RENAME TO IDX_OKO_XML_SENDT_1;

ALTER TABLE VEDTAK_XML_OS ADD MELDING_TYPE VARCHAR2(100 CHAR);

ALTER TABLE VEDTAK_XML_OS ADD KL_MELDING_TYPE VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('MELDING_TYPE') VIRTUAL VISIBLE;

ALTER TABLE VEDTAK_XML_OS RENAME TO OKO_XML_SENDT;

RENAME SEQ_VEDTAK_XML_OS TO SEQ_OKO_XML_SENDT;

CREATE INDEX IDX_OKO_XML_SENDT_2 ON OKO_XML_SENDT (MELDING_TYPE);

ALTER TABLE OKO_XML_SENDT ADD CONSTRAINT FK_OKO_XML_SENDT_2 FOREIGN KEY (MELDING_TYPE, KL_MELDING_TYPE) REFERENCES KODELISTE (KODE, KODEVERK) ENABLE;

COMMENT ON TABLE OKO_XML_SENDT IS 'Tabell som tar vare på XML sendt til OS, brukes for feilsøking';
COMMENT ON COLUMN OKO_XML_SENDT.MELDING IS 'XML sendt til OS';
COMMENT ON COLUMN OKO_XML_SENDT.KVITTERING IS 'Respons fra OS';
COMMENT ON COLUMN OKO_XML_SENDT.MELDING_TYPE IS 'Melding Type';
COMMENT ON COLUMN OKO_XML_SENDT.KL_MELDING_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';

UPDATE OKO_XML_SENDT SET MELDING_TYPE='VEDTAK' WHERE MELDING_TYPE IS NULL;

ALTER TABLE OKO_XML_SENDT MODIFY MELDING_TYPE NOT NULL ENABLE;

ALTER TABLE OKO_XML_SENDT MODIFY KL_MELDING_TYPE NOT NULL ENABLE;

INSERT INTO PROSESS_TASK_TYPE (KODE,NAVN,FEIL_MAKS_FORSOEK,BESKRIVELSE)
VALUES ('slett.midlertidig.lagret.xml','Slett XML som er sendt til økonomi','3','Sletter sendt XML som er sendt til økonomi');
