INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKK_OPPLYSNING_TYPE','SÆRLIG_GRUNNER_BEGRUNNELSE',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

ALTER TABLE VILKAAR_AKTSOMHET ADD SARLIG_GRUNNER_BEGRUNNELSE VARCHAR2(4000 CHAR);
COMMENT ON COLUMN VILKAAR_AKTSOMHET.SARLIG_GRUNNER_BEGRUNNELSE is 'beskrivelse av særlig grunner';
