ALTER TABLE FEILUTBETALING_PERIODE_AARSAK ADD AARSAK_KODEVERK VARCHAR2(100 CHAR) NOT NULL;

ALTER TABLE FEILUTBETALING_PERIODE_AARSAK ADD UNDER_AARSAK_KODEVERK VARCHAR2(100 CHAR);

COMMENT ON COLUMN FEILUTBETALING_PERIODE_AARSAK.AARSAK_KODEVERK IS 'Årsak kodeverk fra Kodeverk tabell';

COMMENT ON COLUMN FEILUTBETALING_PERIODE_AARSAK.UNDER_AARSAK_KODEVERK IS 'Under årsak kodeverk fra Kodeverk tabell';