-- FEILUTBTALING
CREATE TABLE FEILUTBETALING(
    ID                              NUMBER(19)                       NOT NULL,
    OPPRETTET_AV                   VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
    OPPRETTET_TID                  TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
    ENDRET_AV                      VARCHAR2(20 CHAR),
    ENDRET_TID                     TIMESTAMP(3),
    CONSTRAINT PK_FEILUTBETALING PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_FEILUTBETALING MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE FEILUTBETALING is 'Kobler flere perioder av fakta om feilutbetaling for tilbakekreving';

-- GR_FEILUTBETALING
CREATE TABLE GR_FEILUTBETALING (
  ID                        NUMBER(19, 0)      NOT NULL,
  BEHANDLING_ID             NUMBER(19, 0)      NOT NULL,
  FEILUTBETALING_ID   NUMBER(19, 0)      NOT NULL,
  AKTIV                     varchar2(1 char)   not null,
  OPPRETTET_AV              VARCHAR2(20 CHAR) DEFAULT 'VL'         NOT NULL ,
  OPPRETTET_TID             TIMESTAMP(3) DEFAULT systimestamp      NOT NULL ,
  ENDRET_AV                 VARCHAR2(20 CHAR),
  ENDRET_TID                TIMESTAMP(3),
  CONSTRAINT PK_GR_FEILUTBETALING PRIMARY KEY (ID),
  CONSTRAINT FK_GR_FEILUTBETALING_1 FOREIGN KEY (BEHANDLING_ID) REFERENCES BEHANDLING(ID),
  CONSTRAINT FK_GR_FEILUTBETALING_2 FOREIGN KEY (FEILUTBETALING_ID) REFERENCES FEILUTBETALING(ID),
  CONSTRAINT CHK_AKTIV_FEILUTBETALING CHECK (AKTIV IN ('J', 'N'))
);

CREATE SEQUENCE SEQ_GR_FEILUTBETALING MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE  GR_FEILUTBETALING is 'Versjonering av fakta om feilutbetaling for tilbakekreving';
COMMENT ON COLUMN GR_FEILUTBETALING.BEHANDLING_ID is 'Referanse til behandling';
COMMENT ON COLUMN GR_FEILUTBETALING.FEILUTBETALING_ID is 'FK:FEILUTBETALING';
COMMENT ON COLUMN GR_FEILUTBETALING.AKTIV is 'Angir status av fakta om feilutbetaling';

CREATE INDEX IDX_GR_FEILUTBETALING_1 ON GR_FEILUTBETALING(BEHANDLING_ID);
CREATE INDEX IDX_GR_FEILUTBETALING_2 ON GR_FEILUTBETALING(FEILUTBETALING_ID);

-- Alter tabell FEILUTBETALING_PERIODE_AARSAK

ALTER TABLE FEILUTBETALING_PERIODE_AARSAK ADD FEILUTBETALING_ID NUMBER(19, 0) NOT NULL;

COMMENT ON COLUMN FEILUTBETALING_PERIODE_AARSAK.FEILUTBETALING_ID is 'FK:FEILUTBETALING';

ALTER TABLE FEILUTBETALING_PERIODE_AARSAK ADD CONSTRAINT FK_FEILUTBET_PERIODE_AARSAK_2 FOREIGN KEY (FEILUTBETALING_ID)
REFERENCES FEILUTBETALING (ID) ENABLE;

ALTER TABLE FEILUTBETALING_PERIODE_AARSAK DROP COLUMN BEHANDLING_ID;

ALTER TABLE FEILUTBETALING_PERIODE_AARSAK DROP COLUMN AKTIV;

CREATE INDEX IDX_FEILUTBET_PERIODE_AARSAK_2 ON FEILUTBETALING_PERIODE_AARSAK(FEILUTBETALING_ID);
