DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK IN('VEDTAK_RESULTAT_TYPE','VEDTAK_RESULTAT');
DELETE FROM KODELISTE WHERE KODEVERK IN ('VEDTAK_RESULTAT_TYPE','VEDTAK_RESULTAT');
DELETE FROM KODEVERK WHERE KODE IN ('VEDTAK_RESULTAT_TYPE','VEDTAK_RESULTAT');

INSERT INTO KODEVERK (KODE,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE)
VALUES ('VEDTAK_RESULTAT_TYPE','N','N','Vedtak Resultat','Internt kodeverk for vedtak resultat. ');

INSERT INTO KODELISTE (ID,KODEVERK,KODE,BESKRIVELSE,GYLDIG_FOM) VALUES (seq_kodeliste.nextval,'VEDTAK_RESULTAT_TYPE','FULL_TILBAKEBETALING', 'Full tilbakebetaling',to_date('01.01.2000','DD.MM.RRRR'));
INSERT INTO KODELISTE (ID,KODEVERK,KODE,BESKRIVELSE,GYLDIG_FOM) VALUES (seq_kodeliste.nextval,'VEDTAK_RESULTAT_TYPE','DELVIS_TILBAKEBETALING', 'Delvis tilbakebetaling',to_date('01.01.2000','DD.MM.RRRR'));
INSERT INTO KODELISTE (ID,KODEVERK,KODE,BESKRIVELSE,GYLDIG_FOM) VALUES (seq_kodeliste.nextval,'VEDTAK_RESULTAT_TYPE','INGEN_TILBAKEBETALING', 'Ingen tilbakebetaling',to_date('01.01.2000','DD.MM.RRRR'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE, GYLDIG_FOM)  VALUES (SEQ_KODELISTE.NEXTVAL, 'VEDTAK_RESULTAT_TYPE', '-', 'Udefinert', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN) VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL, 'VEDTAK_RESULTAT_TYPE', 'FULL_TILBAKEBETALING','NB','Tilbakebetaling');
INSERT INTO KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN) VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL, 'VEDTAK_RESULTAT_TYPE', 'DELVIS_TILBAKEBETALING', 'NB', 'Delvis tilbakebetaling');
INSERT INTO KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN) VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL, 'VEDTAK_RESULTAT_TYPE', 'INGEN_TILBAKEBETALING', 'NB', 'Ingen tilbakebetaling');

INSERT INTO PROSESS_TASK_TYPE (KODE,NAVN,FEIL_MAKS_FORSOEK,FEIL_SEK_MELLOM_FORSOEK,BESKRIVELSE) values ('iverksetteVedtak.avsluttBehandling','Avslutte behandling i modul Iverksette vedtak','3','30',
'Avslutter behandlingen når brev er sendt og tilbakekrevingsvedtak til økonomi overført');

INSERT INTO PROSESS_TASK_TYPE (KODE,NAVN,FEIL_MAKS_FORSOEK,FEIL_SEK_MELLOM_FORSOEK,BESKRIVELSE) values ('iverksetteVedtak.sendVedtaksbrev','Kall til "Sende vedtaksbrev" i Iverksette vedtak','3','30',
'Sender vedtaksbrev til brukeren via DokumentBestilleren, venter på kvittering');

INSERT INTO PROSESS_TASK_TYPE (KODE,NAVN,FEIL_MAKS_FORSOEK,FEIL_SEK_MELLOM_FORSOEK,BESKRIVELSE) values ('iverksetteVedtak.sendØkonomiTilbakekrevingsvedtak','Send tilbakekrevingsvedtak til økonomi','3','30',
'Send tilbakekrevingsvedtak til økonomi');