create sequence SEQ_VEDTAKSBREV_SPORING minvalue 1000000 start with 1000000 increment by 50 nocache nocycle;

CREATE TABLE VEDTAKSBREV_SPORING
(
  ID             NUMBER(19, 0) NOT NULL,
  BEHANDLING_ID  NUMBER(19, 0) NOT NULL,
  JOURNALPOST_ID VARCHAR2(20 CHAR) NOT NULL,
  DOKUMENT_ID    VARCHAR2(20 CHAR) NOT NULL,
  OPPRETTET_AV   VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  OPPRETTET_TID  TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  ENDRET_AV      VARCHAR2(20 CHAR),
  ENDRET_TID     TIMESTAMP(3),
  CONSTRAINT PK_VEDTAKSBREV_SPORING PRIMARY KEY (ID),
  CONSTRAINT FK_VEDTAKSBREV_SPORING FOREIGN KEY (BEHANDLING_ID) REFERENCES BEHANDLING (ID) ENABLE
);

CREATE INDEX IDX_VEDTAKSBREVSPORING ON VEDTAKSBREV_SPORING (BEHANDLING_ID);

COMMENT ON COLUMN VEDTAKSBREV_SPORING.ID IS 'Primary Key';
COMMENT ON COLUMN VEDTAKSBREV_SPORING.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling i fptilbake';
COMMENT ON COLUMN VEDTAKSBREV_SPORING.JOURNALPOST_ID IS 'Journalpostid i Doksys';
COMMENT ON COLUMN VEDTAKSBREV_SPORING.DOKUMENT_ID IS 'Dokumentid i Doksys';
COMMENT ON TABLE VEDTAKSBREV_SPORING  IS 'Vedtaksbrevsporing innholder informasjon om vedtaksbrevet som er bestilt.';


create sequence SEQ_VEDTAKSBREV_OPPSUMMERING minvalue 1000000 start with 1000000 increment by 50 nocache nocycle;

CREATE TABLE VEDTAKSBREV_OPPSUMMERING
(
  ID                    NUMBER(19, 0) NOT NULL,
  BEHANDLING_ID         NUMBER(19, 0) NOT NULL,
  OPPSUMMERING_FRITEKST VARCHAR2(1500 CHAR),
  OPPRETTET_TID         TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  OPPRETTET_AV          VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  ENDRET_AV             VARCHAR2(20 CHAR),
  ENDRET_TID            TIMESTAMP(3),
  CONSTRAINT PK_VEDTAKSBREV_OPPSUMMERING PRIMARY KEY (ID),
  CONSTRAINT FK_VEDTAKSBREV_OPPSUMMERING FOREIGN KEY (BEHANDLING_ID) REFERENCES BEHANDLING (ID) ENABLE
);

CREATE INDEX IDX_VEDTAKSBREVOPPSUMMERING ON VEDTAKSBREV_OPPSUMMERING (BEHANDLING_ID);

COMMENT ON COLUMN VEDTAKSBREV_OPPSUMMERING.ID IS 'Primary Key';
COMMENT ON COLUMN VEDTAKSBREV_OPPSUMMERING.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling i fptilbake';
COMMENT ON COLUMN VEDTAKSBREV_OPPSUMMERING.OPPSUMMERING_FRITEKST IS 'Fritekst fra saksbehandler til oppsummering av vedtaket';
COMMENT ON TABLE VEDTAKSBREV_OPPSUMMERING  IS 'Inneholder friteksten til vedtaksoppsummeringen som er skrevet inn av saksbehandler.';

INSERT INTO KODEVERK (KODE,KODEVERK_EIER,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,SAMMENSATT)
VALUES ('FRITEKST_TYPE','VL','N','N','Friteksttype til vedtaksbrev','Friteksttype til vedtaksbrev','VL',to_timestamp(sysdate,'DD.MM.RRRR'),null,null,'N');

INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE, GYLDIG_FOM, GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'FRITEKST_TYPE','FAKTA_AVSNITT',null, 'Fritekst til faktaavsnittet i vedtaksbrevet',
        to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE, GYLDIG_FOM, GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'FRITEKST_TYPE','VILKAAR_AVSNITT',null, 'Fritekst til vilkårsavsnittet i vedtaksbrevet',
        to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE, GYLDIG_FOM, GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'FRITEKST_TYPE','SAERLIGE_GRUNNER_AVSNITT',null, 'Fritekst til avsnittet om særlige grunner i vedtaksbrevet',
        to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));


create sequence SEQ_VEDTAKSBREV_PERIODE minvalue 1000000 start with 1000000 increment by 50 nocache nocycle;

CREATE TABLE VEDTAKSBREV_PERIODE
(
  ID               NUMBER(19, 0) NOT NULL,
  BEHANDLING_ID    NUMBER(19, 0) NOT NULL,
  FOM              DATE                              NOT NULL,
  TOM              DATE                              NOT NULL,
  FRITEKST         VARCHAR2(1500 CHAR) NOT NULL,
  FRITEKST_TYPE    VARCHAR2(200 CHAR) NOT NULL,
  KL_FRITEKST_TYPE VARCHAR2(100 CHAR) generated always as ('FRITEKST_TYPE') VIRTUAL VISIBLE NOT NULL ENABLE,
  OPPRETTET_TID    TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  OPPRETTET_AV     VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  ENDRET_AV        VARCHAR2(20 CHAR),
  ENDRET_TID       TIMESTAMP(3),
  CONSTRAINT PK_VEDTAKSBREV_PERIODE PRIMARY KEY (ID),
  CONSTRAINT FK_VEDTAKSBREV_PERIODE FOREIGN KEY (BEHANDLING_ID) REFERENCES BEHANDLING (ID) ENABLE
);

CREATE INDEX IDX_VEDTAKSBREVPERIODER ON VEDTAKSBREV_PERIODE (BEHANDLING_ID);

COMMENT ON COLUMN VEDTAKSBREV_PERIODE.ID IS 'Primary Key';
COMMENT ON COLUMN VEDTAKSBREV_PERIODE.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling i fptilbake';
COMMENT ON COLUMN VEDTAKSBREV_PERIODE.FOM IS 'Fom-dato for perioden';
COMMENT ON COLUMN VEDTAKSBREV_PERIODE.TOM IS 'Tom-dato for perioden';
COMMENT ON COLUMN VEDTAKSBREV_PERIODE.FRITEKST IS 'Fritekst skrevet til et av avsnittene i vedtaksbrevet';
COMMENT ON COLUMN VEDTAKSBREV_PERIODE.FRITEKST_TYPE IS 'Hvilket avsnitt friteksten gjelder';
COMMENT ON COLUMN VEDTAKSBREV_PERIODE.KL_FRITEKST_TYPE IS 'Hvilket kodeverk friteksttypen er tilknyttet';
COMMENT ON TABLE VEDTAKSBREV_PERIODE  IS 'Inneholder en periode i et vedtaksbrev, samt fritekst';

ALTER TABLE VARSELBREV_DATA RENAME TO VARSELBREV_SPORING;
