UPDATE KRAV_GRUNNLAG_BELOP_433 SET SKATT_PROSENT=0 where SKATT_PROSENT is null;

UPDATE KRAV_GRUNNLAG_PERIODE_432 SET BELOP_SKATT_MND=0 WHERE BELOP_SKATT_MND is null;

ALTER TABLE KRAV_GRUNNLAG_BELOP_433 MODIFY SKATT_PROSENT NOT NULL ENABLE;

ALTER TABLE KRAV_GRUNNLAG_PERIODE_432 MODIFY BELOP_SKATT_MND NOT NULL ENABLE;
