INSERT INTO DOKUMENT_MAL_TYPE (KODE,NAVN,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,GENERISK,DOKUMENT_MAL_RESTRIKSJON,DOKSYS_KODE)
VALUES ('INNHEN','Innhent dokumentasjon',null,'VL',systimestamp,null,null,'J','INGEN','000049');

INSERT INTO DOKUMENT_MAL_TYPE (KODE,NAVN,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,GENERISK,DOKUMENT_MAL_RESTRIKSJON,DOKSYS_KODE)
VALUES ('VARS','Varsel om tilbakekreving dokumentasjon',null,'VL',systimestamp,null,null,'N','ÅPEN_BEHANDLING','000050');

INSERT INTO DOKUMENT_MAL_TYPE (KODE,NAVN,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,GENERISK,DOKUMENT_MAL_RESTRIKSJON,DOKSYS_KODE)
VALUES ('KORRIGVARS','Korrigert Varsel om tilbakekreving dokumentasjon',null,'VL',systimestamp,null,null,'N','ÅPEN_BEHANDLING','000050');

INSERT INTO DOKUMENT_MAL_TYPE (KODE,NAVN,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,GENERISK,DOKUMENT_MAL_RESTRIKSJON,DOKSYS_KODE)
VALUES ('FRITKS','Fritekstbrev',null,'VL',systimestamp,null,null,'J','INGEN','000096');
