ALTER TABLE KRAVGRUNNLAG_XML RENAME TO OKO_XML_MOTTATT;

RENAME SEQ_KRAVGRUNNLAG_XML TO SEQ_OKO_XML_MOTTATT;

CREATE TABLE GR_KRAV_VEDTAK_STATUS(
  ID                        NUMBER(19, 0)               NOT NULL ,
  KRAV_VEDTAK_STATUS_ID     NUMBER(19, 0)               NOT NULL ,
  BEHANDLING_ID             NUMBER(19, 0)               NOT NULL ,
  AKTIV                     VARCHAR2(1)                 NOT NULL ,
  OPPRETTET_AV  VARCHAR2(200 CHAR) DEFAULT 'VL'         NOT NULL ,
  OPPRETTET_TID TIMESTAMP(3) DEFAULT systimestamp       NOT NULL ,
  ENDRET_AV     VARCHAR2(20 CHAR),
  ENDRET_TID    TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_GR_KRAV_VEDTAK_STATUS MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE  GR_KRAV_VEDTAK_STATUS IS 'Aggregate tabell for å lagre kravOgVedtakStatus';
COMMENT ON COLUMN GR_KRAV_VEDTAK_STATUS.ID IS 'Primary Key';
COMMENT ON COLUMN GR_KRAV_VEDTAK_STATUS.KRAV_VEDTAK_STATUS_ID IS 'FK:KRAV_VEDTAK_STATUS_437.Angir kravOgVedtakStatus kommer fra okonomi';
COMMENT ON COLUMN GR_KRAV_VEDTAK_STATUS.BEHANDLING_ID IS 'FK: BEHANDLING fremmednøkkel for tilknyttet behandling';
COMMENT ON COLUMN GR_KRAV_VEDTAK_STATUS.AKTIV IS 'Angir status av grunnlag';

--------------------------------------------------------
--  DDL for Index og Primary Key
--------------------------------------------------------

ALTER TABLE GR_KRAV_VEDTAK_STATUS  ADD CONSTRAINT PK_GR_KRAV_VEDTAK_STATUS PRIMARY KEY ("ID") ENABLE;

CREATE INDEX IDX_GR_KRAV_VEDTAK_STATUS_1 ON GR_KRAV_VEDTAK_STATUS ("KRAV_VEDTAK_STATUS_ID");

CREATE INDEX IDX_GR_KRAV_VEDTAK_STATUS_2 ON GR_KRAV_VEDTAK_STATUS ("BEHANDLING_ID");

--------------------------------------------------------
--  Ref Constraints for Tabeller
--------------------------------------------------------

ALTER TABLE GR_KRAV_VEDTAK_STATUS ADD CONSTRAINT FK_GR_KRAV_VEDTAK_STATUS_1 FOREIGN KEY ("BEHANDLING_ID")
REFERENCES BEHANDLING("ID") ENABLE;

ALTER TABLE GR_KRAV_VEDTAK_STATUS ADD CONSTRAINT FK_GR_KRAV_VEDTAK_STATUS_2 FOREIGN KEY ("KRAV_VEDTAK_STATUS_ID")
REFERENCES KRAV_VEDTAK_STATUS_437("ID") ENABLE;
