--KLASSE_KODE
INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPSVATORD',null,'FPSVATORD',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPSVATORD','NB','FPSVATORD','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPSVATFRI',null,'FPSVATFRI',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPSVATFRI','NB','FPSVATFRI','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPSVSND-OP',null,'FPSVSND-OP',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPSVSND-OP','NB','FPSVSND-OP','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPSVATAL',null,'FPSVATAL',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPSVATAL','NB','FPSVATAL','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPSVATSJO',null,'FPSVATSJO',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPSVATSJO','NB','FPSVATSJO','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPSVSNDDM-OP',null,'FPSVSNDDM-OP',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPSVSNDDM-OP','NB','FPSVSNDDM-OP','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPSVSNDJB-OP',null,'FPSVSNDJB-OP',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPSVSNDJB-OP','NB','FPSVSNDJB-OP','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPSVSNDFI',null,'FPSVSNDFI',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPSVSNDFI','NB','FPSVSNDFI','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

