UPDATE KODELISTE_NAVN_I18N SET NAVN='Avbrutt' WHERE KL_KODEVERK='AKSJONSPUNKT_STATUS' AND KL_KODE='AVBR';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Opprettet' WHERE KL_KODEVERK='AKSJONSPUNKT_STATUS' AND KL_KODE='OPPR';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Utført' WHERE KL_KODEVERK='AKSJONSPUNKT_STATUS' AND KL_KODE='UTFO';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Avsluttet' WHERE KL_KODEVERK='BEHANDLING_STATUS' AND KL_KODE='AVSLU';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Fatter vedtak' WHERE KL_KODEVERK='BEHANDLING_STATUS' AND KL_KODE='FVED';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Iverksetter vedtak' WHERE KL_KODEVERK='BEHANDLING_STATUS' AND KL_KODE='IVED';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Opprettet' WHERE KL_KODEVERK='BEHANDLING_STATUS' AND KL_KODE='OPPRE';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Behandling utredes' WHERE KL_KODEVERK='BEHANDLING_STATUS' AND KL_KODE='UTRED';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Autopunkt' WHERE KL_KODEVERK='AKSJONSPUNKT_TYPE' AND KL_KODE='AUTO';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Manuell' WHERE KL_KODEVERK='AKSJONSPUNKT_TYPE' AND KL_KODE='MANU';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Overstyring' WHERE KL_KODEVERK='AKSJONSPUNKT_TYPE' AND KL_KODE='OVST';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Saksbehandleroverstyring' WHERE KL_KODEVERK='AKSJONSPUNKT_TYPE' AND KL_KODE='SAOV';