CREATE TABLE GRUNNLAG_OPPDATERT (
  ID NUMBER(19,0) NOT NULL,
  BEHANDLING_ID NUMBER(19,0) NOT NULL,
  OPPRETTET_AV VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  OPPRETTET_TID TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  ENDRET_AV VARCHAR2(20 CHAR),
  ENDRET_TID TIMESTAMP(3),
  CONSTRAINT PK_GRUNNLAG_OPPDATERT PRIMARY KEY (ID),
  CONSTRAINT FK_GRUNNLAG_OPPDATERT_1 FOREIGN KEY (BEHANDLING_ID) REFERENCES BEHANDLING (ID)
);

CREATE INDEX IDX_GRUNNLAG_OPPDATERT ON GRUNNLAG_OPPDATERT (BEHANDLING_ID);

CREATE SEQUENCE SEQ_GRUNNLAG_OPPDATERT MINVALUE 1 START WITH 1 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE GRUNNLAG_OPPDATERT IS 'Tilbakekrevingsgrunnlag for behandling';
COMMENT ON COLUMN GRUNNLAG_OPPDATERT.ID IS 'Primary key';
COMMENT ON COLUMN GRUNNLAG_OPPDATERT.BEHANDLING_ID IS 'FK: BEHANDLING fremmednøkkel for tilknyttet behandling';