CREATE TABLE FEILUTBETALING_AARSAK_DEF(
  ID                          NUMBER(19,0) NOT NULL ENABLE,
  AARSAK                      VARCHAR2(100 CHAR) NOT NULL ENABLE,
  OPPRETTET_AV                VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL ENABLE,
  OPPRETTET_TID               TIMESTAMP(3) DEFAULT systimestamp NOT NULL ENABLE,
  ENDRET_AV                   VARCHAR2(20 CHAR),
  ENDRET_TID                 TIMESTAMP (3)
  );

  CREATE SEQUENCE SEQ_FEILUTBETALING_AARSAK_DEF MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

  COMMENT ON TABLE  FEILUTBETALING_AARSAK_DEF  IS 'Tabell for å lagere hoveddefinisjon av feilutbetaling årsaker';
  COMMENT ON COLUMN FEILUTBETALING_AARSAK_DEF.ID IS 'Primary Key';
  COMMENT ON COLUMN FEILUTBETALING_AARSAK_DEF.AARSAK IS 'FK:Kodeverk';

  CREATE TABLE FEILUTBETALING_PERIODE_AARSAK(
  ID                          NUMBER(19,0) NOT NULL,
  BEHANDLING_ID               NUMBER(19,0) NOT NULL,
  AKTIV                       VARCHAR2(1) DEFAULT 'J' NOT NULL ,
  FOM                         DATE               NOT NULL ,
  TOM                         DATE               NOT NULL ,
  AARSAK                      VARCHAR2(100 CHAR) NOT NULL,
  UNDER_AARSAK                VARCHAR2(100 CHAR),
  OPPRETTET_AV                VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
  OPPRETTET_TID               TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  ENDRET_AV                   VARCHAR2(20 CHAR),
  ENDRET_TID                  TIMESTAMP (3)
  );

  CREATE SEQUENCE SEQ_FEILUTBET_PERIODE_AARSAK MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

  COMMENT ON TABLE  FEILUTBETALING_PERIODE_AARSAK  IS 'Tabell for å lagere feilutbetaling årsak og underårsak for hver perioder';
  COMMENT ON COLUMN FEILUTBETALING_PERIODE_AARSAK.ID IS 'Primary Key';
  COMMENT ON COLUMN FEILUTBETALING_PERIODE_AARSAK.BEHANDLING_ID IS 'FK:BEHANDLING';
  COMMENT ON COLUMN FEILUTBETALING_PERIODE_AARSAK.AKTIV IS 'Angir status av feilutbetaling årsak';
  COMMENT ON COLUMN FEILUTBETALING_PERIODE_AARSAK.FOM IS 'Første dag av feilutbetaling periode';
  COMMENT ON COLUMN FEILUTBETALING_PERIODE_AARSAK.TOM IS 'Siste dag av feilutbetaling periode';
  COMMENT ON COLUMN FEILUTBETALING_PERIODE_AARSAK.AARSAK IS 'Årsak av feilutbetaling periode';
  COMMENT ON COLUMN FEILUTBETALING_PERIODE_AARSAK.UNDER_AARSAK IS 'UnderÅrsak av feilutbetaling periode';

--------------------------------------------------------
  --  DDL for Index og Primary Key
  --------------------------------------------------------

ALTER TABLE FEILUTBETALING_AARSAK_DEF  ADD CONSTRAINT PK_FEILUTBETALING_AARSAK_DEF PRIMARY KEY (ID) ENABLE;

ALTER TABLE FEILUTBETALING_PERIODE_AARSAK  ADD CONSTRAINT PK_FEILUTBET_PERIODE_AARSAK PRIMARY KEY (ID) ENABLE;

CREATE INDEX IDX_FEILUTBET_AARSAK_DEF_1 ON FEILUTBETALING_AARSAK_DEF (AARSAK);

CREATE INDEX IDX_FEILUTBET_PERIODE_AARSAK_1 ON FEILUTBETALING_PERIODE_AARSAK (BEHANDLING_ID);

--------------------------------------------------------
--  Ref Constraints
--------------------------------------------------------

ALTER TABLE FEILUTBETALING_AARSAK_DEF ADD CONSTRAINT FK_FEILUTBETALING_AARSAK_DEF_1 FOREIGN KEY (AARSAK)
REFERENCES KODEVERK (KODE) ENABLE;

ALTER TABLE FEILUTBETALING_PERIODE_AARSAK ADD CONSTRAINT FK_FEILUTBET_PERIODE_AARSAK_1 FOREIGN KEY (BEHANDLING_ID)
REFERENCES BEHANDLING (ID) ENABLE;