INSERT INTO BEHANDLING_STEG_TYPE (KODE, NAVN, BEHANDLING_STATUS_DEF, BESKRIVELSE)
VALUES ('TBKGSTEG', 'Hent tilbakekrevingsgrunnlag', 'UTRED', 'Hente tilbakekrevingsgrunnlag for behandling');

INSERT INTO BEHANDLING_TYPE_STEG_SEKV (ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval, 'BT-007', 'TBKGSTEG', 60);

INSERT INTO VURDERINGSPUNKT_DEF (KODE, BEHANDLING_STEG, VURDERINGSPUNKT_TYPE, NAVN)
VALUES ('TBKGSTEG.INN', 'TBKGSTEG', 'INN', 'Tilbakekrevingsgrunnlag - Inngang');

INSERT INTO AKSJONSPUNKT_DEF (KODE, NAVN, VURDERINGSPUNKT, BESKRIVELSE, VILKAR_TYPE, TOTRINN_BEHANDLING_DEFAULT, AKSJONSPUNKT_TYPE, FRIST_PERIODE, TILBAKEHOPP_VED_GJENOPPTAKELSE, LAG_UTEN_HISTORIKK, SKJERMLENKE_TYPE )
VALUES ('7002', 'Venter på tilbakekrevingsgrunnlag fra økonomi', 'TBKGSTEG.INN', 'Venter på tilbakekrevingsgrunnlag fra økonomi', '-', 'N', 'AUTO', null, 'N', 'J', '-');

INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE)
VALUES (SEQ_KODELISTE.nextval, 'VENT_AARSAK', 'VENT_PÅ_TILBAKEKREVINGSGRUNNLAG', 'Venter på tilbakekrevingsgrunnlag fra økonomi', 'Venter på tilbakekrevingsgrunnlag fra økonomi');
