--medlemskap
update KODELISTE_NAVN_I18N set navn='Unntak medlemskap/medlem annet land' where kl_kodeverk='HENDELSE_UNDERTYPE' and kl_kode='MEDLEM_I_ANNET_LAND';

INSERT INTO KODELISTE_RELASJON (ID,KODEVERK1,KODE1,KODEVERK2,KODE2) VALUES (SEQ_KODELISTE_RELASJON.NEXTVAL,'FAGSAK_YTELSE','ES','HENDELSE_TYPE','MEDLEMSKAP');

update FEILUTBETALING_PERIODE_AARSAK set UNDER_AARSAK_KODEVERK='IKKE_LOVLIG_OPPHOLD' where UNDER_AARSAK_KODEVERK in ('ES_IKKE_LOVLIG_OPPHOLD');
update FEILUTBETALING_PERIODE_AARSAK set UNDER_AARSAK_KODEVERK='UTVANDRET' where UNDER_AARSAK_KODEVERK in ('ES_UTVANDRET');
update FEILUTBETALING_PERIODE_AARSAK set UNDER_AARSAK_KODEVERK='MEDLEM_I_ANNET_LAND' where UNDER_AARSAK_KODEVERK in ('ES_MEDLEMSKAP_UNNTAKK');
update FEILUTBETALING_PERIODE_AARSAK set UNDER_AARSAK_KODEVERK='IKKE_OPPHOLDSRETT_EØS' where UNDER_AARSAK_KODEVERK in ('ES_IKKE_OPPHOLDSRETT');
update FEILUTBETALING_PERIODE_AARSAK set UNDER_AARSAK_KODEVERK='IKKE_BOSATT' where UNDER_AARSAK_KODEVERK in ('ES_IKKE_BOSATT');
update FEILUTBETALING_PERIODE_AARSAK set AARSAK_KODEVERK = 'MEDLEMSKAP' where AARSAK_KODEVERK in ('ES_MEDLEMSKAP_TYPE');

delete KODELISTE_NAVN_I18N where kl_kodeverk='HENDELSE_UNDERTYPE' and kl_kode in (select kode2 from kodeliste_relasjon where kodeverk1='HENDELSE_TYPE' and kode1='ES_MEDLEMSKAP_TYPE' and kodeverk2='HENDELSE_UNDERTYPE');
delete kodeliste_relasjon where kodeverk1='HENDELSE_TYPE' and kode1='ES_MEDLEMSKAP_TYPE';
delete kodeliste where kodeverk='HENDELSE_UNDERTYPE' and kode not in (select kode2 from kodeliste_relasjon where kodeverk1='HENDELSE_TYPE');
delete kodeliste_relasjon where kodeverk1='FAGSAK_YTELSE' and kode1='ES' and kodeverk2='HENDELSE_TYPE' and kode2 = 'ES_MEDLEMSKAP_TYPE';
delete kodeliste_navn_i18n where kl_kodeverk='HENDELSE_TYPE' and kl_kode not in (select kode2 from kodeliste_relasjon where kodeverk1='FAGSAK_YTELSE');
delete kodeliste where kodeverk='HENDELSE_TYPE' and kode not in (select kode2 from kodeliste_relasjon where kodeverk1='FAGSAK_YTELSE');

--økonomi, annet
INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE) VALUES (seq_kodeliste.nextval,'HENDELSE_TYPE','OKONOMI_FEIL',null,'Feil i økonomi');
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN) VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HENDELSE_TYPE','OKONOMI_FEIL','NB','Feil i økonomi');

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,EKSTRA_DATA) VALUES (seq_kodeliste.nextval,'HENDELSE_UNDERTYPE','OKONOMI_FEIL_FERIEPENGER',null,'Feil feriepengeutbetaling', '5');
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN) VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HENDELSE_UNDERTYPE','OKONOMI_FEIL_FERIEPENGER','NB','Feil feriepengeutbetaling');

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,EKSTRA_DATA) VALUES (seq_kodeliste.nextval,'HENDELSE_UNDERTYPE','ØKONOMI_UTBETALT_FOR_MYE',null,'Feil i økonomi - utbetalt for mye', '1');
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN) VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HENDELSE_UNDERTYPE','ØKONOMI_UTBETALT_FOR_MYE','NB','Feil i økonomi - utbetalt for mye');

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,EKSTRA_DATA) VALUES (seq_kodeliste.nextval,'HENDELSE_UNDERTYPE','REFUSJON_ARBGIVER',null,'Refusjon til arbeidsgiver', '1');
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN) VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HENDELSE_UNDERTYPE','REFUSJON_ARBGIVER','NB','Refusjon til arbeidsgiver');

INSERT INTO KODELISTE_RELASJON (ID,KODEVERK1,KODE1,KODEVERK2,KODE2) VALUES (SEQ_KODELISTE_RELASJON.NEXTVAL,'FAGSAK_YTELSE','FP','HENDELSE_TYPE','OKONOMI_FEIL');
INSERT INTO KODELISTE_RELASJON (ID,KODEVERK1,KODE1,KODEVERK2,KODE2) VALUES (SEQ_KODELISTE_RELASJON.NEXTVAL,'FAGSAK_YTELSE','SVP','HENDELSE_TYPE','OKONOMI_FEIL');

INSERT INTO KODELISTE_RELASJON (ID,KODEVERK1,KODE1,KODEVERK2,KODE2) VALUES (SEQ_KODELISTE_RELASJON.NEXTVAL,'HENDELSE_TYPE','ES_ANNET_TYPE','HENDELSE_UNDERTYPE','ANNET_FRITEKST');
INSERT INTO KODELISTE_RELASJON (ID,KODEVERK1,KODE1,KODEVERK2,KODE2) VALUES (SEQ_KODELISTE_RELASJON.NEXTVAL,'HENDELSE_TYPE','SVP_ANNET_TYPE','HENDELSE_UNDERTYPE','ANNET_FRITEKST');
INSERT INTO KODELISTE_RELASJON (ID,KODEVERK1,KODE1,KODEVERK2,KODE2) VALUES (SEQ_KODELISTE_RELASJON.NEXTVAL,'HENDELSE_TYPE','ES_FEIL_UTBETALING_TYPE','HENDELSE_UNDERTYPE','ØKONOMI_UTBETALT_FOR_MYE');
INSERT INTO KODELISTE_RELASJON (ID,KODEVERK1,KODE1,KODEVERK2,KODE2) VALUES (SEQ_KODELISTE_RELASJON.NEXTVAL,'HENDELSE_TYPE','FP_ANNET_HENDELSE_TYPE','HENDELSE_UNDERTYPE','REFUSJON_ARBGIVER');
INSERT INTO KODELISTE_RELASJON (ID,KODEVERK1,KODE1,KODEVERK2,KODE2) VALUES (SEQ_KODELISTE_RELASJON.NEXTVAL,'HENDELSE_TYPE','SVP_ANNET_TYPE','HENDELSE_UNDERTYPE','REFUSJON_ARBGIVER');
INSERT INTO KODELISTE_RELASJON (ID,KODEVERK1,KODE1,KODEVERK2,KODE2) VALUES (SEQ_KODELISTE_RELASJON.NEXTVAL,'HENDELSE_TYPE','OKONOMI_FEIL','HENDELSE_UNDERTYPE','OKONOMI_FEIL_FERIEPENGER');
UPDATE KODELISTE_RELASJON set kode1='OKONOMI_FEIL' where kodeverk1='HENDELSE_TYPE' and kodeverk2='HENDELSE_UNDERTYPE' and kode2='OKONOMI_DOBBELUTBETALING';
UPDATE KODELISTE_RELASJON set kode1='OKONOMI_FEIL' where kodeverk1='HENDELSE_TYPE' and kodeverk2='HENDELSE_UNDERTYPE' and kode2='OKONOMI_UTBETALT';
UPDATE KODELISTE_RELASJON set kode1='OKONOMI_FEIL' where kodeverk1='HENDELSE_TYPE' and kodeverk2='HENDELSE_UNDERTYPE' and kode2='OKONOMI_FEIL_TREKK';
update kodeliste_navn_i18N set navn = 'Dobbeltutbetaling' where kl_kodeverk = 'HENDELSE_UNDERTYPE' and kl_kode = 'OKONOMI_DOBBELUTBETALING';
update kodeliste_navn_i18N set navn = 'Utbetalt for mye' where kl_kodeverk = 'HENDELSE_UNDERTYPE' and kl_kode = 'OKONOMI_UTBETALT';
update kodeliste_navn_i18N set navn = 'Feil trekk' where kl_kodeverk = 'HENDELSE_UNDERTYPE' and kl_kode = 'OKONOMI_FEIL_TREKK';

update FEILUTBETALING_PERIODE_AARSAK set AARSAK_KODEVERK = 'OKONOMI_FEIL' where UNDER_AARSAK in ('OKONOMI_DOBBELUTBETALING', 'OKONOMI_UTBETALT', 'OKONOMI_FEIL_TREKK');
