ALTER TABLE OKO_XML_MOTTATT ADD TILKOBLET VARCHAR2(1 CHAR);

comment on column OKO_XML_MOTTATT.TILKOBLET is 'Angir om mottatt xml er tilkoblet med en behandling';

UPDATE OKO_XML_MOTTATT mot SET TILKOBLET='N' WHERE mot.EKSTERN_BEHANDLING_ID NOT IN (SELECT EKSTERN_ID FROM EKSTERN_BEHANDLING);

UPDATE OKO_XML_MOTTATT mot SET TILKOBLET='J' WHERE mot.EKSTERN_BEHANDLING_ID IN (SELECT EKSTERN_ID FROM EKSTERN_BEHANDLING);
