-- KODEVERK
INSERT INTO KODEVERK (KODE,KODEVERK_EIER,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,SAMMENSATT)
VALUES ('TBK_OPPFYLT_VALG','VL','N','N','Tilbakekreving oppfylt','Kodeverk over tilbakekreving oppfylt valg for hver periode','VL',to_timestamp(sysdate,'DD.MM.RRRR'),null,null,'N');

INSERT INTO KODEVERK (KODE,KODEVERK_EIER,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,SAMMENSATT)
VALUES ('INNTEKTS_KATEGORI','VL','N','N','Inntekst kategory','Kodeverk over inntekts category','VL',to_timestamp(sysdate,'DD.MM.RRRR'),null,null,'N');

-- KODELISTE-TBK_OPPFYLT_VALG

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) VALUES (seq_kodeliste.nextval,'TBK_OPPFYLT_VALG','JA_MOTTAKER_FORSTAA',null,
'Mottaker forstår feilutbetaling',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (seq_kodeliste.nextval,'TBK_OPPFYLT_VALG','JA_MOTTAKER_UAKTSOMT_FEILAKTIGE_OPPLYSNINGER',null,'Mottaker forårsaket feilutbetalingen ved fortsett eller uaktsomt gitt feilaktige opplysninger',
to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (seq_kodeliste.nextval,'TBK_OPPFYLT_VALG','JA_MOTTAKER_UAKTSOMT_MANGELFULLE_OPPLYSNINGER',null,'Mottaker forårsaket feilutbetalingen ved fortsett eller uaktsomt gitt mangelfulle opplysninger',
to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (seq_kodeliste.nextval,'TBK_OPPFYLT_VALG','NEI_MOTTAKER_GOD_TRO',null,'Mottaker har mottat beløpet i god tro',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (seq_kodeliste.nextval,'TBK_OPPFYLT_VALG','-',null,'UDEFINERT',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

-- KODELISTE-KLASSE_KODE

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPADATORD',null,'FPADATORD',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPADATORD','NB','FPADATORD','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPADATFRI',null,'FPADATFRI',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPADATFRI','NB','FPADATFRI','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPADSND-OP',null,'FPADSND-OP',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPADSND-OP','NB','FPADSND-OP','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPADATAL',null,'FPADATAL',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPADATAL','NB','FPADATAL','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPADATSJO',null,'FPADATSJO',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPADATSJO','NB','FPADATSJO','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPADSNDDM-OP',null,'FPADSNDDM-OP',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPADSNDDM-OP','NB','FPADSNDDM-OP','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPADSNDJB-OP',null,'FPADSNDJB-OP',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPADSNDJB-OP','NB','FPADSNDJB-OP','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPADSNDFI',null,'FPADSNDFI',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPADSNDFI','NB','FPADSNDFI','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'KLASSE_KODE','FPATSJO',null,'FPATSJO',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'KLASSE_KODE','FPATSJO','NB','FPATSJO','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);


-- KODELISTE-INNTEKTS_KATEGORI

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'INNTEKTS_KATEGORI','FØDSEL',null,'Fødsel-ES',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'INNTEKTS_KATEGORI','FØDSEL','NB','Fødsel','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'INNTEKTS_KATEGORI','ADOPSJON',null,'Adopsjon-ES',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'INNTEKTS_KATEGORI','ADOPSJON','NB','Adopsjon','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'INNTEKTS_KATEGORI','ARBEIDSTAKER',null,'Arbeidstaker',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'INNTEKTS_KATEGORI','ARBEIDSTAKER','NB','Arbeidstaker','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'INNTEKTS_KATEGORI','FRILANSER',null,'Frilanser',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'INNTEKTS_KATEGORI','FRILANSER','NB','Frilanser','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'INNTEKTS_KATEGORI','SELVSTENDIG_NÆRINGSDRIVENDE',null,'Selvstendig Næringsdrivende',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'INNTEKTS_KATEGORI','SELVSTENDIG_NÆRINGSDRIVENDE','NB','Selvstendig Næringsdrivende','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'INNTEKTS_KATEGORI','ARBEIDSLEDIG',null,'Arbeidsledig',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'INNTEKTS_KATEGORI','ARBEIDSLEDIG','NB','Arbeidsledig','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'INNTEKTS_KATEGORI','SJØMANN',null,'Sjømann',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'INNTEKTS_KATEGORI','SJØMANN','NB','Sjømann','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'INNTEKTS_KATEGORI','DAGMAMMA',null,'Dagmamma',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'INNTEKTS_KATEGORI','DAGMAMMA','NB','Dagmamma','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'INNTEKTS_KATEGORI','JORDBRUKER',null,'Jordbruker',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'INNTEKTS_KATEGORI','JORDBRUKER','NB','Jordbruker','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'INNTEKTS_KATEGORI','FISKER',null,'Fisker',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'INNTEKTS_KATEGORI','FISKER','NB','Fisker','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'INNTEKTS_KATEGORI','FERIEPENGER_ARBEIDSTAKER',null,'Feriepenger arbeidstaker',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'INNTEKTS_KATEGORI','FERIEPENGER_ARBEIDSTAKER','NB','Feriepenger arbeidstaker','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

