INSERT INTO AKSJONSPUNKT_DEF (KODE, NAVN, VURDERINGSPUNKT, BESKRIVELSE, VILKAR_TYPE, TOTRINN_BEHANDLING_DEFAULT, AKSJONSPUNKT_TYPE, FRIST_PERIODE, TILBAKEHOPP_VED_GJENOPPTAKELSE, LAG_UTEN_HISTORIKK, SKJERMLENKE_TYPE )
VALUES ('5030', 'Avklar verge', 'FAKTFEILUTSTEG.INN', 'Avklar verge', '-', 'N', 'MANU', null, 'N', 'N', '-');

--historikkinnslag
UPDATE KODELISTE_NAVN_I18N SET NAVN='Fakta om verge/fullmektig' WHERE KL_KODEVERK='SKJERMLENKE_TYPE' AND KL_KODE='FAKTA_OM_VERGE';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Registering av opplysninger om verge/fullmektig' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='REGISTRER_OM_VERGE';
