CREATE TABLE VERGE
(
    ID              NUMBER(19,0) NOT NULL,
    AKTOER_ID VARCHAR2(50 char),
    GYLDIG_FOM      DATE NOT NULL,
    GYLDIG_TOM      DATE NOT NULL,
    VERGE_TYPE      VARCHAR2(100 CHAR) NOT NULL,
    ORGNR           VARCHAR2(100 char),
    NAVN            VARCHAR2(1000 char) NOT NULL,
    KILDE           VARCHAR2(50 char) NOT NULL,
    OPPRETTET_AV   VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
    OPPRETTET_TID  TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
    ENDRET_AV      VARCHAR2(20 CHAR),
    ENDRET_TID     TIMESTAMP(3),
    CONSTRAINT PK_VERGE PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_VERGE MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE VERGE is 'Informasjon om verge';
COMMENT ON COLUMN VERGE.ID is 'Primary Key';
COMMENT ON COLUMN VERGE.AKTOER_ID is 'AktørId av verge person';
COMMENT ON COLUMN VERGE.GYLDIG_FOM is 'Hvis fullmakt er begrenset i periode, dato for når fullmakten er gyldig fra';
COMMENT ON COLUMN VERGE.GYLDIG_TOM is 'Hvis fullmakt er begrenset i periode, dato for når fullmakten er gyldig til';
COMMENT ON COLUMN VERGE.VERGE_TYPE is 'Type verge';
COMMENT ON COLUMN VERGE.ORGNR is 'Vergens organisasjonsnummer';
COMMENT ON COLUMN VERGE.NAVN is 'Navn på vergen, som tastet inn av saksbehandler';
COMMENT ON COLUMN VERGE.KILDE is 'Opprinnelsen av verge.Enten Fpsak hvis det kopierte fra fpsak eller fptilbake';

CREATE TABLE GR_VERGE
(
    ID              NUMBER(19,0)      NOT NULL,
    BEHANDLING_ID   NUMBER(19,0)      NOT NULL,
    VERGE_ID        NUMBER(19,0)      NOT NULL,
    AKTIV           VARCHAR2(1 CHAR)  NOT NULL,
    OPPRETTET_AV    VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
    ENDRET_AV      VARCHAR2(20 CHAR),
    ENDRET_TID     TIMESTAMP(3),
    CONSTRAINT PK_GR_VERGE PRIMARY KEY (ID),
    CONSTRAINT FK_GR_VERGE_1 FOREIGN KEY (BEHANDLING_ID) REFERENCES BEHANDLING(ID),
    CONSTRAINT FK_GR_VERGE_2 FOREIGN KEY (VERGE_ID) REFERENCES VERGE(ID),
    CONSTRAINT CHK_AKTIV_VERGE CHECK (AKTIV IN ('J', 'N'))
);

CREATE SEQUENCE SEQ_GR_VERGE MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE  GR_VERGE is 'Aggregate tabell for å lagre verge';
COMMENT ON COLUMN GR_VERGE.ID is 'Primary Key';
COMMENT ON COLUMN GR_VERGE.VERGE_ID is 'FK:VERGE';
COMMENT ON COLUMN GR_VERGE.BEHANDLING_ID is 'FK: Referanse til behandling';
COMMENT ON COLUMN GR_VERGE.AKTIV is 'Angir status av verge';

CREATE INDEX IDX_GR_VERGE_1 ON GR_VERGE(BEHANDLING_ID);
CREATE INDEX IDX_GR_VERGE_2 ON GR_VERGE(VERGE_ID);
