delete from KODELISTE_NAVN_I18N where KL_KODEVERK='BEHANDLING_AARSAK' and KL_KODE not in ('RE_KLAGE_NFP', 'RE_KLAGE_KA', 'RE_VILKÅR', 'RE_FORELDELSE', '-');
delete from KODELISTE where KODEVERK='BEHANDLING_AARSAK' and KODE not in ('RE_KLAGE_NFP', 'RE_KLAGE_KA', 'RE_VILKÅR', 'RE_FORELDELSE', '-');
