ALTER TABLE BEHANDLING ADD AUTOMATISK_SAKSBEHANDLET VARCHAR2(1 BYTE);

COMMENT ON COLUMN BEHANDLING.AUTOMATISK_SAKSBEHANDLET is 'Angir om behandlingen saksbehandlet automatisk. ';

UPDATE BEHANDLING SET AUTOMATISK_SAKSBEHANDLET='N';

ALTER TABLE BEHANDLING MODIFY AUTOMATISK_SAKSBEHANDLET NOT NULL ENABLE;
