INSERT INTO BREV_SPORING(ID, BEHANDLING_ID, JOURNALPOST_ID, DOKUMENT_ID,BREV_TYPE)
SELECT SEQ_BREV_SPORING.NEXTVAL,BEHANDLING_ID, JOURNALPOST_ID, DOKUMENT_ID,'VARSEL' FROM VARSELBREV_SPORING;

INSERT INTO BREV_SPORING(ID, BEHANDLING_ID, JOURNALPOST_ID, DOKUMENT_ID,BREV_TYPE)
SELECT SEQ_BREV_SPORING.NEXTVAL,BEHANDLING_ID, JOURNALPOST_ID, DOKUMENT_ID,'VEDTAK' FROM VEDTAKSBREV_SPORING;
