INSERT INTO BEHANDLING_STEG_TYPE (KODE, NAVN, BEHANDLING_STATUS_DEF, BESKRIVELSE)
VALUES ('FAKTFEILUTSTEG', 'Fakta om Feilutbetaling', 'UTRED', 'Lagre fakta om feilutbetaling');

INSERT INTO BEHANDLING_TYPE_STEG_SEKV (ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval, 'BT-007', 'FAKTFEILUTSTEG', 70);

INSERT INTO VURDERINGSPUNKT_DEF (KODE, BEHANDLING_STEG, VURDERINGSPUNKT_TYPE, NAVN)
VALUES ('FAKTFEILUTSTEG.INN', 'FAKTFEILUTSTEG', 'INN', 'Faktafeilutbetaling - Inngang');

INSERT INTO VURDERINGSPUNKT_DEF (KODE, BEHANDLING_STEG, VURDERINGSPUNKT_TYPE, NAVN)
VALUES ('FAKTFEILUTSTEG.UT', 'FAKTFEILUTSTEG', 'UT', 'Faktafeilutbetaling - Utgang');

INSERT INTO AKSJONSPUNKT_DEF (KODE, NAVN, VURDERINGSPUNKT, BESKRIVELSE, VILKAR_TYPE, TOTRINN_BEHANDLING_DEFAULT, AKSJONSPUNKT_TYPE, FRIST_PERIODE, TILBAKEHOPP_VED_GJENOPPTAKELSE, LAG_UTEN_HISTORIKK, SKJERMLENKE_TYPE )
VALUES ('7003', 'Avklart fakta for feilutbetaling', 'FAKTFEILUTSTEG.UT', 'Avklart fakta for feilutbetaling', '-', 'N', 'MANU', null, 'N', 'N', '-');