ALTER TABLE AKSJONSPUNKT drop CONSTRAINT FK_AKSJONSPUNKT_5;
ALTER TABLE AKSJONSPUNKT drop CONSTRAINT FK_AKSJONSPUNKT_6;
ALTER TABLE AKSJONSPUNKT drop CONSTRAINT FK_AKSJONSPUNKT_7;

ALTER TABLE AKSJONSPUNKT_DEF drop CONSTRAINT FK_AKSJONSPUNKT_DEF_2;
ALTER TABLE AKSJONSPUNKT_DEF drop CONSTRAINT FK_AKSJONSPUNKT_DEF_3;
ALTER TABLE AKSJONSPUNKT_DEF drop CONSTRAINT FK_AKSJONSPUNKT_DEF_4;

ALTER TABLE BEHANDLING drop CONSTRAINT FK_BEHANDLING_2;
ALTER TABLE BEHANDLING drop CONSTRAINT FK_BEHANDLING_3;

ALTER TABLE BEHANDLING_STEG_TILSTAND drop CONSTRAINT FK_BEHANDLING_STEG_TILSTAND_80;

ALTER TABLE BEHANDLING_TYPE_STEG_SEKV drop CONSTRAINT FK_BEHANDLING_TYPE_STEG_SEK_2;

ALTER TABLE BEHANDLING_VEDTAK drop CONSTRAINT FK_BEHANDLING_VEDTAK_2 ;

ALTER TABLE FAGSAK drop CONSTRAINT FK_FAGSAK_2;

ALTER TABLE FORELDELSE_PERIODE drop CONSTRAINT FK_FORELDELSE_PERIODE_2;

ALTER TABLE HISTORIKKINNSLAG drop CONSTRAINT FK_HISTORIKKINNSLAG_2;
ALTER TABLE HISTORIKKINNSLAG drop CONSTRAINT FK_HISTORIKKINNSLAG_4;

ALTER TABLE KONFIG_VERDI drop CONSTRAINT FK_KONFIG_VERDI_1;

ALTER TABLE KONFIG_VERDI_KODE drop CONSTRAINT FK_KONFIG_VERDI_KODE_82;
ALTER TABLE KONFIG_VERDI_KODE drop CONSTRAINT FK_KONFIG_VERDI_KODE_83;

ALTER TABLE KRAV_GRUNNLAG_431 drop CONSTRAINT FK_KRAV_GRUNNLAG_431_1;
ALTER TABLE KRAV_GRUNNLAG_431 drop CONSTRAINT FK_KRAV_GRUNNLAG_431_3;
ALTER TABLE KRAV_GRUNNLAG_431 drop CONSTRAINT FK_KRAV_GRUNNLAG_431_4;

ALTER TABLE KRAV_GRUNNLAG_BELOP_433 drop CONSTRAINT FK_KRAV_GRUNNLAG_BELOP_433_2;

ALTER TABLE KRAV_VEDTAK_STATUS_437 drop CONSTRAINT FK_KRAV_VEDTAK_STATUS_437_1;
ALTER TABLE KRAV_VEDTAK_STATUS_437 drop CONSTRAINT FK_KRAV_VEDTAK_STATUS_437_3;

ALTER TABLE OKO_XML_SENDT drop CONSTRAINT FK_OKO_XML_SENDT_2;

ALTER TABLE VERGE drop CONSTRAINT FK_VERGE_1;

ALTER TABLE VILKAAR_AKTSOMHET drop CONSTRAINT FK_VILKAAR_AKTSOMHET_2;

ALTER TABLE VILKAAR_PERIODE drop CONSTRAINT FK_VILKAAR_PERIODE_2;
ALTER TABLE VILKAAR_PERIODE drop CONSTRAINT FK_VILKAAR_PERIODE_3;

ALTER TABLE VILKAAR_SAERLIG_GRUNN drop CONSTRAINT FK_VILKAAR_SAERLIG_GRUNN_2;

ALTER TABLE VURDER_PAA_NYTT_AARSAK drop CONSTRAINT FK_VURDER_PAA_NYTT_AARSAK_2;

ALTER TABLE VURDER_AARSAK_TTVURDERING drop CONSTRAINT FK_VURDER_AARSAK_TTVURDERING_2;


























