UPDATE PROSESS_TASK_TYPE SET NAVN='Slett mottatt xml', BESKRIVELSE='Sletter mottat XML fra økonomi etter at den er lagret i fptilbake sin domenestruktur' WHERE KODE='kravgrunnlag.slett.midlertidig.lagret.xml';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Henlagt, søknaden er feilopprettet' WHERE KL_KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KL_KODE='HENLAGT_FEILOPPRETTET';

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM) values (seq_kodeliste.nextval,'BEHANDLING_RESULTAT_TYPE','HENLAGT_KRAVGRUNNLAG_NULLSTILT',null,
'Søknaden er henlagt pga nullstilt kravgrunnlag melding fra økonomi',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_RESULTAT_TYPE','HENLAGT_KRAVGRUNNLAG_NULLSTILT','NB','Kravgrunnlaget er nullstilt','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KL_KODE='HENLAGT_SØKNAD_TRUKKET';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KL_KODE='HENLAGT_BRUKER_DØD';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KL_KODE='MERGET_OG_HENLAGT';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KL_KODE='HENLAGT_SØKNAD_MANGLER';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KL_KODE='HENLAGT_KLAGE_TRUKKET';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KL_KODE='HENLAGT_INNSYN_TRUKKET';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KL_KODE='MANGLER_BEREGNINGSREGLER';

DELETE FROM KODELISTE WHERE KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KODE='HENLAGT_SØKNAD_TRUKKET';
DELETE FROM KODELISTE WHERE KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KODE='HENLAGT_BRUKER_DØD';
DELETE FROM KODELISTE WHERE KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KODE='MERGET_OG_HENLAGT';
DELETE FROM KODELISTE WHERE KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KODE='HENLAGT_SØKNAD_MANGLER';
DELETE FROM KODELISTE WHERE KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KODE='HENLAGT_KLAGE_TRUKKET';
DELETE FROM KODELISTE WHERE KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KODE='HENLAGT_INNSYN_TRUKKET';
DELETE FROM KODELISTE WHERE KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KODE='MANGLER_BEREGNINGSREGLER';




