INSERT INTO FEILUTBETALING_AARSAK_DEF (ID,AARSAK,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_FEILUTBETALING_AARSAK_DEF.NEXTVAL,'UTSETTELSE_AARSAK_TYPE','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO FEILUTBETALING_AARSAK_DEF (ID,AARSAK,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_FEILUTBETALING_AARSAK_DEF.NEXTVAL,'MEDLEMSKAP_VILKAARET_TYPE','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO FEILUTBETALING_AARSAK_DEF (ID,AARSAK,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_FEILUTBETALING_AARSAK_DEF.NEXTVAL,'UTTAK_KVOTE','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO FEILUTBETALING_AARSAK_DEF (ID,AARSAK,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_FEILUTBETALING_AARSAK_DEF.NEXTVAL,'BEREGNINGSGRUNNLAG_TILSTAND','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO FEILUTBETALING_AARSAK_DEF (ID,AARSAK,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_FEILUTBETALING_AARSAK_DEF.NEXTVAL,'STONAD_PERIODE','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO FEILUTBETALING_AARSAK_DEF (ID,AARSAK,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_FEILUTBETALING_AARSAK_DEF.NEXTVAL,'OPPTJENING_TYPE','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO FEILUTBETALING_AARSAK_DEF (ID,AARSAK,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_FEILUTBETALING_AARSAK_DEF.NEXTVAL,'MORS_AKTIVITET_KRAV','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO FEILUTBETALING_AARSAK_DEF (ID,AARSAK,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_FEILUTBETALING_AARSAK_DEF.NEXTVAL,'OMSORG_TYPE','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO FEILUTBETALING_AARSAK_DEF (ID,AARSAK,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_FEILUTBETALING_AARSAK_DEF.NEXTVAL,'FORELDES_UTTAK','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO FEILUTBETALING_AARSAK_DEF (ID,AARSAK,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_FEILUTBETALING_AARSAK_DEF.NEXTVAL,'BARN_ALDER','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO FEILUTBETALING_AARSAK_DEF (ID,AARSAK,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_FEILUTBETALING_AARSAK_DEF.NEXTVAL,'OPPHOR_AARSAK_TYPE','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO FEILUTBETALING_AARSAK_DEF (ID,AARSAK,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_FEILUTBETALING_AARSAK_DEF.NEXTVAL,'RETT_TYPE','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO FEILUTBETALING_AARSAK_DEF (ID,AARSAK,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_FEILUTBETALING_AARSAK_DEF.NEXTVAL,'UTBETALING_SYSTEM_FEIL_TYPE','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO FEILUTBETALING_AARSAK_DEF (ID,AARSAK,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_FEILUTBETALING_AARSAK_DEF.NEXTVAL,'GRADERING_AARSAK_TYPE','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO FEILUTBETALING_AARSAK_DEF (ID,AARSAK,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_FEILUTBETALING_AARSAK_DEF.NEXTVAL,'ANNET_AARSAK_TYPE','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);