UPDATE KODELISTE SET BESKRIVELSE='Verge for barn under 18 år' WHERE KODEVERK='VERGE_TYPE' AND KODE='BARN';
UPDATE KODELISTE SET BESKRIVELSE='Verge for foreldreløst barn under 18 år' WHERE KODEVERK='VERGE_TYPE' AND KODE='FBARN';
UPDATE KODELISTE SET BESKRIVELSE='Verge for voksen' WHERE KODEVERK='VERGE_TYPE' AND KODE='VOKSEN';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Verge for barn under 18 år' WHERE KL_KODEVERK='VERGE_TYPE' AND KL_KODE='BARN';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Verge for foreldreløst barn under 18 år' WHERE KL_KODEVERK='VERGE_TYPE' AND KL_KODE='FBARN';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Verge for voksen' WHERE KL_KODEVERK='VERGE_TYPE' AND KL_KODE='VOKSEN';

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'VERGE_TYPE','ADVOKAT',null,'Advokat/advokatfullmektig',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'VERGE_TYPE','ANNEN_F',null,'Annen fullmektig',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'VERGE_TYPE','ADVOKAT','NB','Advokat/advokatfullmektig','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'VERGE_TYPE','ANNEN_F','NB','Annen fullmektig','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

ALTER TABLE VERGE ADD BEGRUNNELSE VARCHAR2(4000 CHAR);
COMMENT ON COLUMN VERGE.BEGRUNNELSE IS 'Begrunnelse for verge';

ALTER TABLE VERGE ADD KL_VERGE_TYPE VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('VERGE_TYPE') VIRTUAL VISIBLE;
COMMENT ON COLUMN VERGE.KL_VERGE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';

ALTER TABLE VERGE ADD CONSTRAINT FK_VERGE_1 FOREIGN KEY (VERGE_TYPE, KL_VERGE_TYPE) REFERENCES KODELISTE (KODE, KODEVERK) ENABLE;

CREATE INDEX IDX_VERGE_1 ON VERGE (VERGE_TYPE, KL_VERGE_TYPE);
