ALTER TABLE BEHANDLING_VEDTAK DROP CONSTRAINT FK_BEHANDLING_VEDTAK_3;
ALTER TABLE BEHANDLING_VEDTAK DROP COLUMN KL_VEDTAK_RESULTAT_TYPE;
ALTER TABLE BEHANDLING_VEDTAK DROP COLUMN VEDTAK_RESULTAT_TYPE;
