DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='FAGSAK_YTELSE' and KODE1='SVP' and KODEVERK2='HENDELSE_TYPE' and KODE2='SVP_ARBEIDSFORHOLD_TYPE';
DELETE FROM KODELISTE_RELASJON WHERE KODEVERK1='HENDELSE_TYPE' and KODE1='SVP_ARBEIDSFORHOLD_TYPE';

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='HENDELSE_TYPE' and KL_KODE='SVP_ARBEIDSFORHOLD_TYPE';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='HENDELSE_UNDERTYPE' and KL_KODE='MANGLER_ARBEIDSFORHOLD';

DELETE FROM KODELISTE WHERE KODEVERK='HENDELSE_TYPE' and KODE='SVP_ARBEIDSFORHOLD_TYPE';
DELETE FROM KODELISTE WHERE KODEVERK='HENDELSE_UNDERTYPE' and KODE='MANGLER_ARBEIDSFORHOLD';
