-- fjernet ubrukt KODELISTE_NAVN_I18N for VENT_ÅRSAK

DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='VENT_AARSAK' AND KL_KODE='AVV_FODSEL';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='VENT_AARSAK' AND KL_KODE='UTV_FRIST';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='VENT_AARSAK' AND KL_KODE='FOR_TIDLIG_SOKNAD';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='VENT_AARSAK' AND KL_KODE='OPPD_ÅPEN_BEH';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='VENT_AARSAK' AND KL_KODE='VENT_OPDT_INNTEKTSMELDING';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='VENT_AARSAK' AND KL_KODE='AVV_RESPONS_REVURDERING';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='VENT_AARSAK' AND KL_KODE='VENT_REGISTERINNHENTING';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='VENT_AARSAK' AND KL_KODE='VENT_TIDLIGERE_BEHANDLING';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='VENT_AARSAK' AND KL_KODE='VENT_INFOTRYGD';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='VENT_AARSAK' AND KL_KODE='VENT_ÅPEN_BEHANDLING';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='VENT_AARSAK' AND KL_KODE='VENT_OPPTJENING_OPPLYSNINGER';
DELETE FROM KODELISTE_NAVN_I18N WHERE KL_KODEVERK='VENT_AARSAK' AND KL_KODE='VENT_INNTEKT_RAPPORTERINGSFRIST';

-- fjernet ubrukt KODELISTE for VENT_ÅRSAK

DELETE FROM KODELISTE WHERE KODEVERK='VENT_AARSAK' AND KODE='AVV_FODSEL';
DELETE FROM KODELISTE WHERE KODEVERK='VENT_AARSAK' AND KODE='UTV_FRIST';
DELETE FROM KODELISTE WHERE KODEVERK='VENT_AARSAK' AND KODE='FOR_TIDLIG_SOKNAD';
DELETE FROM KODELISTE WHERE KODEVERK='VENT_AARSAK' AND KODE='OPPD_ÅPEN_BEH';
DELETE FROM KODELISTE WHERE KODEVERK='VENT_AARSAK' AND KODE='VENT_OPDT_INNTEKTSMELDING';
DELETE FROM KODELISTE WHERE KODEVERK='VENT_AARSAK' AND KODE='AVV_RESPONS_REVURDERING';
DELETE FROM KODELISTE WHERE KODEVERK='VENT_AARSAK' AND KODE='VENT_REGISTERINNHENTING';
DELETE FROM KODELISTE WHERE KODEVERK='VENT_AARSAK' AND KODE='VENT_TIDLIGERE_BEHANDLING';
DELETE FROM KODELISTE WHERE KODEVERK='VENT_AARSAK' AND KODE='VENT_INFOTRYGD';
DELETE FROM KODELISTE WHERE KODEVERK='VENT_AARSAK' AND KODE='VENT_ÅPEN_BEHANDLING';
DELETE FROM KODELISTE WHERE KODEVERK='VENT_AARSAK' AND KODE='VENT_OPPTJENING_OPPLYSNINGER';
DELETE FROM KODELISTE WHERE KODEVERK='VENT_AARSAK' AND KODE='VENT_INNTEKT_RAPPORTERINGSFRIST';

--lag ny KODELISTE og KODELISTE_NAVN_I18N for VENT_ÅRSAK

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'VENT_AARSAK','UTV_TIL_FRIST',null,'Utvidet tilsvarsfrist',to_date('01.01.2000','DD.MM.RRRR'),
to_date('31.12.9999','DD.MM.RRRR'),'VL',to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'VENT_AARSAK','UTV_TIL_FRIST','NB','Utvidet tilsvarsfrist','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'VENT_AARSAK','VENT_PÅ_ØKONOMI',null,'Venter på økonomiløsningen',to_date('01.01.2000','DD.MM.RRRR'),
to_date('31.12.9999','DD.MM.RRRR'),'VL',to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'VENT_AARSAK','VENT_PÅ_ØKONOMI','NB','Venter på økonomiløsningen','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'VENT_AARSAK','ENDRE_TILKJENT_YTELSE',null,'Mulig endring i tilkjent ytelse',to_date('01.01.2000','DD.MM.RRRR'),
to_date('31.12.9999','DD.MM.RRRR'),'VL',to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'VENT_AARSAK','ENDRE_TILKJENT_YTELSE','NB','Mulig endring i tilkjent ytelse','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

-- oppdatere navn av eksisterte kodeliste

UPDATE KODELISTE_NAVN_I18N SET NAVN='Venter på scanning' WHERE KL_KODEVERK='VENT_AARSAK' AND KL_KODE='SCANN';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Avventer dokumentasjon' WHERE KL_KODEVERK='VENT_AARSAK' AND KL_KODE='AVV_DOK';

