alter table GR_FEILUTBETALING rename to GR_FAKTA_FEILUTBETALING;
alter table FEILUTBETALING rename to FAKTA_FEILUTBETALING;
alter table FEILUTBETALING_PERIODE_AARSAK rename to FAKTA_FEILUTBETALING_PERIODE;
rename SEQ_FEILUTBETALING to SEQ_FAKTA_FEILUTBETALING;
rename SEQ_FEILUTBET_PERIODE_AARSAK to SEQ_FAKTA_FEILUTB_PERIODE;
rename SEQ_GR_FEILUTBETALING to SEQ_GR_FAKTA_FEILUTBETALING;
drop sequence SEQ_FEILUTBETALING_AARSAK_DEF;
alter table FAKTA_FEILUTBETALING rename constraint PK_FEILUTBETALING to PK_FAKTA_FEILUTBETALING;
alter table FAKTA_FEILUTBETALING_PERIODE rename constraint PK_FEILUTBET_PERIODE_AARSAK to PK_FAKTA_FEILUTB_PERIODE;
alter table FAKTA_FEILUTBETALING_PERIODE rename constraint FK_FEILUTBET_PERIODE_AARSAK_2 to FK_FAKTA_FEILUTB_PERIODE_1;
alter table GR_FAKTA_FEILUTBETALING rename constraint CHK_AKTIV_FEILUTBETALING to CHK_GR_FAKTA_FEILUTB_AKTIV;
alter table GR_FAKTA_FEILUTBETALING rename constraint FK_GR_FEILUTBETALING_1 to FK_GR_FAKTA_FEILUTB_1;
alter table GR_FAKTA_FEILUTBETALING rename constraint FK_GR_FEILUTBETALING_2 to FK_GR_FAKTA_FEILUTB_2;
alter table GR_FAKTA_FEILUTBETALING rename constraint PK_GR_FEILUTBETALING to PK_GR_FAKTA_FEILUTBETALING;

alter table GR_FAKTA_FEILUTBETALING rename column FEILUTBETALING_ID to FAKTA_FEILUTBETALING_ID;
alter table FAKTA_FEILUTBETALING_PERIODE rename column FEILUTBETALING_ID to FAKTA_FEILUTBETALING_ID;

alter table FAKTA_FEILUTBETALING_PERIODE rename column AARSAK to HENDELSE_TYPE;
alter table FAKTA_FEILUTBETALING_PERIODE drop column AARSAK_KODEVERK;
ALTER TABLE FAKTA_FEILUTBETALING_PERIODE ADD (KL_HENDELSE_TYPE VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('HENDELSE_TYPE') VIRTUAL  NOT NULL);
alter table FAKTA_FEILUTBETALING_PERIODE rename column UNDER_AARSAK to HENDELSE_UNDERTYPE;
alter table FAKTA_FEILUTBETALING_PERIODE drop column UNDER_AARSAK_KODEVERK;
ALTER TABLE FAKTA_FEILUTBETALING_PERIODE ADD (KL_HENDELSE_UNDERTYPE VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('HENDELSE_UNDERTYPE') VIRTUAL  NOT NULL);

alter index IDX_GR_FEILUTBETALING_1 rename to IDX_GR_FAKTA_FEILUTB_1;
alter index IDX_GR_FEILUTBETALING_2 rename to IDX_GR_FAKTA_FEILUTB_2;
alter index PK_GR_FEILUTBETALING rename to PK_GR_FAKTA_FEILUTBETALING;
alter index PK_FEILUTBET_PERIODE_AARSAK rename to PK_FAKTA_FEILUTB_PERIODE;
alter index PK_FEILUTBETALING rename to PK_FAKTA_FEILUTBETALING;

comment on column FAKTA_FEILUTBETALING_PERIODE.HENDELSE_TYPE is 'Hendelse som er årsak til feilutbetalingen';
comment on column FAKTA_FEILUTBETALING_PERIODE.HENDELSE_UNDERTYPE is 'Hendelse som er årsak til feilutbetalingen (underårsak)';
comment on column FAKTA_FEILUTBETALING_PERIODE.KL_HENDELSE_TYPE is 'Kodeverk for HENDELSE_TYPE';
comment on column FAKTA_FEILUTBETALING_PERIODE.KL_HENDELSE_UNDERTYPE is 'Kodeverk for HENDELSE_UNDERTYPE';

