CREATE TABLE VERGE
(
    ID              NUMBER(19,0) NOT NULL,
    BRUKER_ID       NUMBER(19,0),
    GYLDIG_FOM      DATE,
    GYLDIG_TOM      DATE,
    VERGE_TYPE      VARCHAR2(100 CHAR) NOT NULL,
    ORGANISASJON_ID NUMBER(19,0),
    OPPRETTET_AV   VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
    OPPRETTET_TID  TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
    ENDRET_AV      VARCHAR2(20 CHAR),
    ENDRET_TID     TIMESTAMP(3),
    CONSTRAINT PK_VERGE PRIMARY KEY (ID),
    CONSTRAINT FK_VERGE_1 FOREIGN KEY(BRUKER_ID) REFERENCES BRUKER (ID) ENABLE
);

CREATE SEQUENCE SEQ_VERGE MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE VERGE IS 'Informasjon om verge';
COMMENT ON COLUMN VERGE.ID is 'Primary Key';
COMMENT ON COLUMN VERGE.BRUKER_ID IS 'FK:BRUKER Fremmednøkkel til brukertabellen';
COMMENT ON COLUMN VERGE.GYLDIG_FOM IS 'Hvis fullmakt er begrenset i periode, dato for når fullmakten er gyldig fra';
COMMENT ON COLUMN VERGE.GYLDIG_TOM IS 'Hvis fullmakt er begrenset i periode, dato for når fullmakten er gyldig til';
COMMENT ON COLUMN VERGE.VERGE_TYPE IS 'Type verge';
COMMENT ON COLUMN VERGE.ORGANISASJON_ID IS 'FK:VERGE_ORGANISASJON Fremmednøkkel hvis verge er en organisasjon';

--------------------------------------------------------
--  DDL for Index og Primary Key
--------------------------------------------------------
CREATE INDEX IDX_VERGE_1 on VERGE (BRUKER_ID);
CREATE INDEX IDX_VERGE_2 on VERGE (VERGE_TYPE);
CREATE INDEX IDX_VERGE_3 on VERGE (ORGANISASJON_ID);

CREATE TABLE VERGE_ORGANISASJON
(
    ID             NUMBER(19,0)  NOT NULL,
    ORGNR          VARCHAR2(100 char)  NOT NULL,
    NAVN           VARCHAR2(1000 char),
    OPPRETTET_AV   VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
    OPPRETTET_TID  TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
    ENDRET_AV      VARCHAR2(20 CHAR),
    ENDRET_TID     TIMESTAMP(3),
    CONSTRAINT PK_VERGE_ORGANISASJON PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_VERGE_ORGANISASJON MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE  VERGE_ORGANISASJON IS 'En organisasjon som fungerer som verge for en bruker';
COMMENT ON COLUMN VERGE_ORGANISASJON.ORGNR IS 'Vergens organisasjonsnummer';
COMMENT ON COLUMN VERGE_ORGANISASJON.NAVN IS 'Navn på vergen, som tastet inn av saksbehandler';

--------------------------------------------------------
--  EKSTERN_BEHANDLING
--------------------------------------------------------
ALTER TABLE EKSTERN_BEHANDLING ADD VERGE_ID NUMBER(19,0);
COMMENT ON COLUMN EKSTERN_BEHANDLING.VERGE_ID IS 'FK:VERGE Fremmednøkkel til Verge tabellen';
CREATE INDEX IDX_EKSTERN_BEHANDLING_4 on EKSTERN_BEHANDLING (VERGE_ID);

--------------------------------------------------------
--  Ref Constraints for Tabeller
--------------------------------------------------------
ALTER TABLE VERGE ADD CONSTRAINT FK_VERGE_2 FOREIGN KEY (ORGANISASJON_ID) REFERENCES VERGE_ORGANISASJON(ID) ENABLE;

ALTER TABLE EKSTERN_BEHANDLING ADD CONSTRAINT FK_EKSTERN_BEHANDLING_2 FOREIGN KEY (VERGE_ID) REFERENCES VERGE(ID) ENABLE;
