INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE, GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL,'FRITEKST_TYPE','SAERLIGE_GRUNNER_ANNET_AVSNITT',null, 'Ekstra fritekst i vedtaksbrevet når særlig grunn annet er valgt',        to_date('01.01.2000','DD.MM.RRRR'));
