--------------------------------------------------------
--  DDL for Table HISTORIKKINNSLAG
--------------------------------------------------------

CREATE TABLE HISTORIKKINNSLAG (
   ID NUMBER(19,0) NOT NULL,
   TEKST VARCHAR2(2000 CHAR),
   BEHANDLING_ID NUMBER(19,0),
   HISTORIKK_AKTOER_ID VARCHAR2(100 CHAR) NOT NULL,
   HISTORIKKINNSLAG_TYPE VARCHAR2(100 CHAR) NOT NULL,
   OPPRETTET_AV VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL,
   OPPRETTET_TID TIMESTAMP (3) DEFAULT systimestamp NOT NULL,
   ENDRET_AV VARCHAR2(20 CHAR),
   ENDRET_TID TIMESTAMP (3),
   KL_HISTORIKK_AKTOER VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('HISTORIKK_AKTOER') VIRTUAL VISIBLE NOT NULL,
   FAGSAK_ID NUMBER(19,0) NOT NULL,
   BRUKER_KJOENN VARCHAR2(100 CHAR) NOT NULL,
   KL_BRUKER_KJOENN VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('BRUKER_KJOENN') VIRTUAL VISIBLE NOT NULL,
   KL_HISTORIKKINNSLAG_TYPE VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('HISTORIKKINNSLAG_TYPE') VIRTUAL VISIBLE NOT NULL,
  CONSTRAINT PK_HISTORIKKINNSLAG PRIMARY KEY (ID)
);

CREATE INDEX IDX_HISTORIKKINNSLAG_02 ON HISTORIKKINNSLAG (BRUKER_KJOENN);
CREATE INDEX IDX_HISTORIKKINNSLAG_03 ON HISTORIKKINNSLAG (HISTORIKKINNSLAG_TYPE);
CREATE INDEX IDX_HISTORIKKINNSLAG_6 ON HISTORIKKINNSLAG (FAGSAK_ID);
CREATE INDEX IDX_HISTORIKKINNSLAG_7 ON HISTORIKKINNSLAG (HISTORIKK_AKTOER_ID);
CREATE INDEX IDX_HISTORIKKINNSLAG_01 ON HISTORIKKINNSLAG (BEHANDLING_ID);

ALTER TABLE HISTORIKKINNSLAG ADD CONSTRAINT FK_BEHANDLING_ID FOREIGN KEY (BEHANDLING_ID) REFERENCES BEHANDLING (ID) ENABLE;
ALTER TABLE HISTORIKKINNSLAG ADD CONSTRAINT FK_HISTORIKKINNSLAG_3 FOREIGN KEY (FAGSAK_ID) REFERENCES FAGSAK (ID) ENABLE;
ALTER TABLE HISTORIKKINNSLAG ADD CONSTRAINT FK_HISTORIKKINNSLAG_4 FOREIGN KEY (BRUKER_KJOENN, KL_BRUKER_KJOENN) REFERENCES KODELISTE (KODE, KODEVERK) ENABLE;
ALTER TABLE HISTORIKKINNSLAG ADD CONSTRAINT FK_HISTORIKKINNSLAG_5 FOREIGN KEY (HISTORIKKINNSLAG_TYPE, KL_HISTORIKKINNSLAG_TYPE) REFERENCES KODELISTE (KODE, KODEVERK) ENABLE;
ALTER TABLE HISTORIKKINNSLAG ADD CONSTRAINT FK_HISTORIKKINNSLAG_80 FOREIGN KEY (HISTORIKK_AKTOER_ID, KL_HISTORIKK_AKTOER) REFERENCES KODELISTE (KODE, KODEVERK) ENABLE;

COMMENT ON COLUMN HISTORIKKINNSLAG.ID IS 'Primary Key';
COMMENT ON COLUMN HISTORIKKINNSLAG.TEKST IS 'Tekst som beskriver hendelsen (som skal vises i historikkfanen)';
COMMENT ON COLUMN HISTORIKKINNSLAG.BEHANDLING_ID IS 'FK: BEHANDLING Fremmednøkkel for kobling til behandling';
COMMENT ON COLUMN HISTORIKKINNSLAG.HISTORIKK_AKTOER_ID IS 'FK:HISTORIKK_AKTOER Fremmednøkkel til';
COMMENT ON COLUMN HISTORIKKINNSLAG.HISTORIKKINNSLAG_TYPE IS 'Fremmednøkkel til beskrivelse av historikkinnslaget';
COMMENT ON COLUMN HISTORIKKINNSLAG.KL_HISTORIKK_AKTOER IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN HISTORIKKINNSLAG.FAGSAK_ID IS 'FK:FAGSAK Fremmednøkkel for kobling til fagsak';
COMMENT ON COLUMN HISTORIKKINNSLAG.BRUKER_KJOENN IS 'FK:BRUKER_KJOENN Fremmednøkkel til kodeverkstabellen som viser mulige kjønn for bruker og viser til brukerens kjønn';
COMMENT ON COLUMN HISTORIKKINNSLAG.KL_BRUKER_KJOENN IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN HISTORIKKINNSLAG.KL_HISTORIKKINNSLAG_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON TABLE HISTORIKKINNSLAG  IS 'Historikk over hendelser i saken';
