INSERT INTO BEHANDLING_STEG_TYPE (KODE,NAVN,BEHANDLING_STATUS_DEF,BESKRIVELSE)
VALUES ('FAKTAVERGESTEG','Fakta om verge','UTRED','Lagre fakta om verge');

INSERT INTO VURDERINGSPUNKT_DEF (KODE,BEHANDLING_STEG,VURDERINGSPUNKT_TYPE,NAVN) VALUES ('FAKTAVERGESTEG.INN','FAKTAVERGESTEG','INN','Fakta om verge - Inngang');

INSERT INTO VURDERINGSPUNKT_DEF (KODE,BEHANDLING_STEG,VURDERINGSPUNKT_TYPE,NAVN) VALUES ('FAKTAVERGESTEG.UT','FAKTAVERGESTEG','UT','Fakta om verge - Utgang');

INSERT INTO AKSJONSPUNKT_DEF (KODE, NAVN, VURDERINGSPUNKT, BESKRIVELSE, VILKAR_TYPE, TOTRINN_BEHANDLING_DEFAULT, AKSJONSPUNKT_TYPE, FRIST_PERIODE, TILBAKEHOPP_VED_GJENOPPTAKELSE, LAG_UTEN_HISTORIKK, SKJERMLENKE_TYPE )
VALUES ('5030', 'Avklar verge', 'FAKTAVERGESTEG.UT', 'Avklar verge', '-', 'N', 'MANU', null, 'N', 'N', '-');

INSERT INTO BEHANDLING_TYPE_STEG_SEKV (ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR) VALUES
(SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval, 'BT-007', 'FAKTAVERGESTEG', 65);

INSERT INTO BEHANDLING_TYPE_STEG_SEKV (ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR) VALUES
(SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval, 'BT-009', 'FAKTAVERGESTEG', 65);

--historikkinnslag
UPDATE KODELISTE_NAVN_I18N SET NAVN='Fakta om verge/fullmektig' WHERE KL_KODEVERK='SKJERMLENKE_TYPE' AND KL_KODE='FAKTA_OM_VERGE';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Registering av opplysninger om verge/fullmektig' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='REGISTRER_OM_VERGE';
