CREATE TABLE TOTRINNRESULTATGRUNNLAG
(
  ID                             NUMBER(19)                        NOT NULL,
  BEHANDLING_ID                  NUMBER(19)                        NOT NULL,
  FAKTA_FEILUTBETALING_ID        NUMBER(19)                        NOT NULL,
  VURDERT_FORELDELSE_ID          NUMBER(19),
  VURDERT_VILKAAR_ID             NUMBER(19),
  AKTIV                          VARCHAR2(1 CHAR)                  NOT NULL,
  VERSJON                        NUMBER(19) DEFAULT 0              NOT NULL,
  OPPRETTET_AV                   VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
  OPPRETTET_TID                  TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
  ENDRET_AV                      VARCHAR2(20 CHAR),
  ENDRET_TID                     TIMESTAMP(3),
  CONSTRAINT PK_TOTRINNRESULTATGRUNNLAG PRIMARY KEY (ID),
  CONSTRAINT FK_TOTRINNRESULTATGRUNNLAG_1 FOREIGN KEY ( BEHANDLING_ID ) REFERENCES BEHANDLING ( ID ),
  CONSTRAINT FK_TOTRINNRESULTATGRUNNLAG_2 FOREIGN KEY ( FAKTA_FEILUTBETALING_ID ) REFERENCES GR_FEILUTBETALING ( ID ),
  CONSTRAINT FK_TOTRINNRESULTATGRUNNLAG_3 FOREIGN KEY ( VURDERT_FORELDELSE_ID ) REFERENCES GR_VURDERT_FORELDELSE ( ID ),
  CONSTRAINT FK_TOTRINNRESULTATGRUNNLAG_4 FOREIGN KEY ( VURDERT_VILKAAR_ID ) REFERENCES GR_VILKAAR ( ID ),
  CONSTRAINT CHK_TOTRINNRESGR_AKTIV CHECK (AKTIV IN ('J', 'N'))
);

CREATE SEQUENCE SEQ_TOTRINNRESULTATGRUNNLAG MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

CREATE INDEX IDX_TORINN_RES_GR_01 ON TOTRINNRESULTATGRUNNLAG (BEHANDLING_ID);
CREATE INDEX IDX_TORINN_RES_GR_02 ON TOTRINNRESULTATGRUNNLAG (FAKTA_FEILUTBETALING_ID);
CREATE INDEX IDX_TORINN_RES_GR_03 ON TOTRINNRESULTATGRUNNLAG (VURDERT_FORELDELSE_ID);
CREATE INDEX IDX_TORINN_RES_GR_04 ON TOTRINNRESULTATGRUNNLAG (VURDERT_VILKAAR_ID);

COMMENT ON TABLE TOTRINNRESULTATGRUNNLAG  IS 'Tabell som held grunnlagsId for data vist i panelet fra beslutter.';
COMMENT ON COLUMN TOTRINNRESULTATGRUNNLAG.ID IS 'PK';
COMMENT ON COLUMN TOTRINNRESULTATGRUNNLAG.BEHANDLING_ID IS 'FK til behandling som hører til totrinn resultatet';
COMMENT ON COLUMN TOTRINNRESULTATGRUNNLAG.FAKTA_FEILUTBETALING_ID IS 'FK til aktivt FeilutbetalingAggregate ved totrinnsbehandlingen';
COMMENT ON COLUMN TOTRINNRESULTATGRUNNLAG.VURDERT_FORELDELSE_ID IS 'FK til aktivt VurdertForeldelseAggregate ved totrinnsbehanddlingen';
COMMENT ON COLUMN TOTRINNRESULTATGRUNNLAG.VURDERT_VILKAAR_ID IS 'FK til aktivt VilkårVurderingAggregate ved totrinnsbehandlingen';