--KONSEKVENS_FOR_YTELSEN
UPDATE KODELISTE_NAVN_I18N SET NAVN='Ingen endring' WHERE KL_KODEVERK='KONSEKVENS_FOR_YTELSEN' AND KL_KODE='INGEN_ENDRING';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Foreldrepenger opphører' WHERE KL_KODEVERK='KONSEKVENS_FOR_YTELSEN' AND KL_KODE='FORELDREPENGER_OPPHØRER';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Endring i uttak' WHERE KL_KODEVERK='KONSEKVENS_FOR_YTELSEN' AND KL_KODE='ENDRING_I_UTTAK';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Endring i fordeling av ytelsen' WHERE KL_KODEVERK='KONSEKVENS_FOR_YTELSEN' AND KL_KODE='ENDRING_I_FORDELING_AV_YTELSEN';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Endring i beregning og uttak' WHERE KL_KODEVERK='KONSEKVENS_FOR_YTELSEN' AND KL_KODE='ENDRING_I_BEREGNING_OG_UTTAK';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Endring i beregning' WHERE KL_KODEVERK='KONSEKVENS_FOR_YTELSEN' AND KL_KODE='ENDRING_I_BEREGNING';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Udefinert' WHERE KL_KODEVERK='KONSEKVENS_FOR_YTELSEN' AND KL_KODE='-';

--TILBAKEKR_VIDERE_BEH
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'TILBAKEKR_VIDERE_BEH','TILBAKEKR_INFOTRYGD','NB','Feilutbetaling med tilbakekreving','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'TILBAKEKR_VIDERE_BEH','TILBAKEKR_IGNORER','NB','Feilutbetaling, avvent samordning','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'TILBAKEKR_VIDERE_BEH','TILBAKEKR_INNTREKK','NB','Feilutbetaling hvor inntrekk dekker hele beløpet','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'TILBAKEKR_VIDERE_BEH','-','NB','UDefinert','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'TILBAKEKR_VIDERE_BEH','TILBAKEKR_OPPDATER', 'Endringer vil oppdatere eksisterende feilutbetalte perioder og beløp.', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'TILBAKEKR_VIDERE_BEH','TILBAKEKR_OPPDATER','NB','Endringer vil oppdatere eksisterende feilutbetalte perioder og beløp.','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

--BEHANDLING_RESULTAT_TYPE
UPDATE KODELISTE_NAVN_I18N SET NAVN='Innvilget' WHERE KL_KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KL_KODE='INNVILGET';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Opphør' WHERE KL_KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KL_KODE='OPPHØR';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Ikke fastsatt' WHERE KL_KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KL_KODE='IKKE_FASTSATT';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Ingen endring' WHERE KL_KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KL_KODE='INGEN_ENDRING';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Foreldrepenger er endret' WHERE KL_KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KL_KODE='FORELDREPENGER_ENDRET';
UPDATE KODELISTE_NAVN_I18N SET NAVN='Avslått' WHERE KL_KODEVERK='BEHANDLING_RESULTAT_TYPE' AND KL_KODE='AVSLÅTT';

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_RESULTAT_TYPE','MANGLER_BEREGNINGSREGLER', 'Mangler beregningsregler', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_RESULTAT_TYPE','MANGLER_BEREGNINGSREGLER','NB','Mangler beregningsregler','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_RESULTAT_TYPE','MERGET_OG_HENLAGT', 'Mottatt ny søknad', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_RESULTAT_TYPE','MERGET_OG_HENLAGT','NB','Mottatt ny søknad','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

--BEHANDLING_AARSAK
INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','BERØRT-BEHANDLING', 'Endring i den andre forelderens uttak', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','BERØRT-BEHANDLING','NB','Endring i den andre forelderens uttak','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','ETTER_KLAGE', 'Ny behandling eller revurdering etter klage eller anke', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','ETTER_KLAGE','NB','Ny behandling eller revurdering etter klage eller anke','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','INFOBREV_BEHANDLING', 'Sende informasjonsbrev', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','INFOBREV_BEHANDLING','NB','Sende informasjonsbrev','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','KØET-BEHANDLING', 'Søker eller den andre forelderen har en åpen behandling', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','KØET-BEHANDLING','NB','Søker eller den andre forelderen har en åpen behandling','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-ANNET', 'Annet', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-ANNET','NB','Annet','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-AVAB', 'Avvik i antall barn', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-AVAB','NB','Avvik i antall barn','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-BER-GRUN', 'Nye opplysninger som kan påvirke beregningsgrunnlaget', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-BER-GRUN','NB','Nye opplysninger som kan påvirke beregningsgrunnlaget','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-DØD', 'Dødsfall', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-DØD','NB','Dødsfall','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-END-FRA-BRUKER', 'Endringssøknad fra bruker', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-END-FRA-BRUKER','NB','Endringssøknad fra bruker','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-END-INNTEKTSMELD', 'Mottatt ny inntektsmelding', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-END-INNTEKTSMELD','NB','Mottatt ny inntektsmelding','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-ENDR-BER-GRUN', 'Nye opplysninger som kan påvirke beregningsgrunnlaget', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-ENDR-BER-GRUN','NB','Nye opplysninger som kan påvirke beregningsgrunnlaget','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-FEFAKTA', 'Feil eller endret fakta', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-FEFAKTA','NB','Feil eller endret fakta','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-FRDLING', 'Nye opplysninger om uttak', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-FRDLING','NB','Nye opplysninger om uttak','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-FRIST', 'Nye opplysninger som kan påvirke vurderingen av søknadsfristen', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-FRIST','NB','Nye opplysninger som kan påvirke vurderingen av søknadsfristen','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-FØDSEL', 'Fødsel', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-FØDSEL','NB','Fødsel','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-HENDELSE-DØD-B', 'Melding om registrert død på barn i folkeregisteret', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-HENDELSE-DØD-B','NB','Melding om registrert død på barn i folkeregisteret','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-HENDELSE-DØD-F', 'Melding om registrert død på forelder i folkeregisteret', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-HENDELSE-DØD-F','NB','Melding om registrert død på forelder i folkeregisteret','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-HENDELSE-DØDFØD', 'Melding om registrert dødfødsel i folkeregisteret', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-HENDELSE-DØDFØD','NB','Melding om registrert dødfødsel i folkeregisteret','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-HENDELSE-FØDSEL', 'Melding om registrert fødsel i folkeregisteret', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-HENDELSE-FØDSEL','NB','Melding om registrert fødsel i folkeregisteret','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-INNTK', 'Nye opplysninger om inntekt', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-INNTK','NB','Nye opplysninger om inntekt','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-KLAG-M-INNTK', 'Klage/ankebehandling med endrede inntektsopplysninger', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-KLAG-M-INNTK','NB','Klage/ankebehandling med endrede inntektsopplysninger','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-KLAG-U-INNTK', 'Klage/ankebehandling uten endrede inntektsopplysninger', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-KLAG-U-INNTK','NB','Klage/ankebehandling uten endrede inntektsopplysninger','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-LOV', 'Feil lovanvendelse', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-KLAG-U-INNTK','NB','Feil lovanvendelse','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-MDL', 'Nye opplysninger om medlemskap', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-MDL','NB','Nye opplysninger om medlemskap','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-MF', 'Manglende informasjon om fødsel i folkeregisteret', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-MF','NB','Manglende informasjon om fødsel i folkeregisteret','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-MFIP', 'Manglende informasjon om fødsel i folkeregisteret mellom uke 26 og 29', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-MFIP','NB','Manglende informasjon om fødsel i folkeregisteret mellom uke 26 og 29','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-OPTJ', 'Nye opplysninger om opptjening', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-OPTJ','NB','Nye opplysninger om opptjening','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-PRSSL', 'Prosessuell feil', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-PRSSL','NB','Prosessuell feil','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-REGISTEROPPL', 'Nye registeropplysninger', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-REGISTEROPPL','NB','Nye registeropplysninger','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-RGLF', 'Feil regelverksforståelse', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-RGLF','NB','Feil regelverksforståelse','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-SATS-REGULERING', 'Regulering av grunnbeløp', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-SATS-REGULERING','NB','Regulering av grunnbeløp','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-SRTB', 'Nye opplysninger om søkers relasjon til barnet', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-SRTB','NB','Nye opplysninger om søkers relasjon til barnet','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-TILST-YT-INNVIL', 'Tilstøtende ytelse innvilget', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-TILST-YT-INNVIL','NB','Tilstøtende ytelse innvilget','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-TILST-YT-OPPH', 'Tilstøtende ytelse opphørt', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-TILST-YT-OPPH','NB','Tilstøtende ytelse opphørt','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, BESKRIVELSE,GYLDIG_FOM)
VALUES (SEQ_KODELISTE.NEXTVAL, 'BEHANDLING_AARSAK','RE-YTELSE', 'Nye opplysninger om ytelse', to_date('2000-01-01', 'YYYY-MM-DD'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_AARSAK','RE-YTELSE','NB','Nye opplysninger om ytelse','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);
