ALTER TABLE BEHANDLING DROP COLUMN BEHANDLENDE_ENHET_ARSAK;

ALTER TABLE BEHANDLING DROP COLUMN SIST_OPPDATERT_TIDSPUNKT;

ALTER TABLE BEHANDLING DROP COLUMN AAPNET_FOR_ENDRING;

ALTER TABLE BEHANDLING ADD MANUELT_OPPRETTET VARCHAR2(1 BYTE);

COMMENT ON COLUMN BEHANDLING.MANUELT_OPPRETTET is 'Angir om behandlingen ble opprettet manuelt. ';

UPDATE BEHANDLING SET MANUELT_OPPRETTET='N';

ALTER TABLE BEHANDLING MODIFY MANUELT_OPPRETTET NOT NULL ENABLE;
