alter table FAKTA_FEILUTBETALING_PERIODE modify (HENDELSE_UNDERTYPE not null);
ALTER TABLE FAKTA_FEILUTBETALING_PERIODE ADD CONSTRAINT FK_FAKTA_FEILUT_PERIODE_2 FOREIGN KEY (HENDELSE_TYPE, KL_HENDELSE_TYPE) REFERENCES KODELISTE (KODE, KODEVERK);
ALTER TABLE FAKTA_FEILUTBETALING_PERIODE ADD CONSTRAINT FK_FAKTA_FEILUT_PERIODE_3 FOREIGN KEY (HENDELSE_UNDERTYPE, KL_HENDELSE_UNDERTYPE) REFERENCES KODELISTE (KODE, KODEVERK);
ALTER TABLE FAKTA_FEILUTBETALING_PERIODE ADD CONSTRAINT FK_FAKTA_FEILUT_PERIODE_4 FOREIGN KEY (HENDELSE_TYPE, KL_HENDELSE_TYPE, HENDELSE_UNDERTYPE, KL_HENDELSE_UNDERTYPE) REFERENCES KODELISTE_RELASJON (KODE1, KODEVERK1, KODE2, KODEVERK2);


CREATE INDEX IDX_FAKTA_FEILUTBETALING_PERIODE_1 ON FAKTA_FEILUTBETALING_PERIODE (HENDELSE_TYPE);

CREATE INDEX IDX_FAKTA_FEILUTBETALING_PERIODE_2 ON FAKTA_FEILUTBETALING_PERIODE (HENDELSE_UNDERTYPE);

CREATE INDEX IDX_FAKTA_FEILUTBETALING_PERIODE_3 ON FAKTA_FEILUTBETALING_PERIODE (HENDELSE_TYPE,HENDELSE_UNDERTYPE);