UPDATE KODELISTE set KODE = 'FORSTO_BURDE_FORSTAATT' where kodeverk = 'VILKAAR_RESULTAT' and kode = 'FORSTO_BURDE_FORSTÅTT';
UPDATE KODELISTE set KODE = 'FEIL_OPPLYSNINGER' where kodeverk = 'VILKAAR_RESULTAT' and kode = 'FEIL_OPPLYSNINGER_FRA_BRUKER';
UPDATE KODELISTE set KODE = 'MANGELFULL_OPPLYSNING' where kodeverk = 'VILKAAR_RESULTAT' and kode = 'MANGELFULLE_OPPLYSNINGER_FRA_BRUKER';
UPDATE KODELISTE set KODE = 'GOD_TRO' where kodeverk = 'VILKAAR_RESULTAT' and kode = 'GOD_TRO';

UPDATE KODELISTE set KODE = 'GRAD_UAKTSOMHET' where kodeverk = 'SAERLIG_GRUNN' and kode = 'GRAD_AV_UAKTSOMHET';

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'SAERLIG_GRUNN','GRAD_UAKTSOMHET','NB','Graden av uaktsomhet hos den kravet retter seg mot','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'SAERLIG_GRUNN','HELT_ELLER_DELVIS_NAVS_FEIL','NB','Om feilen helt eller delvis kan tilskrives NAV','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'SAERLIG_GRUNN','STOERRELSE_BELOEP','NB','Størrelsen på feilutbetalt beløp','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'SAERLIG_GRUNN','TID_FRA_UTBETALING','NB','Hvor lang til siden utbetalingen fant sted','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'SAERLIG_GRUNN','ANNET','NB','Annet','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'AKTSOMHET','FORSETT','NB','Forsett','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'AKTSOMHET','GROVT_UAKTSOM','NB','Grov uaktsomhet','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'AKTSOMHET','SIMPEL_UAKTSOM','NB','Simpel uaktsomhet','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'VILKAAR_RESULTAT','FORSTO_BURDE_FORSTAATT','NB','Ja, mottaker forsto eller burde forstått at utbetalingen skyldtes en feil (1. ledd, 1. punkt)','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'VILKAAR_RESULTAT','FEIL_OPPLYSNINGER','NB','Ja, mottaker har forårsaket feilutbetalingen ved forsett eller uaktsomt gitt feilaktige opplysninger (1. ledd, 2 punkt)','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'VILKAAR_RESULTAT','MANGELFULL_OPPLYSNING','NB','Ja, mottaker har forårsaket feilutbetalingen ved forsett eller uaktsomt gitt mangelfulle opplysninger (1. ledd, 2 punkt)','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'VILKAAR_RESULTAT','GOD_TRO','NB','Nei, mottaker har mottatt beløpet i god tro (1. ledd)','VL',to_date('31.01.2019','DD.MM.RRRR'),null,null);