INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'SKJERMLENKE_TYPE','TILBAKEKREVING',null,'Tilbakekreving',to_date('01.01.2000','DD.MM.RRRR'),
to_date('31.12.9999','DD.MM.RRRR'),'VL',to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'SKJERMLENKE_TYPE','TILBAKEKREVING','NB','Tilbakekreving','VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKKINNSLAG_TYPE','TILBAKEKREVING',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKKINNSLAG_TYPE','TILBAKEKREVING','NB','Tilbakekreving','VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','ER_VILKARENE_TILBAKEKREVING_OPPFYLT',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','ER_VILKARENE_TILBAKEKREVING_OPPFYLT','NB','Er vilkårene for tilbakekreving oppfylt?','VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','MOTTAKER_UAKTSOMHET_GRAD',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','MOTTAKER_UAKTSOMHET_GRAD','NB','I hvilken grad har mottaker handlet uaktsomhet?','VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','ER_SARLIGE_GRUNNER_TIL_REDUKSJON',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','ER_SARLIGE_GRUNNER_TIL_REDUKSJON','NB','Er det særlige grunner til reduksjon?','VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','ANDEL_TILBAKEKREVES',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','ANDEL_TILBAKEKREVES','NB','Andel som tilbakekreves','VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','BELOEP_TILBAKEKREVES',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','BELOEP_TILBAKEKREVES','NB','Beløp som skal tilbakekreves','VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','TILBAKEKREV_SMAABELOEP',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','TILBAKEKREV_SMAABELOEP','NB','Er totalbeløpet under 4 rettsgebyr(6.ledd)?','VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','BELOEP_ER_I_BEHOLD',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','BELOEP_ER_I_BEHOLD','NB','Er beløpet i behold?','VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','ILEGG_RENTER',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKK_ENDRET_FELT_TYPE','ILEGG_RENTER','NB','Skal det tilegges renter?','VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);

INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'HISTORIKK_OPPLYSNING_TYPE','TILBAKEKREVING_OPPFYLT_BEGRUNNELSE',null,null,to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HISTORIKK_OPPLYSNING_TYPE','TILBAKEKREVING_OPPFYLT_BEGRUNNELSE','NB','TILBAKEKREVING_OPPFYLT_BEGRUNNELSE','VL',
to_date(sysdate,'DD.MM.RRRR'),null,null);