INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN) VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HENDELSE_UNDERTYPE','UTVANDRET','NB','Utvandret medlemskap');
INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN) VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'HENDELSE_UNDERTYPE','MEDLEM_I_ANNET_LAND','NB','Medlem i et annet land');
