CREATE TABLE KRAV_GRUNNLAG_431(
  ID                      NUMBER(19, 0)      NOT NULL,
  VEDTAK_ID               NUMBER(19, 0)      NOT NULL,
  KRAV_STATUS_KODE        VARCHAR2(100 CHAR) NOT NULL,
  FAG_OMRAADE_KODE        VARCHAR2(100 CHAR) NOT NULL,
  FAGSYSTEM_ID            VARCHAR2(30 CHAR)  NOT NULL,
  VEDTAK_FAGSYSTEM_DATO   DATE,
  OMGJORT_VEDTAK_ID       NUMBER(19, 0),
  GJELDER_VEDTAK_ID       VARCHAR2(50 CHAR)  NOT NULL,
  GJELDER_TYPE            VARCHAR2(100 CHAR) NOT NULL,
  UTBETALES_TIL_ID        VARCHAR2(50 CHAR)  NOT NULL,
  UTBET_ID_TYPE           VARCHAR2(100 CHAR) NOT NULL,
  HJEMMEL_KODE            VARCHAR2(20 CHAR),
  BEREGNES_RENTER         VARCHAR2(1 CHAR),
  ANSVARLIG_ENHET         VARCHAR2(13 CHAR)  NOT NULL,
  BOSTED_ENHET            VARCHAR2(13 CHAR)  NOT NULL,
  BEHANDL_ENHET           VARCHAR2(13 CHAR)  NOT NULL,
  KONTROLL_FELT           VARCHAR2(26 CHAR)  NOT NULL,
  SAKSBEH_ID              VARCHAR2(20 CHAR)  NOT NULL,
  REFERANSE               VARCHAR2(30 CHAR),
  KL_KRAV_STATUS_KODE     VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('KRAV_STATUS_KODE') VIRTUAL VISIBLE,
  KL_FAG_OMRAADE_KODE     VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('FAG_OMRAADE_KODE') VIRTUAL VISIBLE,
  KL_GJELDER_TYPE         VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('GJELDER_TYPE') VIRTUAL VISIBLE,
  OPPRETTET_AV            VARCHAR2(20 CHAR) DEFAULT 'VL'        NOT NULL ,
  OPPRETTET_TID           TIMESTAMP(3) DEFAULT systimestamp      NOT NULL ,
  ENDRET_AV               VARCHAR2(20 CHAR),
  ENDRET_TID              TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_KRAV_GRUNNLAG_431 MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE  KRAV_GRUNNLAG_431 IS 'Tabell for tilbakekrevingsvedtak fra økonomi';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.VEDTAK_ID IS 'Identifikasjon av tilbakekrevingsvedtaket opprettet av Tilbakekrevingskomponenten';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.KRAV_STATUS_KODE IS 'Status på kravgrunnlaget';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.FAG_OMRAADE_KODE IS 'Fagområdet på feilutbetalingen';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.FAGSYSTEM_ID IS 'Fagsystemets identifikasjon av vedtaket som har feilutbetaling';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.VEDTAK_FAGSYSTEM_DATO IS 'Fagsystemets vedtaksdato for vedtaket';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.OMGJORT_VEDTAK_ID IS 'Henvisning til forrige gyldige vedtak';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.GJELDER_VEDTAK_ID IS 'Vanligvis stønadsmottaker (fnr/orgnr) i feilutbetalingen';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.GJELDER_TYPE IS 'Angir om Vedtak-gjelder-id er fnr, orgnr, TSS-nr etc';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.UTBETALES_TIL_ID IS 'Mottaker av pengene i feilutbetalingen';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.UTBET_ID_TYPE IS 'Angir om Utbetales-til-id er fnr, orgnr, TSS-nr etc';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.HJEMMEL_KODE IS 'Lovhjemmel for tilbakekrevingsvedtaket';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.BEREGNES_RENTER IS 'J dersom det skal beregnes renter på kravet';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.ANSVARLIG_ENHET IS 'Enhet ansvarlig';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.BOSTED_ENHET IS 'Bostedsenhet, hentet fra feilutbetalingen';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.BEHANDL_ENHET IS 'Behandlende enhet, hentet fra feilutbetalingen';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.KONTROLL_FELT IS 'Brukes ved innsending av tilbakekrevingsvedtak for å kontrollere at kravgrunnlaget ikke er blitt endret i mellomtiden';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.SAKSBEH_ID IS 'Saksbehandler';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.REFERANSE IS 'Henvisning fra nyeste oppdragslinje';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.KL_KRAV_STATUS_KODE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.KL_FAG_OMRAADE_KODE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN KRAV_GRUNNLAG_431.KL_GJELDER_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';


CREATE TABLE KRAV_GRUNNLAG_PERIODE_432(
  ID                      NUMBER(19, 0)  NOT NULL,
  FOM                     DATE           NOT NULL,
  TOM                     DATE           NOT NULL,
  KRAV_GRUNNLAG_431_ID    NUMBER(19, 0)  NOT NULL,
  OPPRETTET_AV            VARCHAR2(20 CHAR) DEFAULT 'VL'        NOT NULL ,
  OPPRETTET_TID           TIMESTAMP(3) DEFAULT systimestamp      NOT NULL ,
  ENDRET_AV               VARCHAR2(20 CHAR),
  ENDRET_TID              TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_KRAV_GRUNNLAG_PERIODE_432 MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE  KRAV_GRUNNLAG_PERIODE_432 IS 'Perioder av tilbakekrevingsvedtak fra økonomi';
COMMENT ON COLUMN KRAV_GRUNNLAG_PERIODE_432.FOM IS 'Første dag i periode';
COMMENT ON COLUMN KRAV_GRUNNLAG_PERIODE_432.TOM IS 'Siste dag i periode';
COMMENT ON COLUMN KRAV_GRUNNLAG_PERIODE_432.KRAV_GRUNNLAG_431_ID IS 'FK:KRAV_GRUNNLAG_431';

CREATE TABLE KRAV_GRUNNLAG_BELOP_433(
  ID                      NUMBER(19, 0)      NOT NULL,
  KLASSE_KODE             VARCHAR2(100 CHAR) NOT NULL,
  KLASSE_TYPE             VARCHAR2(100 CHAR) NOT NULL,
  OPPR_UTBET_BELOP        NUMBER(12,2),
  NY_BELOP                NUMBER(12,2)       NOT NULL,
  TILBAKE_KREVES_BELOP    NUMBER(12,2),
  UINNKREVD_BELOP         NUMBER(12,2),
  RESULTAT_KODE           VARCHAR2(20 CHAR),
  AARSAK_KODE             VARCHAR2(20 CHAR),
  SKYLD_KODE              VARCHAR2(20 CHAR),
  KRAV_GRUNNLAG_PERIODE_432_ID NUMBER(19, 0)      NOT NULL,
  KL_KLASSE_KODE          VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('KLASSE_KODE') VIRTUAL VISIBLE,
  KL_KLASSE_TYPE          VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('KLASSE_TYPE') VIRTUAL VISIBLE,
  OPPRETTET_AV            VARCHAR2(20 CHAR) DEFAULT 'VL'        NOT NULL ,
  OPPRETTET_TID           TIMESTAMP(3) DEFAULT systimestamp      NOT NULL ,
  ENDRET_AV               VARCHAR2(20 CHAR),
  ENDRET_TID              TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_KRAV_GRUNNLAG_BELOP_433 MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE  KRAV_GRUNNLAG_BELOP_433 IS 'Tabell for tilbakekrevingsbeløp fra økonomi';
COMMENT ON COLUMN KRAV_GRUNNLAG_BELOP_433.KLASSE_KODE IS 'Klassifisering av stønad, skatt, trekk etc.';
COMMENT ON COLUMN KRAV_GRUNNLAG_BELOP_433.KLASSE_TYPE IS 'Angir type av klassekoden';
COMMENT ON COLUMN KRAV_GRUNNLAG_BELOP_433.OPPR_UTBET_BELOP IS 'Opprinnelig beregnet beløp, dvs utbetalingen som førte til feilutbetaling';
COMMENT ON COLUMN KRAV_GRUNNLAG_BELOP_433.NY_BELOP IS 'Beløpet som ble beregnet ved korrigeringen';
COMMENT ON COLUMN KRAV_GRUNNLAG_BELOP_433.TILBAKE_KREVES_BELOP IS 'Beløpet som skal tilbakekreves';
COMMENT ON COLUMN KRAV_GRUNNLAG_BELOP_433.UINNKREVD_BELOP IS 'Beløp som ikke skal tilbakekreves';
COMMENT ON COLUMN KRAV_GRUNNLAG_BELOP_433.RESULTAT_KODE IS 'Hvilket vedtak som er fattet ang tilbakekreving';
COMMENT ON COLUMN KRAV_GRUNNLAG_BELOP_433.AARSAK_KODE IS 'Årsak til feilutbetalingen';
COMMENT ON COLUMN KRAV_GRUNNLAG_BELOP_433.SKYLD_KODE IS 'Hvem som har skyld i at det ble feilutbetalt';
COMMENT ON COLUMN KRAV_GRUNNLAG_BELOP_433.KRAV_GRUNNLAG_PERIODE_432_ID IS 'FK:KRAV_GRUNNLAG_PERIODE_432';
COMMENT ON COLUMN KRAV_GRUNNLAG_BELOP_433.KL_KLASSE_KODE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN KRAV_GRUNNLAG_BELOP_433.KL_KLASSE_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';


CREATE TABLE KRAV_VEDTAK_STATUS_437(
  ID                      NUMBER(19, 0)      NOT NULL,
  VEDTAK_ID               NUMBER(19, 0)      NOT NULL,
  KRAV_STATUS_KODE        VARCHAR2(100 CHAR) NOT NULL,
  FAG_OMRAADE_KODE        VARCHAR2(100 CHAR) NOT NULL,
  FAGSYSTEM_ID            VARCHAR2(30 CHAR)  NOT NULL,
  GJELDER_VEDTAK_ID       VARCHAR2(50 CHAR)  NOT NULL,
  GJELDER_TYPE            VARCHAR2(100 CHAR) NOT NULL,
  REFERANSE               VARCHAR2(30 CHAR),
  KL_KRAV_STATUS_KODE     VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('KRAV_STATUS_KODE') VIRTUAL VISIBLE,
  KL_FAG_OMRAADE_KODE     VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('FAG_OMRAADE_KODE') VIRTUAL VISIBLE,
  KL_GJELDER_TYPE         VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('GJELDER_TYPE') VIRTUAL VISIBLE,
  OPPRETTET_AV            VARCHAR2(20 CHAR) DEFAULT 'VL'        NOT NULL ,
  OPPRETTET_TID           TIMESTAMP(3) DEFAULT systimestamp      NOT NULL ,
  ENDRET_AV               VARCHAR2(20 CHAR),
  ENDRET_TID              TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_KRAV_VEDTAK_STATUS_437 MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE  KRAV_VEDTAK_STATUS_437 IS 'Tabell for krav og vedtak status endringer fra økonomi';
COMMENT ON COLUMN KRAV_VEDTAK_STATUS_437.VEDTAK_ID IS 'Identifikasjon av tilbakekrevingsvedtaket opprettet av Tilbakekrevingskomponenten';
COMMENT ON COLUMN KRAV_VEDTAK_STATUS_437.KRAV_STATUS_KODE IS 'Status på kravgrunnlaget';
COMMENT ON COLUMN KRAV_VEDTAK_STATUS_437.FAG_OMRAADE_KODE IS 'Fagområdet på feilutbetalingen';
COMMENT ON COLUMN KRAV_VEDTAK_STATUS_437.FAGSYSTEM_ID IS 'Fagsystemets identifikasjon av vedtaket som har feilutbetaling';
COMMENT ON COLUMN KRAV_VEDTAK_STATUS_437.GJELDER_VEDTAK_ID IS 'Vanligvis stønadsmottaker (fnr/orgnr) i feilutbetalingen';
COMMENT ON COLUMN KRAV_VEDTAK_STATUS_437.GJELDER_TYPE IS 'Angir om Vedtak-gjelder-id er fnr, orgnr, TSS-nr etc';
COMMENT ON COLUMN KRAV_VEDTAK_STATUS_437.REFERANSE IS 'Henvisning fra nyeste oppdragslinje';
COMMENT ON COLUMN KRAV_VEDTAK_STATUS_437.KL_KRAV_STATUS_KODE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN KRAV_VEDTAK_STATUS_437.KL_FAG_OMRAADE_KODE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN KRAV_VEDTAK_STATUS_437.KL_GJELDER_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';

CREATE TABLE GR_KRAV_GRUNNLAG(
  ID                        NUMBER(19, 0)               NOT NULL ,
  GRUNNLAG_OKONOMI_ID       NUMBER(19, 0)               NOT NULL ,
  BEHANDLING_ID             NUMBER(19, 0)               NOT NULL ,
  AKTIV                     VARCHAR2(1) DEFAULT 'J'     NOT NULL ,
  OPPRETTET_AV  VARCHAR2(200 CHAR) DEFAULT 'VL'         NOT NULL ,
  OPPRETTET_TID TIMESTAMP(3) DEFAULT systimestamp       NOT NULL ,
  ENDRET_AV     VARCHAR2(20 CHAR),
  ENDRET_TID    TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_GR_KRAV_GRUNNLAG MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE  GR_KRAV_GRUNNLAG IS 'Aggregate tabell for å lagre grunnlag';
COMMENT ON COLUMN GR_KRAV_GRUNNLAG.ID IS 'Primary Key';
COMMENT ON COLUMN GR_KRAV_GRUNNLAG.GRUNNLAG_OKONOMI_ID IS 'FK:KRAV_GRUNNLAG_431.Angir grunnlag kommer fra okonomi';
COMMENT ON COLUMN GR_KRAV_GRUNNLAG.BEHANDLING_ID IS 'FK: BEHANDLING fremmednøkkel for tilknyttet behandling';
COMMENT ON COLUMN GR_KRAV_GRUNNLAG.AKTIV IS 'Angir status av grunnlag';

--------------------------------------------------------
--  DDL for Index og Primary Key
--------------------------------------------------------
ALTER TABLE KRAV_GRUNNLAG_431  ADD CONSTRAINT PK_KRAV_GRUNNLAG_431 PRIMARY KEY ("ID") ENABLE;

ALTER TABLE KRAV_GRUNNLAG_PERIODE_432  ADD CONSTRAINT PK_KRAV_GRUNNLAG_PERIODE_432 PRIMARY KEY ("ID") ENABLE;

ALTER TABLE KRAV_GRUNNLAG_BELOP_433  ADD CONSTRAINT PK_KRAV_GRUNNLAG_BELOP_433 PRIMARY KEY ("ID") ENABLE;

ALTER TABLE KRAV_VEDTAK_STATUS_437  ADD CONSTRAINT PK_KRAV_VEDTAK_STATUS_437 PRIMARY KEY ("ID") ENABLE;

ALTER TABLE GR_KRAV_GRUNNLAG  ADD CONSTRAINT PK_GR_KRAV_GRUNNLAG PRIMARY KEY ("ID") ENABLE;

CREATE INDEX IDX_KRAV_GRUNNLAG_431_1 ON KRAV_GRUNNLAG_431 ("KRAV_STATUS_KODE");

CREATE INDEX IDX_KRAV_GRUNNLAG_431_2 ON KRAV_GRUNNLAG_431 ("FAG_OMRAADE_KODE");

CREATE INDEX IDX_KRAV_GRUNNLAG_431_3 ON KRAV_GRUNNLAG_431 ("GJELDER_TYPE");

CREATE INDEX IDX_KRAV_GRUNNLAG_431_4 ON KRAV_GRUNNLAG_431 ("UTBET_ID_TYPE");

CREATE INDEX IDX_KRAV_GRUNNLAG_431_5 ON KRAV_GRUNNLAG_431 ("UTBETALES_TIL_ID");

CREATE INDEX IDX_KRAV_GRUNN_PERIODE_432_1 ON KRAV_GRUNNLAG_PERIODE_432 ("KRAV_GRUNNLAG_431_ID");

CREATE INDEX IDX_KRAV_GRUNN_BELOP_433_1 ON KRAV_GRUNNLAG_BELOP_433 ("KLASSE_KODE");

CREATE INDEX IDX_KRAV_GRUNN_BELOP_433_2 ON KRAV_GRUNNLAG_BELOP_433 ("KLASSE_TYPE");

CREATE INDEX IDX_KRAV_GRUNN_BELOP_433_3 ON KRAV_GRUNNLAG_BELOP_433 ("KRAV_GRUNNLAG_PERIODE_432_ID");

CREATE INDEX IDX_KRAV_VED_STATUS_437_1 ON KRAV_VEDTAK_STATUS_437 ("KRAV_STATUS_KODE");

CREATE INDEX IDX_KRAV_VED_STATUS_437_2 ON KRAV_VEDTAK_STATUS_437 ("FAG_OMRAADE_KODE");

CREATE INDEX IDX_KRAV_VED_STATUS_437_3 ON KRAV_VEDTAK_STATUS_437 ("GJELDER_TYPE");

CREATE INDEX IDX_GR_KRAV_GRUNNLAG_1 ON GR_KRAV_GRUNNLAG ("GRUNNLAG_OKONOMI_ID");

CREATE INDEX IDX_GR_KRAV_GRUNNLAG_2 ON GR_KRAV_GRUNNLAG ("BEHANDLING_ID");

--------------------------------------------------------
--  Ref Constraints for Tabeller
--------------------------------------------------------
ALTER TABLE KRAV_GRUNNLAG_431 ADD CONSTRAINT FK_KRAV_GRUNNLAG_431_1 FOREIGN KEY ("KRAV_STATUS_KODE","KL_KRAV_STATUS_KODE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

ALTER TABLE KRAV_GRUNNLAG_431 ADD CONSTRAINT FK_KRAV_GRUNNLAG_431_2 FOREIGN KEY ("FAG_OMRAADE_KODE","KL_FAG_OMRAADE_KODE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

ALTER TABLE KRAV_GRUNNLAG_431 ADD CONSTRAINT FK_KRAV_GRUNNLAG_431_3 FOREIGN KEY ("GJELDER_TYPE","KL_GJELDER_TYPE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

ALTER TABLE KRAV_GRUNNLAG_431 ADD CONSTRAINT FK_KRAV_GRUNNLAG_431_4 FOREIGN KEY ("UTBET_ID_TYPE","KL_GJELDER_TYPE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

ALTER TABLE KRAV_GRUNNLAG_PERIODE_432 ADD CONSTRAINT FK_KRAV_GRUNNLAG_PERIODE_432_1 FOREIGN KEY ("KRAV_GRUNNLAG_431_ID")
REFERENCES KRAV_GRUNNLAG_431("ID") ENABLE;

ALTER TABLE KRAV_GRUNNLAG_BELOP_433 ADD CONSTRAINT FK_KRAV_GRUNNLAG_BELOP_433_1 FOREIGN KEY ("KLASSE_KODE","KL_KLASSE_KODE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

ALTER TABLE KRAV_GRUNNLAG_BELOP_433 ADD CONSTRAINT FK_KRAV_GRUNNLAG_BELOP_433_2 FOREIGN KEY ("KLASSE_TYPE","KL_KLASSE_TYPE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

ALTER TABLE KRAV_GRUNNLAG_BELOP_433 ADD CONSTRAINT FK_KRAV_GRUNNLAG_BELOP_433_3 FOREIGN KEY ("KRAV_GRUNNLAG_PERIODE_432_ID")
REFERENCES KRAV_GRUNNLAG_PERIODE_432("ID") ENABLE;

ALTER TABLE KRAV_VEDTAK_STATUS_437 ADD CONSTRAINT FK_KRAV_VEDTAK_STATUS_437_1 FOREIGN KEY ("KRAV_STATUS_KODE","KL_KRAV_STATUS_KODE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

ALTER TABLE KRAV_VEDTAK_STATUS_437 ADD CONSTRAINT FK_KRAV_VEDTAK_STATUS_437_2 FOREIGN KEY ("FAG_OMRAADE_KODE","KL_FAG_OMRAADE_KODE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

ALTER TABLE KRAV_VEDTAK_STATUS_437 ADD CONSTRAINT FK_KRAV_VEDTAK_STATUS_437_3 FOREIGN KEY ("GJELDER_TYPE","KL_GJELDER_TYPE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

ALTER TABLE GR_KRAV_GRUNNLAG ADD CONSTRAINT FK_GR_KRAV_GRUNNLAG_1 FOREIGN KEY ("BEHANDLING_ID")
REFERENCES BEHANDLING("ID") ENABLE;

ALTER TABLE GR_KRAV_GRUNNLAG ADD CONSTRAINT FK_GR_KRAV_GRUNNLAG_2 FOREIGN KEY ("GRUNNLAG_OKONOMI_ID")
REFERENCES KRAV_GRUNNLAG_431("ID") ENABLE;