UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='UTVANDRET';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='IKKE_OPPHOLDSTILLATLSE';
UPDATE KODELISTE SET EKSTRA_DATA=2 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='MEDLEM_I_ANNET_LAND';
UPDATE KODELISTE SET EKSTRA_DATA=3 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='IKKE_JOBBET';
UPDATE KODELISTE SET EKSTRA_DATA=4 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='MER_OPPHOLD';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='IKKE_INNTEKT';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='IKKE_YRKESAKTIV';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ENDRING_GRUNNLAG';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='INNTEKT_UNDER';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ENDRET_DEKNINGSGRAD';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='FEIL_FLERBARNSDAGER';
UPDATE KODELISTE SET EKSTRA_DATA=2 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='OPPHOR_BARN_DOD';
UPDATE KODELISTE SET EKSTRA_DATA=3 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='OPPHOR_MOTTAKER_DOD';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='STONADSPERIODE_OVER_3';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='NY_STONADSPERIODE';
UPDATE KODELISTE SET EKSTRA_DATA=2 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='IKKE_OMSORG';
UPDATE KODELISTE SET EKSTRA_DATA=3 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='MOTTAKER_I_ARBEID';
UPDATE KODELISTE SET EKSTRA_DATA=4 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='FORELDRES_UTTAK';
UPDATE KODELISTE SET EKSTRA_DATA=5 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='STONADSPERIODE_MANGEL';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='LOVBESTEMT_FERIE';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ARBEID_HELTID';
UPDATE KODELISTE SET EKSTRA_DATA=2 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='MOTTAKER_HELT_AVHENGIG';
UPDATE KODELISTE SET EKSTRA_DATA=3 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='MOTTAKER_INNLAGT';
UPDATE KODELISTE SET EKSTRA_DATA=4 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='BARN_INNLAGT';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='KVO_MOTTAKER_HELT_AVHENGIG';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='KVO_MOTTAKER_INNLAGT';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='MOR_IKKE_ARBEID';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='MOR_IKKE_STUDERT';
UPDATE KODELISTE SET EKSTRA_DATA=2 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='MOR_IKKE_ARBEID_OG_STUDER';
UPDATE KODELISTE SET EKSTRA_DATA=3 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='MOR_IKKE_HELT_AVHENGIG';
UPDATE KODELISTE SET EKSTRA_DATA=4 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='MOR_IKKE_INNLAGT';
UPDATE KODELISTE SET EKSTRA_DATA=5 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='MOR_IKKE_I_IP';
UPDATE KODELISTE SET EKSTRA_DATA=6 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='MOR_IKKE_I_KP';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='OKONOMI_DOBBELUTBETALING';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='OKONOMI_UTBETALT';
UPDATE KODELISTE SET EKSTRA_DATA=2 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='OKONOMI_FEIL_TREKK';
UPDATE KODELISTE SET EKSTRA_DATA=3 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ANNET_FRITEKST';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_UTVANDRET';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_IKKE_BOSATT';
UPDATE KODELISTE SET EKSTRA_DATA=2 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_IKKE_OPPHOLDSRETT';
UPDATE KODELISTE SET EKSTRA_DATA=3 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_IKKE_LOVLIG_OPPHOLD';
UPDATE KODELISTE SET EKSTRA_DATA=4 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_MEDLEMSKAP_UNNTAKK';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_BARN_IKKE_REGISTRERT';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_MOTTAKER_FAR_MEDMOR';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_IKKE_OPPFYLT';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_BARN_OVER_15';
UPDATE KODELISTE SET EKSTRA_DATA=2 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_MANN_IKKE_ALENE';
UPDATE KODELISTE SET EKSTRA_DATA=3 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_STEBARN';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_ANDRE_FORELDRE_DODD';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_IKKE_TILDELT';
UPDATE KODELISTE SET EKSTRA_DATA=2 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_IKKE_MINDRE_SAMVAER';
UPDATE KODELISTE SET EKSTRA_DATA=3 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_FORELDREANSVAR_BARN_OVER_15';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_FAR_IKKE_OMSORG';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_STONADEN_ALLEREDE_UTBETALT';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_FAR_IKKE_ALENE';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='ES_FAR_IKKE_INNEN_STONADSPERIODE';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_UTVANDRET';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_MEDLEM_I_ANNET_LAND';
UPDATE KODELISTE SET EKSTRA_DATA=2 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_IKKE_OPPHOLDSTILLATLSE';
UPDATE KODELISTE SET EKSTRA_DATA=3 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_IKKE_JOBBET';
UPDATE KODELISTE SET EKSTRA_DATA=4 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_MER_OPPHOLD';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_ENDRING_TERMINDATO';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_TIDLIG_FODSEL';
UPDATE KODELISTE SET EKSTRA_DATA=2 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_IKKE_HELSEFARLIG';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_TILRETTELEGGING_FULLT_MULIG';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_TILRETTELEGGING_DELVIS_MULIG';
UPDATE KODELISTE SET EKSTRA_DATA=2 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_TILRETTELEGGING_IKKE_MULIG';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_FEIL_ARBEIDSFORHOLD';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_FEIL_ARBEIDSKATEGORI';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_IKKE_ARBEID';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_IKKE_TAP';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_ENDRING_GRUNNLAG';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_INNTEKT_UNDER';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_ENDRING_PROSENT';
UPDATE KODELISTE SET EKSTRA_DATA=1 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND KODE='SVP_ENDRING_PERIODE';

UPDATE KODELISTE SET EKSTRA_DATA=0 WHERE KODEVERK='HENDELSE_UNDERTYPE' AND EKSTRA_DATA IS NULL;
