INSERT INTO KODELISTE (id, kodeverk, kode, beskrivelse,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID)
VALUES(seq_kodeliste.nextval, 'VENT_AARSAK', 'VENT_PÅ_MULIG_MOTREGNING','Mulig motregning med annen ytelse',to_date('01.01.2000','DD.MM.RRRR'),
to_date('31.12.9999','DD.MM.RRRR'),'VL',to_date(sysdate,'DD.MM.RRRR'));

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'VENT_AARSAK','VENT_PÅ_MULIG_MOTREGNING','NB','Mulig motregning med annen ytelse','VL',to_date(sysdate,'DD.MM.RRRR'));

update AKSJONSPUNKT set VENT_AARSAK = 'VENT_PÅ_TILBAKEKREVINGSGRUNNLAG' where VENT_AARSAK = 'VENT_PÅ_ØKONOMI';
update AKSJONSPUNKT set VENT_AARSAK = 'AVV_DOK' where VENT_AARSAK = 'SCANN';

update HISTORIKKINNSLAG_FELT set TIL_VERDI_KODE = 'VENT_PÅ_TILBAKEKREVINGSGRUNNLAG'
where HISTORIKKINNSLAG_FELT_TYPE = 'AARSAK' and KL_TIL_VERDI = 'VENT_AARSAK' and TIL_VERDI_KODE = 'VENT_PÅ_ØKONOMI';

update HISTORIKKINNSLAG_FELT set TIL_VERDI_KODE = 'AVV_DOK'
where HISTORIKKINNSLAG_FELT_TYPE = 'AARSAK' and KL_TIL_VERDI = 'VENT_AARSAK' and TIL_VERDI_KODE = 'SCANN';

delete from KODELISTE_NAVN_I18N where KL_KODEVERK = 'VENT_AARSAK' and KL_KODE = 'VENT_PÅ_ØKONOMI';
delete from KODELISTE_NAVN_I18N where KL_KODEVERK = 'VENT_AARSAK' and KL_KODE = 'SCANN';

delete from KODELISTE where KODEVERK = 'VENT_AARSAK' and KODE = 'VENT_PÅ_ØKONOMI';
delete from KODELISTE where KODEVERK = 'VENT_AARSAK' and KODE = 'SCANN';
