CREATE TABLE VURDERT_FORELDELSE(
  ID                        NUMBER(19, 0)               NOT NULL ,
  OPPRETTET_AV  VARCHAR2(200 CHAR) DEFAULT 'VL'         NOT NULL ,
  OPPRETTET_TID TIMESTAMP(3) DEFAULT systimestamp       NOT NULL ,
  ENDRET_AV     VARCHAR2(20 CHAR),
  ENDRET_TID    TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_VURDERT_FORELDELSE MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE  VURDERT_FORELDELSE IS 'Tabell for å lagre vurdert foreldelse';
COMMENT ON COLUMN VURDERT_FORELDELSE.ID IS 'Primary Key';


CREATE TABLE GR_VURDERT_FORELDELSE(
  ID                        NUMBER(19, 0)               NOT NULL ,
  VURDERT_FORELDELSE_ID     NUMBER(19, 0)               NOT NULL ,
  BEHANDLING_ID             NUMBER(19, 0)               NOT NULL ,
  AKTIV                     VARCHAR2(1) DEFAULT 'J'     NOT NULL ,
  OPPRETTET_AV  VARCHAR2(200 CHAR) DEFAULT 'VL'         NOT NULL ,
  OPPRETTET_TID TIMESTAMP(3) DEFAULT systimestamp       NOT NULL ,
  ENDRET_AV     VARCHAR2(20 CHAR),
  ENDRET_TID    TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_GR_VURDERT_FORELDELSE MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE  GR_VURDERT_FORELDELSE IS 'Aggregate tabell for å lagre vurdert foreldelse';
COMMENT ON COLUMN GR_VURDERT_FORELDELSE.ID IS 'Primary Key';
COMMENT ON COLUMN GR_VURDERT_FORELDELSE.VURDERT_FORELDELSE_ID IS 'FK:VURDERT_FORELDELSE';
COMMENT ON COLUMN GR_VURDERT_FORELDELSE.BEHANDLING_ID IS 'FK: BEHANDLING fremmednøkkel for tilknyttet behandling';
COMMENT ON COLUMN GR_VURDERT_FORELDELSE.AKTIV IS 'Angir status av vurdert foreldelse';

CREATE TABLE FORELDELSE_PERIODE(
  ID                        NUMBER(19, 0)               NOT NULL ,
  VURDERT_FORELDELSE_ID     NUMBER(19, 0)               NOT NULL ,
  FOM                       DATE                        NOT NULL ,
  TOM                       DATE                        NOT NULL ,
  FORELDELSE_VURDERING_TYPE VARCHAR2(100 CHAR)          NOT NULL,
  KL_FORELDELSE_VURDERING_TYPE VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('FORELDELSE_VURDERING') VIRTUAL VISIBLE,
  OPPRETTET_AV  VARCHAR2(200 CHAR) DEFAULT 'VL'         NOT NULL ,
  OPPRETTET_TID TIMESTAMP(3) DEFAULT systimestamp       NOT NULL ,
  ENDRET_AV     VARCHAR2(20 CHAR),
  ENDRET_TID    TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_FORELDELSE_PERIODE MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE  FORELDELSE_PERIODE IS 'Tabell for å lagre ny utbetaling periode opprettet av saksbehandler';
COMMENT ON COLUMN FORELDELSE_PERIODE.ID IS 'Primary Key';
COMMENT ON COLUMN FORELDELSE_PERIODE.VURDERT_FORELDELSE_ID IS 'FK:VURDERT_FORELDELSE';
COMMENT ON COLUMN FORELDELSE_PERIODE.FOM IS 'Første dag av ny utbetaling periode';
COMMENT ON COLUMN FORELDELSE_PERIODE.TOM IS 'Siste dag av ny utbetaling periode';
COMMENT ON COLUMN FORELDELSE_PERIODE.FORELDELSE_VURDERING_TYPE IS 'Foreldelse vurdering type av en periode';
COMMENT ON COLUMN FORELDELSE_PERIODE.KL_FORELDELSE_VURDERING_TYPE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';

--------------------------------------------------------
--  DDL for Index og Primary Key
--------------------------------------------------------
ALTER TABLE VURDERT_FORELDELSE  ADD CONSTRAINT PK_VURDERT_FORELDELSE PRIMARY KEY ("ID") ENABLE;

ALTER TABLE GR_VURDERT_FORELDELSE  ADD CONSTRAINT PK_GR_VURDERT_FORELDELSE PRIMARY KEY ("ID") ENABLE;

ALTER TABLE FORELDELSE_PERIODE  ADD CONSTRAINT PK_FORELDELSE_PERIODE PRIMARY KEY ("ID") ENABLE;

CREATE INDEX IDX_GR_VURDERT_FORELDELSE_1 ON GR_VURDERT_FORELDELSE ("VURDERT_FORELDELSE_ID");

CREATE INDEX IDX_FORELDELSE_PERIODE_1 ON FORELDELSE_PERIODE ("VURDERT_FORELDELSE_ID");

CREATE INDEX IDX_FORELDELSE_PERIODE_2 ON FORELDELSE_PERIODE ("FORELDELSE_VURDERING_TYPE");

--------------------------------------------------------
--  Ref Constraints for Table GR_VURDERT_FORELDELSE og FORELDELSE_PERIODE
--------------------------------------------------------

ALTER TABLE GR_VURDERT_FORELDELSE
ADD CONSTRAINT FK_GR_VURDERT_FORELDELSE_01 FOREIGN KEY ("VURDERT_FORELDELSE_ID")
REFERENCES VURDERT_FORELDELSE ("ID") ENABLE;

ALTER TABLE FORELDELSE_PERIODE
ADD CONSTRAINT FK_FORELDELSE_PERIODE_1 FOREIGN KEY ("VURDERT_FORELDELSE_ID")
REFERENCES VURDERT_FORELDELSE ("ID") ENABLE;

ALTER TABLE FORELDELSE_PERIODE
ADD CONSTRAINT FK_FORELDELSE_PERIODE_2 FOREIGN KEY ("FORELDELSE_VURDERING_TYPE","KL_FORELDELSE_VURDERING_TYPE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;