Insert into KODEVERK (KODE,KODEVERK_EIER,KODEVERK_EIER_REF,KODEVERK_EIER_VER,KODEVERK_EIER_NAVN,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,SAMMENSATT)
values ('FAG_OMRAADE_KODE','VL',null,null,'FagOmraadeKoder','N','N','FagOmraadeKoder','Fag Omraader Koder','N');

Insert into KODEVERK (KODE,KODEVERK_EIER,KODEVERK_EIER_REF,KODEVERK_EIER_VER,KODEVERK_EIER_NAVN,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,SAMMENSATT)
values ('KLASSE_KODE','VL',null,null,'KlasseKoder','N','N','KlasseKoder','Klasse koder','N');