CREATE TABLE DAGLIG_UTBETALING(
  ID                      NUMBER(19, 0)               NOT NULL ,
  UTBETALING_PERIODE_ID    NUMBER(19, 0)               NOT NULL ,
  DAG                     DATE                        NOT NULL ,
  UTBETALT_BELOEP         NUMBER(12,2)                NOT NULL,
  NY_BELOEP               NUMBER(12,2)                NOT NULL,
  SKATT_BELOEP            NUMBER(12,2),
  FEIL_UTBETALT_BELOEP    NUMBER(12,2),
  FAG_OMRAADE_KODE        VARCHAR2(100 CHAR)           NOT NULL,
  KLASSE_KODE             VARCHAR2(100 CHAR)           NOT NULL,
  KL_FAG_OMRAADE_KODE     VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('FAG_OMRAADE_KODE') VIRTUAL VISIBLE,
  KL_KLASSE_KODE          VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('KLASSE_KODE') VIRTUAL VISIBLE,
  OPPRETTET_AV  VARCHAR2(200 CHAR) DEFAULT 'VL'        NOT NULL ,
  OPPRETTET_TID TIMESTAMP(3) DEFAULT systimestamp      NOT NULL ,
  ENDRET_AV     VARCHAR2(20 CHAR),
  ENDRET_TID    TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_DAGLIG_UTBETALING MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE  DAGLIG_UTBETALING IS 'Tabell for utbelalingsinformasjon per dag';
COMMENT ON COLUMN DAGLIG_UTBETALING.ID IS 'Primary Key';
COMMENT ON COLUMN DAGLIG_UTBETALING.UTBETALING_PERIODE_ID IS 'FK:UTBETALING_PERIODER';
COMMENT ON COLUMN DAGLIG_UTBETALING.DAG IS 'utbetalingsdag';
COMMENT ON COLUMN DAGLIG_UTBETALING.UTBETALT_BELOEP IS 'Utbetalt beloep fra økonomi';
COMMENT ON COLUMN DAGLIG_UTBETALING.NY_BELOEP IS 'Riktig beloep fra økonomi';
COMMENT ON COLUMN DAGLIG_UTBETALING.SKATT_BELOEP IS 'Skatt beloep fra økonomi';
COMMENT ON COLUMN DAGLIG_UTBETALING.FEIL_UTBETALT_BELOEP IS 'Beregnet feilbetalt beloep';
COMMENT ON COLUMN DAGLIG_UTBETALING.FAG_OMRAADE_KODE IS 'Fagområde.Mulige verdier: FP, SP, PP';
COMMENT ON COLUMN DAGLIG_UTBETALING.KLASSE_KODE IS 'Klasse kode av utbelalingsinformasjon';
COMMENT ON COLUMN DAGLIG_UTBETALING.KL_FAG_OMRAADE_KODE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN DAGLIG_UTBETALING.KL_KLASSE_KODE IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';

CREATE TABLE UTBETALING_PERIODE(
  ID                    NUMBER(19, 0)               NOT NULL ,
  GRUNNLAG_OPPDATERT_ID NUMBER(19, 0)               NOT NULL ,
  FOM                   DATE                        NOT NULL ,
  TOM                   DATE                        NOT NULL ,
  OPPRETTET_AV  VARCHAR2(200 CHAR) DEFAULT 'VL'     NOT NULL ,
  OPPRETTET_TID TIMESTAMP(3) DEFAULT systimestamp   NOT NULL ,
  ENDRET_AV VARCHAR2(20 CHAR),
  ENDRET_TID TIMESTAMP(3)
);

CREATE SEQUENCE SEQ_UTBETALING_PERIODE MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE NOCYCLE;

COMMENT ON TABLE  UTBETALING_PERIODE IS 'utbelalingsinformasjon fra økonomi';
COMMENT ON COLUMN UTBETALING_PERIODE.ID IS 'Primary Key';
COMMENT ON COLUMN UTBETALING_PERIODE.GRUNNLAG_OPPDATERT_ID IS 'FK:GRUNNLAG_OPPDATERT';
COMMENT ON COLUMN UTBETALING_PERIODE.FOM IS 'Første dag av utbetaling periode';
COMMENT ON COLUMN UTBETALING_PERIODE.TOM IS 'Siste dag av utbetaling periode';

--------------------------------------------------------
--  DDL for Index og Primary Key
--------------------------------------------------------

ALTER TABLE DAGLIG_UTBETALING  ADD CONSTRAINT PK_DAGLIG_UTBETALING PRIMARY KEY ("ID") ENABLE;

ALTER TABLE UTBETALING_PERIODE  ADD CONSTRAINT PK_UTBETALING_PERIODE PRIMARY KEY ("ID") ENABLE;

CREATE INDEX IDX_DAGLIG_UTBETALING_1 ON DAGLIG_UTBETALING ("UTBETALING_PERIODE_ID");

CREATE INDEX IDX_DAGLIG_UTBETALING_2 ON DAGLIG_UTBETALING ("FAG_OMRAADE_KODE");

CREATE INDEX IDX_DAGLIG_UTBETALING_3 ON DAGLIG_UTBETALING ("KLASSE_KODE");

CREATE INDEX IDX_UTBETALING_PERIODE_1 ON UTBETALING_PERIODE ("GRUNNLAG_OPPDATERT_ID");

--------------------------------------------------------
--  Ref Constraints for Table DAGLIG_UTBETALING og UTBETALING_PERIODE
--------------------------------------------------------

ALTER TABLE DAGLIG_UTBETALING
ADD CONSTRAINT FK_DAGLIG_UTBETALING_01 FOREIGN KEY ("UTBETALING_PERIODE_ID")
REFERENCES UTBETALING_PERIODE ("ID") ENABLE;

ALTER TABLE DAGLIG_UTBETALING
ADD CONSTRAINT FK_DAGLIG_UTBETALING_02 FOREIGN KEY ("FAG_OMRAADE_KODE","KL_FAG_OMRAADE_KODE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

ALTER TABLE DAGLIG_UTBETALING
ADD CONSTRAINT FK_DAGLIG_UTBETALING_03 FOREIGN KEY ("KLASSE_KODE","KL_KLASSE_KODE")
REFERENCES KODELISTE("KODE","KODEVERK") ENABLE;

ALTER TABLE UTBETALING_PERIODE
ADD CONSTRAINT FK_UTBETALING_PERIODE_01 FOREIGN KEY ("GRUNNLAG_OPPDATERT_ID")
REFERENCES GRUNNLAG_OPPDATERT ("ID") ENABLE;

--------------------------------------------------------
--  Add column for Table GRUNNLAG_OPPDATERT
--------------------------------------------------------
ALTER TABLE GRUNNLAG_OPPDATERT ADD AKTIV VARCHAR2(1) DEFAULT 'J' NOT NULL;

COMMENT ON COLUMN GRUNNLAG_OPPDATERT.AKTIV IS 'Angir status av grunnlag fra økonomi';