ALTER TABLE FAKTA_FEILUTBETALING ADD BEGRUNNELSE VARCHAR2(4000 CHAR);

COMMENT ON COLUMN FAKTA_FEILUTBETALING.BEGRUNNELSE is 'Begrunnelse for endringer gjort i fakta om feilutbetaling';

ALTER TABLE AKSJONSPUNKT DROP COLUMN PERIODE_FOM;

ALTER TABLE AKSJONSPUNKT DROP COLUMN PERIODE_TOM;

ALTER TABLE AKSJONSPUNKT DROP COLUMN BESLUTTERS_BEGRUNNELSE;

ALTER TABLE AKSJONSPUNKT DROP COLUMN TOTRINN_BEHANDLING_GODKJENT;

ALTER TABLE AKSJONSPUNKT DROP COLUMN BEGRUNNELSE;
