Insert into BEHANDLING_STEG_TYPE (KODE,NAVN,BEHANDLING_STATUS_DEF,BESKRIVELSE)
values ('VFORELDETSTEG','Vurder foreldelse','UTRED','Vurder om feilutbetalte perioder er foreldet.');

Insert into VURDERINGSPUNKT_DEF (KODE,BEHANDLING_STEG,VURDERINGSPUNKT_TYPE,NAVN)
values ('VFORELDETSTEG.INN','VFORELDETSTEG','INN','Vurder foreldelse - Inngang');

Insert into VURDERINGSPUNKT_DEF (KODE,BEHANDLING_STEG,VURDERINGSPUNKT_TYPE,NAVN)
values ('VFORELDETSTEG.UT','VFORELDETSTEG','UT','Vurder foreldelse - Utgang');

insert into BEHANDLING_TYPE_STEG_SEKV (ID, BEHANDLING_TYPE, BEHANDLING_STEG_TYPE, SEKVENS_NR)
VALUES (SEQ_BEHANDLING_TYPE_STEG_SEKV.nextval, 'BT-007', 'VFORELDETSTEG', 80);

Insert into AKSJONSPUNKT_DEF (KODE,NAVN,VURDERINGSPUNKT,BESKRIVELSE,TOTRINN_BEHANDLING_DEFAULT,AKSJONSPUNKT_TYPE,TILBAKEHOPP_VED_GJENOPPTAKELSE,LAG_UTEN_HISTORIKK, SKJERMLENKE_TYPE)
values ('5003','Vurder foreldelse','VTILBSTEG.INN','Vurder foreldelse','N','MANU','N','N', '-');

INSERT INTO KONFIG_VERDI_KODE (KODE, NAVN, KONFIG_GRUPPE, KONFIG_TYPE, BESKRIVELSE)
VALUES ('foreldelse.antallmaaneder', 'Frist - Foreldelse', 'INGEN', 'PERIOD', 'Angir antall måneder før foreldelse for tilbakekreving');

INSERT INTO KONFIG_VERDI (ID,KONFIG_KODE,KONFIG_GRUPPE,KONFIG_VERDI,GYLDIG_FOM,GYLDIG_TOM)
VALUES (SEQ_KONFIG_VERDI.nextval,'foreldelse.antallmaaneder','INGEN','P30M',to_date('01.01.2016','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));


Insert into KODEVERK (KODE,KODEVERK_EIER,KODEVERK_EIER_REF,KODEVERK_EIER_VER,KODEVERK_EIER_NAVN,KODEVERK_SYNK_NYE,KODEVERK_SYNK_EKSISTERENDE,NAVN,BESKRIVELSE,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,SAMMENSATT)
values ('FORELDELSE_VURDERING','VL',null,null,null,'J','J','ForeldelseVurderingType','Type vurdering av om en feilutbetalt periode er foreldet','VL',to_timestamp('23.08.2018','DD.MM.RRRR'),null,null,'N');

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FORELDELSE_VURDERING','IKKE_VURDERT',null,'Perioden er ikke vurdert',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FORELDELSE_VURDERING','FORELDET',null,'Perioden er vurdert til å være foreldet',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FORELDELSE_VURDERING','IKKE_FORELDET',null,'Perioden er vurdert til å ikke være foreldet',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));

Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM)
values (seq_kodeliste.nextval,'FORELDELSE_VURDERING','TILLEGGSFRIST',null,'Perioden er vurdert til å ilegges en tillegssfrist for foreldelse',to_date('01.01.2000','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));