INSERT INTO KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,BESKRIVELSE,GYLDIG_FOM,GYLDIG_TOM,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID,EKSTRA_DATA)
VALUES (SEQ_KODELISTE.NEXTVAL,'BEHANDLING_TYPE','BT-009',null,'Revurdering tilbakekreving',to_date(sysdate,'DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'),'VL',
to_date(sysdate,'DD.MM.RRRR'),null,null,null);

INSERT INTO KODELISTE_NAVN_I18N (ID,KL_KODEVERK,KL_KODE,SPRAK,NAVN,OPPRETTET_AV,OPPRETTET_TID,ENDRET_AV,ENDRET_TID)
VALUES (SEQ_KODELISTE_NAVN_I18N.NEXTVAL,'BEHANDLING_TYPE','BT-009','NB','Revurdering tilbakekreving','VL',to_date(sysdate,'DD.MM.RRRR'),null,null);

UPDATE BEHANDLING_TYPE_STEG_SEKV SET BEHANDLING_TYPE='BT-009' WHERE BEHANDLING_TYPE='BT-008';

DELETE KODELISTE_NAVN_I18N WHERE KL_KODE='BT-008' AND KL_KODEVERK='BEHANDLING_TYPE';
DELETE KODELISTE WHERE KODE='BT-008' AND KODEVERK='BEHANDLING_TYPE';
