UPDATE KODELISTE_NAVN_I18N SET NAVN='Nye registeropplysninger' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='NYE_REGOPPLYSNINGER';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Klagebehandling NFP' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='KLAGE_BEH_NFP';

UPDATE KODELISTE_NAVN_I18N SET NAVN='Vedtak foreslått og sendt til beslutter' WHERE KL_KODEVERK='HISTORIKKINNSLAG_TYPE' AND KL_KODE='FORSLAG_VEDTAK';
