-- SETT OPP TABELL
CREATE TABLE KODELISTE_NAVN_I18N
(
  ID            NUMBER(19, 0)                     NOT NULL,
  KL_KODEVERK   VARCHAR2(100 CHAR)                NOT NULL,
  KL_KODE       VARCHAR2(100 CHAR)                NOT NULL,
  SPRAK         VARCHAR2(3 CHAR)                  NOT NULL,
  NAVN          VARCHAR2(256 CHAR),
  OPPRETTET_AV  VARCHAR2(20 CHAR) DEFAULT 'VL'    NOT NULL,
  OPPRETTET_TID TIMESTAMP(3) DEFAULT systimestamp NOT NULL,
  ENDRET_AV     VARCHAR2(20 CHAR),
  ENDRET_TID    TIMESTAMP(3),
  CONSTRAINT FK_KODELISTE_2 FOREIGN KEY (KL_KODEVERK, KL_KODE) REFERENCES KODELISTE (KODEVERK, KODE)
);
CREATE SEQUENCE SEQ_KODELISTE_NAVN_I18N MINVALUE 1 START WITH 1000000 INCREMENT BY 50 NOCACHE  NOCYCLE;

ALTER TABLE KODELISTE_NAVN_I18N ADD CONSTRAINT PK_KODELISTE_NAVN_I18N PRIMARY KEY (ID);

COMMENT ON TABLE KODELISTE_NAVN_I18N IS 'Kodeliste navn-verdier med oversettelser for støttede språk';
COMMENT ON COLUMN KODELISTE_NAVN_I18N.KL_KODE IS 'FK - Refererer til kode i kodeliste';
COMMENT ON COLUMN KODELISTE_NAVN_I18N.KL_KODEVERK IS 'FK - Refererer til kodeverk i kodeliste';
COMMENT ON COLUMN KODELISTE_NAVN_I18N.SPRAK IS 'Språket brukt i oversettelsen';
COMMENT ON COLUMN KODELISTE_NAVN_I18N.NAVN IS 'Oversatt visnings-navn for kodeverk';

-- MIGRER VERDIER FRA KODELISTE
INSERT INTO KODELISTE_NAVN_I18N (ID, KL_KODEVERK, KL_KODE, SPRAK, NAVN)
SELECT SEQ_KODELISTE_NAVN_I18N.nextval, KODEVERK, KODE, SPRAK, NAVN
FROM KODELISTE;

-- DROP KOLONNER FRA KODELISTE
ALTER TABLE KODELISTE DROP COLUMN NAVN;
ALTER TABLE KODELISTE DROP COLUMN SPRAK;

-- OPPDATERER NOEN OVERSETTELSER
UPDATE KODELISTE_NAVN_I18N SET NAVN = 'Førstegangsbehandling' WHERE KL_KODEVERK='BEHANDLING_TYPE' AND KL_KODE='BT-002';
UPDATE KODELISTE_NAVN_I18N SET NAVN = 'Klage' WHERE KL_KODEVERK='BEHANDLING_TYPE' AND KL_KODE='BT-003';
UPDATE KODELISTE_NAVN_I18N SET NAVN = 'Revurdering' WHERE KL_KODEVERK='BEHANDLING_TYPE' AND KL_KODE='BT-004';
UPDATE KODELISTE_NAVN_I18N SET NAVN = 'Tilbakebetaling endring' WHERE KL_KODEVERK='BEHANDLING_TYPE' AND KL_KODE='BT-005';
UPDATE KODELISTE_NAVN_I18N SET NAVN = 'Dokumentinnsyn' WHERE KL_KODEVERK='BEHANDLING_TYPE' AND KL_KODE='BT-006';
UPDATE KODELISTE_NAVN_I18N SET NAVN = 'Tilbakekreving' WHERE KL_KODEVERK='BEHANDLING_TYPE' AND KL_KODE='BT-007';
UPDATE KODELISTE_NAVN_I18N SET NAVN = 'Inntrekk' WHERE KL_KODEVERK='BEHANDLING_TYPE' AND KL_KODE='BT-008';
UPDATE KODELISTE_NAVN_I18N SET NAVN = 'Ikke definert' WHERE KL_KODEVERK='BEHANDLING_TYPE' AND KL_KODE='-';