name: Bygg pull request

on:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '**.editorconfig'
      - '**.md'
      - '**.MD'
      - 'docs/**'

env:
  GITHUB_USERNAME: x-access-token
  GITHUB_PASSWORD: ${{ secrets.GH_ACCESS_TOKEN }} # Cannot use GITHUB_TOKEN: https://github.community/t/github-token-cannot-access-private-packages/16621#M2148
  TZ: "Europe/Oslo"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: v2-${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: v2-${{ runner.os }}-maven-

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 15

      - name: Log into ghcr registry
        # GITHUB_TOKEN fungere ikke for PR enda... https://github.community/t/cant-authenticate-with-actions-token-for-pr-event/170752
        # run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username "x-access-token" --password-stdin ghcr.io
        run: echo "${{ secrets.GH_ACCESS_TOKEN }}" | docker login --username "x-access-token" --password-stdin ghcr.io

      - name: Hent og start Oracle image
        id: oracle
        shell: bash
        run: |
          .oracle/start-oracle.sh &

      - name: Set build version
        run: |
          echo "BUILD_VERSION=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build (kompiler)
        run: |
          echo "Building $BUILD_VERSION"
          export MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
          mvn test-compile -P-migrer-db -T2 --batch-mode --settings ./.m2/settings.xml -Dchangelist= -Dsha1=-${BUILD_VERSION}

      - name: Vent til oracle er oppe
        id: vent-til-oracle-er-klar
        run: |
          .oracle/vent-til-oracle-er-klar.sh

      - name: Build (test)
        run: |
          echo "Building $BUILD_VERSION"
          export MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
          mvn package -T2 --batch-mode --settings ./.m2/settings.xml -Dchangelist= -Dsha1=-${BUILD_VERSION}
