name: Bygg pull request

on: [pull_request]

env:
  TZ: "Europe/Oslo"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2

      - name: Hent og start Oracle image
        id: oracle
        shell: bash
        run: |
          echo $GITHUB_TOKEN | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          oracle/start-oracle.sh &
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Sett opp Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Set build version
        run: |
          echo "::set-env name=BUILD_VERSION::$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)"

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: v2-${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: v2-${{ runner.os }}-maven-

      - name: Build (kompiler)
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        shell: bash
        run: |
          echo "Building $BUILD_VERSION"
          mvn test-compile -P-migrer-db -T2 --quiet --batch-mode --settings ./.m2/settings.xml -Dchangelist= -Dsha1=-${BUILD_VERSION}

      - name: Vent til oracle er oppe
        id: vent-til-oracle-er-klar
        shell: bash
        run: |
          oracle/vent-til-oracle-er-klar.sh

      - name: Build (test)
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        shell: bash
        run: |
          echo "Building $BUILD_VERSION"
          export MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
          mvn test -T2 --quiet --batch-mode --settings ./.m2/settings.xml -Dchangelist= -Dsha1=-${BUILD_VERSION}
