name: Bygg pull request

on:
  pull_request_target:
    paths-ignore:
      - '.gitignore'
      - '**.editorconfig'
      - '**.md'
      - '**.MD'
      - 'docs/**'

env:
  GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }} # NB: må ha PAT pga avhengighet mot private repo: fp-jms-integrasjon
  TZ: "Europe/Oslo"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b # Use commit-sha1 instead of tag for security concerns
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Hent og start Oracle image
        run: |
          echo "Henter og starter Oracle image"
          cd .oracle
          docker-compose up --quiet-pull > nohup.out 2>&1 &
          sh -c 'tail -n +0 -f nohup.out | { sed "/Database opened./q" && kill $$; }' || true

      - name: Set build version
        run: |
          echo "BUILD_VERSION=2.0-$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build (kompiler)
        run: |
          echo "Building $BUILD_VERSION"
          export MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
          mvn test-compile -P-migrer-db -T2 --batch-mode --settings .github/.m2/settings.xml -Drevision=${BUILD_VERSION}

      - name: Build (test)
        run: |
          echo "Building $BUILD_VERSION"
          export MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
          mvn package -T2 --batch-mode --settings .github/.m2/settings.xml -Drevision=${BUILD_VERSION}
