name: Monitor dependencies with Dependabot
on:
  push:
    branches:
      - master
    paths:
      - "pom.xml"
      - "**/pom.xml"
  workflow_dispatch:
  
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Create m2-settings with private repository access
        uses: whelk-io/maven-settings-xml-action@7c60eb95b2d5ec18f2e0e29f34c9ed69475e7a96
        with:
          repositories: |
            [
              {
                "id": "central",
                "name": "Maven Central",
                "url": "https://repo.maven.apache.org/maven2"
              },
              {
                "id": "github",
                "name": "github",
                "url": "https://maven.pkg.github.com/${{ github.repository }}"
              }
            ]
          servers: |
            [
              {
                "id": "github",
                "password": "${{ secrets.READER_TOKEN }}",
                "username": "${{ github.actor }}"
              }
            ]
          output_file: m2-settings.xml

      - name: Submit Dependency Snapshot to Github Security
        uses: advanced-security/maven-dependency-submission-action@d682d5d68a398c90e9b35f8c564cd8e1918d6a24
        with:
          settings-file: m2-settings.xml
          maven-args: -DskipTests
