name: Deploy kafka topics

on:
  push:
    paths:
      - 'kafka/**'
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-topics:
    strategy:
      matrix:
        topic: [dvh-vedtak, dvh-sakshendelse, k9los-hendelse, dvh-ettersendelse]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1

      - name: Deploy topics to dev
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # ratchet:nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY_K9 }}
          CLUSTER: dev-gcp
          RESOURCE: kafka/k9tilbake/dev/topic-${{ matrix.topic }}.yaml

      - name: Deploy topics to prod
        if: github.ref == 'refs/heads/master'
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # ratchet:nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY_K9 }}
          CLUSTER: prod-gcp
          RESOURCE: kafka/k9tilbake/prod/topic-${{ matrix.topic }}.yaml
