name: Deploy kafka topics

on:
  push:
    paths:
      - 'kafka/**'
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-topics:
    strategy:
      matrix:
        topic: [dvh-vedtak, dvh-sakshendelse, k9los-hendelse, dvh-ettersendelse]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0

      - name: Deploy topics to dev
        uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # ratchet:nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY_K9 }}
          CLUSTER: dev-gcp
          RESOURCE: kafka/k9tilbake/dev/topic-${{ matrix.topic }}.yaml

      - name: Deploy topics to prod
        if: github.ref == 'refs/heads/master'
        uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # ratchet:nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY_K9 }}
          CLUSTER: prod-gcp
          RESOURCE: kafka/k9tilbake/prod/topic-${{ matrix.topic }}.yaml
