name: Comment

on:
  workflow_call:
    inputs:
      issue-number:
        required: true
        type: string
        description: 'The deployment issue.'
      cluster:
        required: true
        type: string
        description: 'The deployment cluster.'
      namespace:
        required: true
        type: string
        description: 'The deployment namespace.'

jobs:
  promote:
    name: promote
    runs-on: 'ubuntu-latest'
    steps:
      - uses: navikt/github-app-token-generator@v1.2
        id: get-token
        with:
          private-key: ${{ secrets.FP_PRIVATE_KEY }}
          app-id: ${{ secrets.FP_APP_ID }}

      - name: Promote til K9 dev
        run: |
          curl -XPOST -u "x-access-token:${{ steps.get-token.outputs.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{
                "event_type": "promote-command",
                "client_payload": {
                  "github": {
                      "payload": {
                          "issue": {
                              "number": "${{ inputs.issue-number }}"
                  }}},
                  "slash_command": {
                      "args": {
                          "unnamed": {
                              "arg1": "${{ inputs.cluster }}",
                              "arg2": "${{ inputs.namespace }}"
                  }}}
                }
              }'